# -*- coding: utf-8 -*-
"""
WORLD 2 — Unit 2 · Family & Feelings  (Levels 111-120)
Grammar arc: the verb "to be" — am / is / are, negatives, questions and short
answers, irregular plurals, demonstratives + to be, and the air/ear reading
sounds. Every sentence, option and answer is hand-checked correct English.
"""

from grammar_helpers import g, t, f, tok, srt, qa, L, W


WORLD = W("Family & Feelings", "The verb to be — Magic Academy Unit 2", [

    # --- Level 1: I am / You are --------------------------------------------
    L("Gondax Castle",
      [("happy", "😊"), ("sad", "😢"), ("friend", "👫"), ("tired", "😴"), ("Tom", "👦"), ("Anna", "👧")],
      "I am / You are",
      ["I am happy.", "You are my friend.", "I am Tom.", "You are kind.", "I am tired.", "You are sad."],
      [g("I ___ happy.", ["am", "are"], "am", "😊"),
       g("You ___ my friend.", ["are", "am"], "are", "👫"),
       g("I ___ tired.", ["am", "are"], "am", "😴"),
       g("You ___ kind.", ["are", "am"], "are", "💛")],
      [t("I ->", "I", ["am", "are", "is"], "am"),
       t("You ->", "you", ["are", "am", "is"], "are"),
       t("one friend -> many...?", "friend", ["friends", "friendes", "friend"], "friends")],
      [f("I am happy.", "I are happy.", "😊"),
       f("You are my friend.", "You am my friend.", "👫"),
       f("I am tired.", "I is tired.", "😴"),
       f("You are sad.", "You is sad.", "😢")],
      srt("I am ...", "You are ...",
          [tok("I am happy", "A", "😊"), tok("I am tired", "A", "😴"), tok("I am Tom", "A", "👦"),
           tok("You are kind", "B", "💛"), tok("You are sad", "B", "😢"), tok("You are my friend", "B", "👫")]),
      [qa("Are you happy?", "Yes, I am."),
       qa("Are you tired?", "No, I am not."),
       qa("Are you Tom?", "Yes, I am Tom."),
       qa("How are you?", "I am fine.")]),

    # --- Level 2: He / She / It is ------------------------------------------
    L("The Royal Boat",
      [("mom", "👩"), ("dad", "👨"), ("sister", "👧"), ("brother", "👦"), ("grandma", "👵"), ("grandpa", "👴")],
      "He / She / It is",
      ["She is my sister.", "He is my dad.", "She is my mom.", "He is my brother.", "It is my cat.", "She is my grandma."],
      [g("She ___ my sister.", ["is", "are"], "is", "👧"),
       g("He ___ my dad.", ["is", "are"], "is", "👨"),
       g("___ is my mom.", ["She", "They"], "She", "👩"),
       g("It ___ my cat.", ["is", "are"], "is", "🐱")],
      [t("He ->", "he", ["is", "am", "are"], "is"),
       t("She ->", "she", ["is", "are", "am"], "is"),
       t("It ->", "it", ["is", "are", "am"], "is")],
      [f("He is my dad.", "He are my dad.", "👨"),
       f("She is my mom.", "She are my mom.", "👩"),
       f("He is my brother.", "He am my brother.", "👦"),
       f("She is my grandma.", "She are my grandma.", "👵")],
      srt("He is ...", "She is ...",
          [tok("He is my dad", "A", "👨"), tok("He is my brother", "A", "👦"), tok("He is my grandpa", "A", "👴"),
           tok("She is my mom", "B", "👩"), tok("She is my sister", "B", "👧"), tok("She is my grandma", "B", "👵")]),
      [qa("Who is she?", "She is my sister."),
       qa("Who is he?", "He is my dad."),
       qa("Is she your mom?", "Yes, she is."),
       qa("Is he your grandpa?", "No, he is my dad.")]),

    # --- Level 3: We are / They are -----------------------------------------
    L("The Whole Family",
      [("family", "👨‍👩‍👧‍👦"), ("parents", "👫"), ("sister", "👧"), ("brother", "👦"), ("grandma", "👵"), ("grandpa", "👴")],
      "We are / They are",
      ["We are a family.", "They are my grandparents.", "We are happy.", "They are my parents.", "We are sisters.", "They are kind."],
      [g("We ___ a family.", ["are", "is"], "are", "👨‍👩‍👧‍👦"),
       g("They ___ my parents.", ["are", "is"], "are", "👫"),
       g("We ___ happy.", ["are", "is"], "are", "😊"),
       g("___ are my grandparents.", ["They", "He"], "They", "👵")],
      [t("We ->", "we", ["are", "is", "am"], "are"),
       t("They ->", "they", ["are", "is", "am"], "are"),
       t("one sister -> many...?", "sister", ["sisters", "sisteres", "sister"], "sisters")],
      [f("We are a family.", "We is a family.", "👨‍👩‍👧‍👦"),
       f("They are my parents.", "They is my parents.", "👫"),
       f("We are happy.", "We am happy.", "😊"),
       f("They are kind.", "They is kind.", "💛")],
      srt("We are ...", "They are ...",
          [tok("We are a family", "A", "👨‍👩‍👧‍👦"), tok("We are happy", "A", "😊"), tok("We are sisters", "A", "👧"),
           tok("They are my parents", "B", "👫"), tok("They are kind", "B", "💛"), tok("They are my grandparents", "B", "👵")]),
      [qa("Who are they?", "They are my parents."),
       qa("Are you a family?", "Yes, we are."),
       qa("Are they your grandparents?", "Yes, they are."),
       qa("Are you happy?", "Yes, we are happy.")]),

    # --- Level 4: to be negative (isn't / aren't) ---------------------------
    L("Not True!",
      [("happy", "😊"), ("sad", "😢"), ("angry", "😠"), ("scared", "😨"), ("tired", "😴"), ("excited", "🤩")],
      "is not / are not",
      ["He is not sad.", "They aren't angry.", "I am not tired.", "She isn't scared.", "We are not sad.", "You aren't angry."],
      [g("He ___ sad.", ["isn't", "aren't"], "isn't", "😢"),
       g("They ___ angry.", ["aren't", "isn't"], "aren't", "😠"),
       g("She ___ scared.", ["isn't", "aren't"], "isn't", "😨"),
       g("We ___ tired.", ["aren't", "isn't"], "aren't", "😴")],
      [t("He ->", "he", ["isn't", "aren't", "am not"], "isn't"),
       t("They ->", "they", ["aren't", "isn't", "am not"], "aren't"),
       t("I ->", "I", ["am not", "isn't", "aren't"], "am not")],
      [f("He is not sad.", "He are not sad.", "😢"),
       f("They aren't angry.", "They isn't angry.", "😠"),
       f("She isn't scared.", "She aren't scared.", "😨"),
       f("We are not tired.", "We is not tired.", "😴")],
      srt("isn't", "aren't",
          [tok("He isn't", "A", "👦"), tok("She isn't", "A", "👧"), tok("It isn't", "A", "🐱"),
           tok("They aren't", "B", "👨‍👩‍👧‍👦"), tok("We aren't", "B", "👫"), tok("You aren't", "B", "🧑")]),
      [qa("Are you sad?", "No, I am not."),
       qa("Is he angry?", "No, he isn't."),
       qa("Are they tired?", "No, they aren't."),
       qa("Is she scared?", "No, she isn't.")]),

    # --- Level 5: to be questions + short answers ---------------------------
    L("The Giant Eagle",
      [("happy", "😊"), ("sad", "😢"), ("ready", "✅"), ("hungry", "🍽️"), ("tired", "😴"), ("scared", "😨")],
      "Are you...? Is he...?",
      ["Are you happy?", "Is he tired?", "Am I late?", "Is she ready?", "Are they hungry?", "Yes, I am."],
      [g("___ you happy?", ["Are", "Is"], "Are", "😊"),
       g("___ he tired?", ["Is", "Are"], "Is", "😴"),
       g("___ they hungry?", ["Are", "Is"], "Are", "🍽️"),
       g("___ I late?", ["Am", "Is"], "Am", "⏰")],
      [t("He ->", "he", ["is", "are", "am"], "is"),
       t("You ->", "you", ["are", "is", "am"], "are"),
       t("I ->", "I", ["am", "are", "is"], "am")],
      [f("Are you happy?", "Is you happy?", "😊"),
       f("Is he tired?", "Are he tired?", "😴"),
       f("Are they hungry?", "Is they hungry?", "🍽️"),
       f("Is she ready?", "Am she ready?", "✅")],
      srt("Are ...?", "Is ...?",
          [tok("Are you happy?", "A", "😊"), tok("Are they ready?", "A", "✅"), tok("Are we late?", "A", "⏰"),
           tok("Is he sad?", "B", "😢"), tok("Is she tired?", "B", "😴"), tok("Is it hot?", "B", "🔥")]),
      [qa("Are you happy?", "Yes, I am."),
       qa("Is he tired?", "Yes, he is."),
       qa("Are they hungry?", "No, they aren't."),
       qa("Am I late?", "No, you aren't.")]),

    # --- Level 6: feelings + to be ------------------------------------------
    L("How do you feel?",
      [("sleepy", "😪"), ("hungry", "🍽️"), ("thirsty", "🥤"), ("bored", "😑"), ("excited", "🤩"), ("proud", "😌")],
      "I am + feeling",
      ["I am excited.", "She is sleepy.", "He is hungry.", "We are thirsty.", "They are bored.", "I am proud."],
      [g("I ___ excited.", ["am", "is"], "am", "🤩"),
       g("She ___ sleepy.", ["is", "am"], "is", "😪"),
       g("We ___ thirsty.", ["are", "is"], "are", "🥤"),
       g("He ___ hungry.", ["is", "are"], "is", "🍽️")],
      [t("I ->", "I", ["am", "are", "is"], "am"),
       t("She ->", "she", ["is", "are", "am"], "is"),
       t("We ->", "we", ["are", "is", "am"], "are")],
      [f("I am excited.", "I is excited.", "🤩"),
       f("She is sleepy.", "She are sleepy.", "😪"),
       f("They are bored.", "They is bored.", "😑"),
       f("He is hungry.", "He am hungry.", "🍽️")],
      srt("... is", "... are",
          [tok("He is proud", "A", "😌"), tok("She is bored", "A", "😑"), tok("It is hot", "A", "🔥"),
           tok("We are hungry", "B", "🍽️"), tok("They are thirsty", "B", "🥤"), tok("You are excited", "B", "🤩")]),
      [qa("How do you feel?", "I am excited."),
       qa("Are you hungry?", "Yes, I am."),
       qa("Is she sleepy?", "Yes, she is."),
       qa("Are they bored?", "No, they aren't.")]),

    # --- Level 7: irregular plurals -----------------------------------------
    L("Grandma's Chip",
      [("man", "👨"), ("woman", "👩"), ("child", "🧒"), ("foot", "🦶"), ("tooth", "🦷"), ("mouse", "🐭")],
      "one -> many (irregular)",
      ["I have two feet.", "These are my teeth.", "The children are happy.", "Two men are here.", "I see three mice.", "The women are kind."],
      [g("I have two ___.", ["feet", "foots"], "feet", "🦶"),
       g("These are my ___.", ["teeth", "tooths"], "teeth", "🦷"),
       g("The ___ are happy.", ["children", "childs"], "children", "🧒"),
       g("I see three ___.", ["mice", "mouses"], "mice", "🐭")],
      [t("one man -> many...?", "man", ["men", "mans", "man"], "men"),
       t("one woman -> many...?", "woman", ["women", "womans", "woman"], "women"),
       t("one child -> many...?", "child", ["children", "childs", "childrens"], "children")],
      [f("These are my feet.", "These are my foots.", "🦶"),
       f("I have two teeth.", "I have two tooths.", "🦷"),
       f("The children are here.", "The childs are here.", "🧒"),
       f("Two men are tall.", "Two mans are tall.", "👨")],
      srt("one", "many",
          [tok("man", "A", "👨"), tok("child", "A", "🧒"), tok("foot", "A", "🦶"),
           tok("men", "B", "👨"), tok("children", "B", "🧒"), tok("feet", "B", "🦶")]),
      [qa("How many feet do you have?", "I have two feet."),
       qa("What are these?", "They are my teeth."),
       qa("Are the children happy?", "Yes, the children are happy."),
       qa("How many mice do you see?", "I see three mice.")]),

    # --- Level 8: demonstratives + to be ------------------------------------
    L("This is my family",
      [("mom", "👩"), ("dad", "👨"), ("sister", "👧"), ("brother", "👦"), ("grandma", "👵"), ("grandpa", "👴")],
      "This is / These are",
      ["This is my mom.", "These are my brothers.", "This is my dad.", "These are my sisters.", "This is my grandma.", "These are my parents."],
      [g("This ___ my mom.", ["is", "are"], "is", "👩"),
       g("These ___ my brothers.", ["are", "is"], "are", "👦"),
       g("___ is my dad.", ["This", "These"], "This", "👨"),
       g("___ are my sisters.", ["These", "This"], "These", "👧")],
      [t("one sister -> many...?", "sister", ["sisters", "sisteres", "sister"], "sisters"),
       t("one brother -> many...?", "brother", ["brothers", "brotheres", "brother"], "brothers"),
       t("one parent -> many...?", "parent", ["parents", "parentes", "parent"], "parents")],
      [f("This is my mom.", "This are my mom.", "👩"),
       f("These are my brothers.", "These is my brothers.", "👦"),
       f("This is my dad.", "This are my dad.", "👨"),
       f("These are my sisters.", "These is my sisters.", "👧")],
      srt("This is ...", "These are ...",
          [tok("This is my mom", "A", "👩"), tok("This is my dad", "A", "👨"), tok("This is my grandma", "A", "👵"),
           tok("These are my brothers", "B", "👦"), tok("These are my sisters", "B", "👧"), tok("These are my parents", "B", "👫")]),
      [qa("Who is this?", "This is my mom."),
       qa("Who are these?", "These are my brothers."),
       qa("Is this your dad?", "Yes, it is."),
       qa("Are these your sisters?", "Yes, they are.")]),

    # --- Level 9: reading sounds air / ear ----------------------------------
    L("Sound Lab: air & ear",
      [("bear", "🐻"), ("hair", "💇"), ("chair", "🪑"), ("ear", "👂"), ("near", "📍"), ("year", "📅")],
      "air / ear sounds",
      ["I sit on a chair.", "This is a bear.", "I hear with my ear.", "See you next year.", "The shop is near.", "I brush my hair."],
      [g("I sit on a ___.", ["chair", "bear"], "chair", "🪑"),
       g("This is a ___.", ["bear", "chair"], "bear", "🐻"),
       g("I hear with my ___.", ["ear", "air"], "ear", "👂"),
       g("I brush my ___.", ["hair", "hear"], "hair", "💇")],
      [t("one chair -> many...?", "chair", ["chairs", "chaires", "chair"], "chairs"),
       t("one bear -> many...?", "bear", ["bears", "beares", "bear"], "bears"),
       t("one year -> many...?", "year", ["years", "yeares", "year"], "years")],
      [f("This is a chair.", "This is a chian.", "🪑"),
       f("This is a bear.", "This is a baer.", "🐻"),
       f("I brush my hair.", "I brush my hiar.", "💇"),
       f("See you next year.", "See you next yaer.", "📅")],
      srt("air sound", "ear sound",
          [tok("bear", "A", "🐻"), tok("hair", "A", "💇"), tok("chair", "A", "🪑"),
           tok("ear", "B", "👂"), tok("near", "B", "📍"), tok("year", "B", "📅")]),
      [qa("What do you sit on?", "I sit on a chair."),
       qa("What is this?", "It is a bear."),
       qa("What do you hear with?", "I hear with my ear."),
       qa("When will I see you?", "See you next year.")]),

    # --- Level 10: Unit 2 review --------------------------------------------
    L("Family Champion",
      [("happy", "😊"), ("sad", "😢"), ("mom", "👩"), ("dad", "👨"), ("child", "🧒"), ("family", "👨‍👩‍👧‍👦")],
      "Unit 2 review",
      ["I am happy.", "She is my mom.", "We are a family.", "He isn't sad.", "Are you my friend?", "The children are here."],
      [g("I ___ happy.", ["am", "is"], "am", "😊"),
       g("She ___ my mom.", ["is", "are"], "is", "👩"),
       g("We ___ a family.", ["are", "is"], "are", "👨‍👩‍👧‍👦"),
       g("The ___ are here.", ["children", "childs"], "children", "🧒")],
      [t("I ->", "I", ["am", "are", "is"], "am"),
       t("She ->", "she", ["is", "are", "am"], "is"),
       t("one child -> many...?", "child", ["children", "childs", "childrens"], "children")],
      [f("I am happy.", "I is happy.", "😊"),
       f("She is my mom.", "She are my mom.", "👩"),
       f("He isn't sad.", "He aren't sad.", "😢"),
       f("The children are here.", "The childs are here.", "🧒")],
      srt("... is", "... are",
          [tok("He is happy", "A", "😊"), tok("She is my mom", "A", "👩"), tok("It is here", "A", "🏠"),
           tok("We are a family", "B", "👨‍👩‍👧‍👦"), tok("They are sad", "B", "😢"), tok("You are kind", "B", "💛")]),
      [qa("Are you happy?", "Yes, I am."),
       qa("Is he sad?", "No, he isn't."),
       qa("Who is she?", "She is my mom."),
       qa("How many children?", "Three children.")]),
])
