# -*- coding: utf-8 -*-
"""
WORLD 3 — Unit 3 · Activities  (Levels 121-130)

Grammar arc: the modal CAN / CAN'T for ability.
  I can + verb -> I can't + verb -> Can you...? / short answers ->
  He/She can + verb -> action verbs -> animals can -> can vs can't ->
  What can you do? -> reading ur/ir/or -> Unit 3 review.

KEY RULE enforced everywhere: after a modal (can / can't) the verb is ALWAYS
the BASE form. Never "can swims", "can to swim", "can flying". Every correct
sentence keeps the base verb; only the deliberately-wrong "fix" halves break it.
"""


from grammar_helpers import g, t, f, tok, srt, qa, L, W


WORLD = W("Activities", "Can & can't — Magic Academy Unit 3", [

    # -- Level 1 -----------------------------------------------------------
    L("The Trampoline",
      [("run", "🏃"), ("jump", "🤸"), ("swim", "🏊"), ("dance", "💃"), ("sing", "🎤"), ("draw", "✏️")],
      "I can + verb",
      ["I can jump.", "I can swim.", "I can run fast.", "I can sing a song.",
       "I can dance.", "I can draw a cat."],
      [g("I can ___ high.", ["jump", "jumps"], "jump", "🤸"),
       g("I can ___ fast.", ["run", "runs"], "run", "🏃"),
       g("I can ___ well.", ["swim", "swimming"], "swim", "🏊"),
       g("I ___ sing.", ["can", "cans"], "can", "🎤")],
      [t("can + jump ->", "jump", ["jump", "jumps", "jumping"], "jump"),
       t("can + run ->", "run", ["run", "runs", "running"], "run"),
       t("can + swim ->", "swim", ["swim", "swims", "swimming"], "swim")],
      [f("I can jump.", "I can jumps.", "🤸"),
       f("I can swim.", "I can swims.", "🏊"),
       f("I can run.", "I can running.", "🏃"),
       f("I can dance.", "I can dances.", "💃")],
      srt("can + base ✓", "wrong form ✗",
          [tok("can jump", "A", "🤸"), tok("can run", "A", "🏃"), tok("can swim", "A", "🏊"),
           tok("can jumps", "B", "🤸"), tok("can runs", "B", "🏃"), tok("can sings", "B", "🎤")]),
      [qa("What can you do?", "I can jump."),
       qa("Can you swim?", "Yes, I can."),
       qa("Can you run fast?", "Yes, I can run fast."),
       qa("What can you do on the trampoline?", "I can jump high.")]),

    # -- Level 2 -----------------------------------------------------------
    L("Astro Gets a Sticker",
      [("paint", "🎨"), ("write", "✍️"), ("fly", "🕊️"), ("cut", "✂️"), ("read", "📖"), ("draw", "✏️")],
      "I can't + verb",
      ["I can't fly.", "I can't cut it.", "I can't paint well.",
       "I can't read this word.", "I can't write it.", "I can't draw a dog."],
      [g("I can't ___ .", ["fly", "flies"], "fly", "🕊️"),
       g("I can't ___ it.", ["cut", "cuts"], "cut", "✂️"),
       g("I can't ___ well.", ["paint", "paints"], "paint", "🎨"),
       g("I can't ___ this.", ["read", "reading"], "read", "📖")],
      [t("can't + fly ->", "fly", ["fly", "flies", "flying"], "fly"),
       t("can't + read ->", "read", ["read", "reads", "reading"], "read"),
       t("can't + paint ->", "paint", ["paint", "paints", "painting"], "paint")],
      [f("I can't fly.", "I can't flies.", "🕊️"),
       f("I can't cut it.", "I can't cuts it.", "✂️"),
       f("I can't read this.", "I can't reads this.", "📖"),
       f("I can't paint.", "I can't painting.", "🎨")],
      srt("can't + base ✓", "wrong form ✗",
          [tok("can't fly", "A", "🕊️"), tok("can't cut", "A", "✂️"), tok("can't read", "A", "📖"),
           tok("can't flies", "B", "🕊️"), tok("can't cuts", "B", "✂️"), tok("can't reads", "B", "📖")]),
      [qa("Can you fly?", "No, I can't."),
       qa("Can you cut this?", "No, I can't cut it."),
       qa("Can birds read?", "No, they can't."),
       qa("Can you paint?", "No, I can't paint.")]),

    # -- Level 3 -----------------------------------------------------------
    L("Can you?",
      [("swim", "🏊"), ("climb", "🧗"), ("skip", "🏃‍♀️"), ("read", "📖"), ("write", "✍️"), ("help", "🤝")],
      "Can you...? Yes / No",
      ["Can you swim?", "Yes, I can.", "No, I can't.", "Can you climb?",
       "Can you help me?", "Yes, I can help."],
      [g("___ you swim?", ["Can", "Do"], "Can", "🏊"),
       g("___ you climb?", ["Can", "Are"], "Can", "🧗"),
       g("Can you ___?", ["skip", "skips"], "skip", "🏃‍♀️"),
       g("Yes, I ___.", ["can", "am"], "can", "✍️")],
      [t("Can you + swim ->", "swim", ["swim", "swims", "swimming"], "swim"),
       t("Can you + climb ->", "climb", ["climb", "climbs", "climbing"], "climb"),
       t("Can you + read ->", "read", ["read", "reads", "reading"], "read")],
      [f("Can you swim?", "Can you swims?", "🏊"),
       f("Can you climb?", "Can you climbs?", "🧗"),
       f("Can you help me?", "Can you helps me?", "🤝"),
       f("Can you read?", "Can you reading?", "📖")],
      srt("Yes, I can.", "No, I can't.",
          [tok("Yes, I can swim.", "A", "🏊"), tok("Yes, I can help.", "A", "🤝"), tok("Yes, I can read.", "A", "📖"),
           tok("No, I can't fly.", "B", "🕊️"), tok("No, I can't skip.", "B", "🏃‍♀️"), tok("No, I can't climb.", "B", "🧗")]),
      [qa("Can you swim?", "Yes, I can."),
       qa("Can you climb a tree?", "No, I can't."),
       qa("Can you help me?", "Yes, I can help."),
       qa("Can you skip?", "No, I can't skip.")]),

    # -- Level 4 -----------------------------------------------------------
    L("Astro the Balloon",
      [("float", "🎈"), ("fly", "🕊️"), ("ride", "🚲"), ("jump", "🤸"), ("run", "🏃"), ("bounce", "⛹️")],
      "He / She can + verb",
      ["She can dance.", "He can run fast.", "She can ride a bike.",
       "He can jump high.", "The balloon can float.", "She can fly a kite."],
      [g("She can ___ .", ["fly", "flies"], "fly", "🕊️"),
       g("He can ___ fast.", ["run", "runs"], "run", "🏃"),
       g("She can ___ a bike.", ["ride", "rides"], "ride", "🚲"),
       g("He ___ jump.", ["can", "cans"], "can", "🤸")],
      [t("She can + fly ->", "fly", ["fly", "flies", "flying"], "fly"),
       t("He can + jump ->", "jump", ["jump", "jumps", "jumping"], "jump"),
       t("She can + ride ->", "ride", ["ride", "rides", "riding"], "ride")],
      [f("She can fly.", "She can flies.", "🕊️"),
       f("He can run fast.", "He can runs fast.", "🏃"),
       f("She can ride a bike.", "She can rides a bike.", "🚲"),
       f("He can jump.", "He can jumps.", "🤸")],
      srt("can + base ✓", "wrong (+s) ✗",
          [tok("She can fly", "A", "🕊️"), tok("He can run", "A", "🏃"), tok("She can ride", "A", "🚲"),
           tok("She can flies", "B", "🕊️"), tok("He can runs", "B", "🏃"), tok("She can rides", "B", "🚲")]),
      [qa("What can she do?", "She can dance."),
       qa("Can he run fast?", "Yes, he can."),
       qa("What can he do?", "He can ride a bike."),
       qa("Can she fly a kite?", "Yes, she can.")]),

    # -- Level 5 -----------------------------------------------------------
    L("Action Station",
      [("run", "🏃"), ("skip", "🏃‍♀️"), ("jump", "🤸"), ("spin", "🌀"), ("lift", "🏋️"), ("throw", "⚾")],
      "can + action verb",
      ["I can run and jump.", "She can spin around.", "He can lift the box.",
       "I can throw the ball.", "We can skip together.", "They can jump high."],
      [g("I can ___ the ball.", ["throw", "throws"], "throw", "⚾"),
       g("She can ___ around.", ["spin", "spins"], "spin", "🌀"),
       g("He can ___ the box.", ["lift", "lifts"], "lift", "🏋️"),
       g("We ___ skip.", ["can", "cans"], "can", "🏃‍♀️")],
      [t("can + run ->", "run", ["run", "runs", "running"], "run"),
       t("can + throw ->", "throw", ["throw", "throws", "throwing"], "throw"),
       t("can + spin ->", "spin", ["spin", "spins", "spinning"], "spin")],
      [f("I can run and jump.", "I can run and jumps.", "🤸"),
       f("She can spin around.", "She can spins around.", "🌀"),
       f("He can lift the box.", "He can lifts the box.", "🏋️"),
       f("They can jump high.", "They can jumps high.", "🤸")],
      srt("I can", "I can't",
          [tok("run", "A", "🏃"), tok("jump", "A", "🤸"), tok("skip", "A", "🏃‍♀️"),
           tok("fly", "B", "🕊️"), tok("purr", "B", "🐱"), tok("roar", "B", "🦁")]),
      [qa("What can you do?", "I can run and jump."),
       qa("Can you throw the ball?", "Yes, I can."),
       qa("Can he lift the box?", "Yes, he can."),
       qa("Can you spin around?", "Yes, I can spin.")]),

    # -- Level 6 -----------------------------------------------------------
    L("Animal Powers",
      [("swim", "🏊"), ("fly", "🕊️"), ("jump", "🐸"), ("climb", "🧗"), ("run", "🐆"), ("roar", "🦁")],
      "Animals can + verb",
      ["A bird can fly.", "A fish can swim.", "A frog can jump.",
       "A monkey can climb.", "A lion can roar.", "A dog can run."],
      [g("A bird can ___ .", ["fly", "flies"], "fly", "🕊️"),
       g("A fish can ___ .", ["swim", "swims"], "swim", "🐟"),
       g("A frog can ___ .", ["jump", "jumps"], "jump", "🐸"),
       g("A lion can ___ .", ["roar", "roars"], "roar", "🦁")],
      [t("can + fly ->", "fly", ["fly", "flies", "flying"], "fly"),
       t("can + climb ->", "climb", ["climb", "climbs", "climbing"], "climb"),
       t("can + roar ->", "roar", ["roar", "roars", "roaring"], "roar")],
      [f("A bird can fly.", "A bird can flies.", "🕊️"),
       f("A fish can swim.", "A fish can swims.", "🐟"),
       f("A monkey can climb.", "A monkey can climbs.", "🧗"),
       f("A lion can roar.", "A lion can roars.", "🦁")],
      srt("can fly", "can't fly",
          [tok("a bird", "A", "🕊️"), tok("a bee", "A", "🐝"), tok("a bat", "A", "🦇"),
           tok("a fish", "B", "🐟"), tok("a dog", "B", "🐕"), tok("a cat", "B", "🐈")]),
      [qa("Can a bird fly?", "Yes, it can."),
       qa("Can a fish swim?", "Yes, it can swim."),
       qa("Can a dog fly?", "No, it can't."),
       qa("What can a lion do?", "It can roar.")]),

    # -- Level 7 -----------------------------------------------------------
    L("Can or Can't?",
      [("sing", "🎤"), ("dance", "💃"), ("jump", "🤸"), ("run", "🏃"), ("swim", "🏊"), ("read", "📖")],
      "can vs can't",
      ["I can sing.", "I can't dance.", "She can swim.",
       "He can't run fast.", "They can read.", "We can't jump high."],
      [g("She can ___ well.", ["swim", "swims"], "swim", "🏊"),
       g("I can ___ a book.", ["read", "reads"], "read", "📖"),
       g("Fish ___ walk.", ["can't", "can"], "can't", "🐟"),
       g("Birds ___ fly.", ["can", "can't"], "can", "🕊️")],
      [t("can + sing ->", "sing", ["sing", "sings", "singing"], "sing"),
       t("can't + dance ->", "dance", ["dance", "dances", "dancing"], "dance"),
       t("can + read ->", "read", ["read", "reads", "reading"], "read")],
      [f("I can't dance.", "I can't dances.", "💃"),
       f("She can swim.", "She can swims.", "🏊"),
       f("He can't run fast.", "He can't runs fast.", "🏃"),
       f("They can read.", "They can reads.", "📖")],
      srt("can", "can't",
          [tok("I can sing", "A", "🎤"), tok("She can swim", "A", "🏊"), tok("They can read", "A", "📖"),
           tok("I can't dance", "B", "💃"), tok("He can't run", "B", "🏃"), tok("We can't jump", "B", "🤸")]),
      [qa("Can you sing?", "Yes, I can."),
       qa("Can you dance?", "No, I can't."),
       qa("Can she swim?", "Yes, she can."),
       qa("Can he run fast?", "No, he can't.")]),

    # -- Level 8 -----------------------------------------------------------
    L("New Spell",
      [("cast", "🪄"), ("wave", "👋"), ("point", "👉"), ("draw", "✏️"), ("sing", "🎤"), ("jump", "🤸")],
      "What can you do?",
      ["I can cast a spell.", "I can wave my wand.", "I can draw a star.",
       "What can you do?", "I can sing and jump.", "I can point at it."],
      [g("What ___ you do?", ["can", "cans"], "can", "🪄"),
       g("I can ___ a spell.", ["cast", "casts"], "cast", "🪄"),
       g("I can ___ my wand.", ["wave", "waves"], "wave", "👋"),
       g("What can you ___?", ["do", "does"], "do", "❓")],
      [t("can + cast ->", "cast", ["cast", "casts", "casting"], "cast"),
       t("can + wave ->", "wave", ["wave", "waves", "waving"], "wave"),
       t("can + draw ->", "draw", ["draw", "draws", "drawing"], "draw")],
      [f("I can cast a spell.", "I can casts a spell.", "🪄"),
       f("What can you do?", "What can you does?", "❓"),
       f("I can wave my wand.", "I can waves my wand.", "👋"),
       f("I can draw a star.", "I can draws a star.", "✏️")],
      srt("question", "answer",
          [tok("What can you do?", "A", "❓"), tok("Can you sing?", "A", "🎤"), tok("Can you jump?", "A", "🤸"),
           tok("I can cast a spell.", "B", "🪄"), tok("Yes, I can.", "B", "👍"), tok("I can draw.", "B", "✏️")]),
      [qa("What can you do?", "I can cast a spell."),
       qa("Can you wave your wand?", "Yes, I can."),
       qa("What can you draw?", "I can draw a star."),
       qa("Can you sing and jump?", "Yes, I can do both.")]),

    # -- Level 9 -----------------------------------------------------------
    L("Sound Lab: ur/or/ir",
      [("bird", "🐦"), ("girl", "👧"), ("turn", "🔄"), ("fork", "🍴"), ("corn", "🌽"), ("third", "🥉")],
      "reading sounds: ur / ir / or",
      ["The bird can fly.", "The girl can sing.", "Please turn left.",
       "I use a fork.", "I like corn.", "She is third."],
      [g("The ___ can fly.", ["bird", "girl"], "bird", "🐦"),
       g("I eat with a ___.", ["fork", "corn"], "fork", "🍴"),
       g("The ___ can sing.", ["girl", "fork"], "girl", "👧"),
       g("Please ___ the key.", ["turn", "corn"], "turn", "🔄")],
      [t("one bird -> many...?", "bird", ["birds", "birdes", "bird"], "birds"),
       t("one girl -> many...?", "girl", ["girls", "girles", "girl"], "girls"),
       t("one fork -> many...?", "fork", ["forks", "forkes", "fork"], "forks")],
      [f("The bird can fly.", "The bird can flies.", "🐦"),
       f("The girl can sing.", "The girl can sings.", "👧"),
       f("I use a fork.", "I use an fork.", "🍴"),
       f("She is third.", "She are third.", "🥉")],
      srt("ur / ir sound", "or sound",
          [tok("bird", "A", "🐦"), tok("girl", "A", "👧"), tok("turn", "A", "🔄"),
           tok("fork", "B", "🍴"), tok("corn", "B", "🌽"), tok("horn", "B", "📯")]),
      [qa("Can the bird fly?", "Yes, it can."),
       qa("What can the girl do?", "She can sing."),
       qa("What do you eat with?", "A fork."),
       qa("Do you like corn?", "Yes, I do.")]),

    # -- Level 10 ----------------------------------------------------------
    L("Activity Champion",
      [("swim", "🏊"), ("jump", "🤸"), ("fly", "🕊️"), ("sing", "🎤"), ("run", "🏃"), ("read", "📖")],
      "Unit 3 review: can / can't",
      ["I can swim.", "I can't fly.", "Can you sing?",
       "She can run fast.", "He can't jump high.", "A bird can fly."],
      [g("I ___ fly. (not able)", ["can't", "can"], "can't", "🕊️"),
       g("She can ___ fast.", ["run", "runs"], "run", "🏃"),
       g("___ you swim?", ["Can", "Do"], "Can", "🏊"),
       g("A bird ___ fly.", ["can", "can't"], "can", "🕊️")],
      [t("can + swim ->", "swim", ["swim", "swims", "swimming"], "swim"),
       t("can + sing ->", "sing", ["sing", "sings", "singing"], "sing"),
       t("can + read ->", "read", ["read", "reads", "reading"], "read")],
      [f("She can run fast.", "She can runs fast.", "🏃"),
       f("I can't fly.", "I can't flies.", "🕊️"),
       f("Can you sing?", "Can you sings?", "🎤"),
       f("A bird can fly.", "A bird can flies.", "🕊️")],
      srt("can", "can't",
          [tok("I can swim", "A", "🏊"), tok("She can run", "A", "🏃"), tok("A bird can fly", "A", "🕊️"),
           tok("I can't fly", "B", "🕊️"), tok("He can't jump", "B", "🤸"), tok("Fish can't walk", "B", "🐟")]),
      [qa("Can you swim?", "Yes, I can."),
       qa("Can you fly?", "No, I can't."),
       qa("What can she do?", "She can run fast."),
       qa("Can a bird fly?", "Yes, it can.")]),
])
