# -*- coding: utf-8 -*-
from grammar_helpers import g, t, f, tok, srt, qa, L, W

WORLD = W("My Things, Your Things", "Have got & possessives — Magic Academy Unit 4", [

    # ---------------------------------------------------------------- 1
    L("Astro Gets Wings",
      [("kite", "🪁"), ("ball", "⚽"), ("bike", "🚲"), ("doll", "🪆"), ("robot", "🤖"), ("puzzle", "🧩")],
      "I / You have got",
      ["I have got a kite.", "You have got a ball.", "I have got a bike.",
       "You have got a robot.", "I have got a doll."],
      [g("I ___ got a kite.", ["have", "has"], "have", "🪁"),
       g("You ___ got a ball.", ["have", "has"], "have", "⚽"),
       g("I ___ got a bike.", ["have", "has"], "have", "🚲"),
       g("I have got ___ robot.", ["a", "an"], "a", "🤖")],
      [t("one kite -> many...?", "kite", ["kites", "kite", "kytes"], "kites"),
       t("one ball -> many...?", "ball", ["balls", "ball", "balles"], "balls"),
       t("one robot -> many...?", "robot", ["robots", "robot", "robotes"], "robots")],
      [f("I have got a kite.", "I has got a kite.", "🪁"),
       f("You have got a ball.", "You has got a ball.", "⚽"),
       f("I have got a bike.", "I have got a bikes.", "🚲")],
      srt("have", "has",
          [tok("I", "A", "🙂"), tok("you", "A", "👉"), tok("we", "A", "👥"),
           tok("he", "B", "👦"), tok("she", "B", "👧"), tok("it", "B", "🤖")]),
      [qa("Have you got a kite?", "Yes, I have got a kite."),
       qa("What have you got?", "I have got a ball."),
       qa("Have you got a bike?", "Yes, I have."),
       qa("Have you got a robot?", "No, I have got a doll.")]),

    # ---------------------------------------------------------------- 2
    L("Chewing Gum",
      [("kite", "🪁"), ("ball", "⚽"), ("bike", "🚲"), ("doll", "🪆"), ("robot", "🤖"), ("guitar", "🎸")],
      "He / She has got",
      ["She has got a doll.", "He has got a robot.", "She has got a kite.",
       "He has got a guitar.", "She has got a ball."],
      [g("She ___ got a doll.", ["has", "have"], "has", "🪆"),
       g("He ___ got a robot.", ["has", "have"], "has", "🤖"),
       g("She ___ got a bike.", ["has", "have"], "has", "🚲"),
       g("He has got ___ guitar.", ["a", "an"], "a", "🎸")],
      [t("he + have ->", "have", ["have", "has", "haves"], "has"),
       t("she + have ->", "have", ["haves", "has", "have"], "has"),
       t("one doll -> many...?", "doll", ["dolls", "doll", "dolles"], "dolls")],
      [f("She has got a doll.", "She have got a doll.", "🪆"),
       f("He has got a robot.", "He have got a robot.", "🤖"),
       f("She has got a kite.", "She has got a kites.", "🪁")],
      srt("have got", "has got",
          [tok("I", "A", "🙂"), tok("you", "A", "👉"), tok("they", "A", "👫"),
           tok("he", "B", "👦"), tok("she", "B", "👧"), tok("it", "B", "🐱")]),
      [qa("Has she got a doll?", "Yes, she has."),
       qa("What has he got?", "He has got a guitar."),
       qa("Has he got a ball?", "No, he has got a bike."),
       qa("Has she got a robot?", "Yes, she has got a robot.")]),

    # ---------------------------------------------------------------- 3
    L("Nothing Left",
      [("guitar", "🎸"), ("piano", "🎹"), ("drum", "🥁"), ("violin", "🎻"), ("ball", "⚽"), ("kite", "🪁")],
      "haven't / hasn't got",
      ["I haven't got a piano.", "She hasn't got a drum.", "He hasn't got a bike.",
       "We haven't got a violin.", "He hasn't got a guitar."],
      [g("I ___ got a piano.", ["haven't", "hasn't"], "haven't", "🎹"),
       g("She ___ got a drum.", ["hasn't", "haven't"], "hasn't", "🥁"),
       g("He ___ got a bike.", ["hasn't", "haven't"], "hasn't", "🚲"),
       g("We ___ got a violin.", ["haven't", "hasn't"], "haven't", "🎻")],
      [t("has not ->", "has not", ["hasn't", "hasnt", "havn't"], "hasn't"),
       t("have not ->", "have not", ["haven't", "havent", "hasnt"], "haven't"),
       t("one drum -> many...?", "drum", ["drums", "drum", "drumes"], "drums")],
      [f("She hasn't got a drum.", "She haven't got a drum.", "🥁"),
       f("I haven't got a piano.", "I hasn't got a piano.", "🎹"),
       f("He hasn't got a ball.", "He haven't got a ball.", "⚽")],
      srt("haven't got", "hasn't got",
          [tok("I", "A", "🙂"), tok("you", "A", "👉"), tok("we", "A", "👥"),
           tok("he", "B", "👦"), tok("she", "B", "👧"), tok("it", "B", "🐱")]),
      [qa("Have you got a piano?", "No, I haven't."),
       qa("Has she got a drum?", "No, she hasn't."),
       qa("Has he got a violin?", "No, he hasn't got a violin."),
       qa("Have they got a guitar?", "No, they haven't.")]),

    # ---------------------------------------------------------------- 4
    L("Have you got?",
      [("ball", "⚽"), ("kite", "🪁"), ("bike", "🚲"), ("doll", "🪆"), ("robot", "🤖"), ("guitar", "🎸")],
      "Have you got ...?",
      ["Have you got a ball?", "Yes, I have.", "Has she got a doll?",
       "No, she hasn't.", "Have they got a kite?"],
      [g("___ you got a ball?", ["Have", "Has"], "Have", "⚽"),
       g("___ she got a doll?", ["Has", "Have"], "Has", "🪆"),
       g("Have you got ___ robot?", ["a", "an"], "a", "🤖"),
       g("___ he got a bike?", ["Has", "Have"], "Has", "🚲")],
      [t("you ... got? ->", "have", ["Have", "Has", "Hav"], "Have"),
       t("she ... got? ->", "has", ["Has", "Have", "Hass"], "Has"),
       t("they ... got? ->", "have", ["Have", "Has", "Haves"], "Have")],
      [f("Have you got a ball?", "Has you got a ball?", "⚽"),
       f("Has she got a doll?", "Have she got a doll?", "🪆"),
       f("Has he got a bike?", "Have he got a bike?", "🚲")],
      srt("Have", "Has",
          [tok("you", "A", "👉"), tok("we", "A", "👥"), tok("they", "A", "👫"),
           tok("he", "B", "👦"), tok("she", "B", "👧"), tok("it", "B", "🤖")]),
      [qa("Have you got a ball?", "Yes, I have."),
       qa("Has she got a doll?", "No, she hasn't."),
       qa("Have they got a kite?", "Yes, they have."),
       qa("Has he got a bike?", "No, he hasn't.")]),

    # ---------------------------------------------------------------- 5
    L("Whose is it?",
      [("robot", "🤖"), ("ball", "⚽"), ("bike", "🚲"), ("doll", "🪆"), ("kite", "🪁"), ("puzzle", "🧩")],
      "my / your / his / her",
      ["This is my robot.", "That is your ball.", "This is his bike.",
       "This is her doll.", "That is my kite."],
      [g("This is ___ robot.", ["my", "I"], "my", "🤖"),
       g("This is ___ doll.", ["her", "she"], "her", "🪆"),
       g("This is ___ bike.", ["his", "he"], "his", "🚲"),
       g("That is ___ ball.", ["your", "you"], "your", "⚽")],
      [t("I ->", "I", ["my", "mine", "me"], "my"),
       t("he ->", "he", ["his", "he's", "him"], "his"),
       t("she ->", "she", ["her", "hers", "she's"], "her")],
      [f("This is her doll.", "This is she doll.", "🪆"),
       f("This is his bike.", "This is he bike.", "🚲"),
       f("This is my robot.", "This is me robot.", "🤖")],
      srt("his", "her",
          [tok("he", "A", "👦"), tok("Tom", "A", "🧒"), tok("dad", "A", "👨"),
           tok("she", "B", "👧"), tok("Anna", "B", "👩"), tok("mom", "B", "🧑")]),
      [qa("Whose robot is this?", "It is my robot."),
       qa("Is this your ball?", "Yes, it is my ball."),
       qa("Whose doll is that?", "It is her doll."),
       qa("Whose bike is this?", "It is his bike.")]),

    # ---------------------------------------------------------------- 6
    L("Astro's Ball",
      [("ball", "⚽"), ("bike", "🚲"), ("doll", "🪆"), ("robot", "🤖"), ("guitar", "🎸"), ("puzzle", "🧩")],
      "possessive 's",
      ["This is Astro's ball.", "That is the girl's doll.", "This is the boy's bike.",
       "Here is Astro's guitar.", "This is dad's robot."],
      [g("This is ___ ball.", ["Astro's", "Astros"], "Astro's", "⚽"),
       g("That is the ___ doll.", ["girl's", "girls"], "girl's", "🪆"),
       g("This is the ___ bike.", ["boy's", "boys"], "boy's", "🚲"),
       g("Here is ___ guitar.", ["Astro's", "Astro"], "Astro's", "🎸")],
      [t("Astro + ball ->", "Astro", ["Astro's", "Astros", "Astroes"], "Astro's"),
       t("the girl + doll ->", "girl", ["girl's", "girls", "girles"], "girl's"),
       t("the boy + bike ->", "boy", ["boy's", "boys", "boyes"], "boy's")],
      [f("This is Astro's ball.", "This is Astros ball.", "⚽"),
       f("That is the girl's doll.", "That is the girls doll.", "🪆"),
       f("This is the boy's bike.", "This is the boys bike.", "🚲")],
      srt("owns it", "more than one",
          [tok("Astro's ball", "A", "⚽"), tok("the girl's doll", "A", "🪆"), tok("the boy's bike", "A", "🚲"),
           tok("two balls", "B", "⚽"), tok("three dolls", "B", "🪆"), tok("many bikes", "B", "🚲")]),
      [qa("Whose ball is this?", "It is Astro's ball."),
       qa("Whose doll is that?", "It is the girl's doll."),
       qa("Whose bike is this?", "It is the boy's bike."),
       qa("Whose guitar is this?", "It is Astro's guitar.")]),

    # ---------------------------------------------------------------- 7
    L("Mine & Yours",
      [("guitar", "🎸"), ("book", "📕"), ("pen", "🖊️"), ("ball", "⚽"), ("kite", "🪁"), ("doll", "🪆")],
      "mine / yours / his / hers",
      ["The kite is mine.", "Is this yours?", "The book is his.",
       "The pen is hers.", "This ball is mine."],
      [g("The kite is ___.", ["mine", "my"], "mine", "🪁"),
       g("Is this ___?", ["yours", "your"], "yours", "❓"),
       g("The book is ___.", ["his", "he's"], "his", "📕"),
       g("The pen is ___.", ["hers", "her's"], "hers", "🖊️")],
      [t("my ->", "my", ["mine", "mines", "my's"], "mine"),
       t("your ->", "your", ["yours", "your's", "yous"], "yours"),
       t("her ->", "her", ["hers", "her's", "heres"], "hers")],
      [f("The kite is mine.", "The kite is my.", "🪁"),
       f("The pen is hers.", "The pen is her.", "🖊️"),
       f("The book is his.", "The book is him.", "📕")],
      srt("before a noun", "stands alone",
          [tok("my", "A", "🙂"), tok("your", "A", "👉"), tok("her", "A", "👧"),
           tok("mine", "B", "🪁"), tok("yours", "B", "❓"), tok("hers", "B", "🖊️")]),
      [qa("Is this kite yours?", "Yes, it is mine."),
       qa("Is this your book?", "No, it is his."),
       qa("Whose pen is this?", "It is hers."),
       qa("Is this ball mine?", "Yes, it is yours.")]),

    # ---------------------------------------------------------------- 8
    L("Toy Box",
      [("robot", "🤖"), ("ball", "⚽"), ("bike", "🚲"), ("doll", "🪆"), ("guitar", "🎸"), ("puzzle", "🧩")],
      "have got + toys",
      ["I have got a robot.", "She has got a doll.", "We have got a puzzle.",
       "He has got a guitar.", "They have got a bike."],
      [g("I ___ got a robot.", ["have", "has"], "have", "🤖"),
       g("She ___ got a doll.", ["has", "have"], "has", "🪆"),
       g("They ___ got a puzzle.", ["have", "has"], "have", "🧩"),
       g("He ___ got a guitar.", ["has", "have"], "has", "🎸")],
      [t("one robot -> many...?", "robot", ["robots", "robot", "robotes"], "robots"),
       t("one ball -> many...?", "ball", ["balls", "ball", "balles"], "balls"),
       t("one puzzle -> many...?", "puzzle", ["puzzles", "puzzle", "puzzels"], "puzzles")],
      [f("I have got a robot.", "I has got a robot.", "🤖"),
       f("She has got a doll.", "She have got a doll.", "🪆"),
       f("They have got a bike.", "They has got a bike.", "🚲")],
      srt("have", "has",
          [tok("I", "A", "🙂"), tok("we", "A", "👥"), tok("they", "A", "👫"),
           tok("he", "B", "👦"), tok("she", "B", "👧"), tok("it", "B", "🤖")]),
      [qa("What have you got?", "I have got a robot."),
       qa("Has she got a doll?", "Yes, she has."),
       qa("Have they got a bike?", "Yes, they have."),
       qa("What has he got?", "He has got a guitar.")]),

    # ---------------------------------------------------------------- 9
    L("Sound Review",
      [("chair", "🪑"), ("table", "🍽️"), ("lamp", "💡"), ("book", "📕"), ("clock", "🕐"), ("phone", "📱")],
      "reading sounds",
      ["This is a chair.", "I have got a lamp.", "The book is on the table.",
       "This is my clock.", "The phone is black."],
      [g("This is ___ chair.", ["a", "an"], "a", "🪑"),
       g("I have got ___ lamp.", ["a", "an"], "a", "💡"),
       g("This is a ___.", ["clock", "clok"], "clock", "🕐"),
       g("This is a ___.", ["phone", "fone"], "phone", "📱")],
      [t("one book -> many...?", "book", ["books", "book", "bookes"], "books"),
       t("one clock -> many...?", "clock", ["clocks", "clock", "clockes"], "clocks"),
       t("one chair -> many...?", "chair", ["chairs", "chair", "chaires"], "chairs")],
      [f("This is a lamp.", "This is a lam.", "💡"),
       f("This is a clock.", "This is a clok.", "🕐"),
       f("This is a phone.", "This is a fone.", "📱")],
      srt("short vowel", "long vowel",
          [tok("lamp", "A", "💡"), tok("clock", "A", "🕐"), tok("book", "A", "📕"),
           tok("table", "B", "🍽️"), tok("phone", "B", "📱"), tok("chair", "B", "🪑")]),
      [qa("What is this?", "It is a chair."),
       qa("Is this a lamp?", "Yes, it is."),
       qa("Is this a book?", "No, it is a clock."),
       qa("What have you got?", "I have got a phone.")]),

    # ---------------------------------------------------------------- 10
    L("Things Champion",
      [("robot", "🤖"), ("doll", "🪆"), ("guitar", "🎸"), ("ball", "⚽"), ("kite", "🪁"), ("bike", "🚲")],
      "Unit 4 review",
      ["I have got a robot.", "She hasn't got a doll.", "Have you got a ball?",
       "This is Astro's guitar.", "The kite is mine.", "That is her bike."],
      [g("She ___ got a doll.", ["has", "have"], "has", "🪆"),
       g("___ you got a ball?", ["Have", "Has"], "Have", "⚽"),
       g("This is ___ guitar.", ["Astro's", "Astros"], "Astro's", "🎸"),
       g("The kite is ___.", ["mine", "my"], "mine", "🪁")],
      [t("he + have ->", "have", ["has", "have", "haves"], "has"),
       t("Astro + ball ->", "Astro", ["Astro's", "Astros", "Astroes"], "Astro's"),
       t("my ->", "my", ["mine", "mines", "my's"], "mine")],
      [f("He has got a robot.", "He have got a robot.", "🤖"),
       f("She hasn't got a doll.", "She haven't got a doll.", "🪆"),
       f("This is Astro's ball.", "This is Astros ball.", "⚽")],
      srt("have got", "has got",
          [tok("I", "A", "🙂"), tok("you", "A", "👉"), tok("we", "A", "👥"),
           tok("he", "B", "👦"), tok("she", "B", "👧"), tok("it", "B", "🤖")]),
      [qa("Have you got a robot?", "Yes, I have."),
       qa("Has she got a doll?", "No, she hasn't."),
       qa("Whose guitar is this?", "It is Astro's guitar."),
       qa("Is this kite yours?", "Yes, it is mine.")]),
])
