# -*- coding: utf-8 -*-
from grammar_helpers import g, t, f, tok, srt, qa, L, W

# ===========================================================================
# WORLD 5 — Unit 5 · Food I Like  (Present simple: like / likes)
# Grammar arc: I like -> Do you like? -> he/she likes -> doesn't like ->
# Does he like? -> object pronouns -> mixed -> like vs likes -> end blends ->
# full review.  Core rule: I/you/we/they LIKE ; he/she/it LIKES.
# Negative: don't like / doesn't like (base verb after don't/doesn't).
# Questions: Do you like...? / Does he like...? (base verb after do/does).
# ===========================================================================
WORLD = W("Food I Like", "Present simple like/likes — Magic Academy Unit 5", [

    L("A Yummy Mystery",
      [("pizza", "🍕"), ("apple", "🍎"), ("rice", "🍚"), ("fish", "🐟"), ("cheese", "🧀"), ("cake", "🍰")],
      "I like / I don't like",
      ["I like pizza.", "I like apples.", "I don't like soup.",
       "I like cheese.", "I like cake.", "I don't like fish."],
      [g("I ___ pizza.", ["like", "likes"], "like", "🍕"),
       g("I ___ like fish.", ["don't", "doesn't"], "don't", "🐟"),
       g("I ___ cheese.", ["like", "likes"], "like", "🧀"),
       g("I ___ like rice.", ["don't", "doesn't"], "don't", "🍚")],
      [t("I + like ->", "like", ["like", "likes", "liked"], "like"),
       t("I + eat ->", "eat", ["eat", "eats", "ate"], "eat"),
       t("I + want ->", "want", ["want", "wants", "wanted"], "want")],
      [f("I like pizza.", "I likes pizza.", "🍕"),
       f("I don't like soup.", "I doesn't like soup.", "🍲"),
       f("I like cheese.", "I likes cheese.", "🧀")],
      srt("like", "likes",
          [tok("I", "A", "🙋"), tok("you", "A", "👉"), tok("we", "A", "👫"),
           tok("he", "B", "👦"), tok("she", "B", "👧"), tok("it", "B", "🐱")]),
      [qa("What do you like?", "I like pizza."),
       qa("Do you like fish?", "No, I don't."),
       qa("Do you like cake?", "Yes, I do."),
       qa("What don't you like?", "I don't like soup.")]),

    L("Do you like it?",
      [("burger", "🍔"), ("salad", "🥗"), ("pasta", "🍝"), ("soup", "🥣"), ("fish", "🐟"), ("cake", "🍰")],
      "Do you like...?",
      ["Do you like pasta?", "Yes, I do.", "Do you like fish?",
       "No, I don't.", "Do you like cake?", "I like salad."],
      [g("___ you like soup?", ["Do", "Does"], "Do", "🥣"),
       g("Do you ___ cake?", ["like", "likes"], "like", "🍰"),
       g("___ you like fish?", ["Do", "Does"], "Do", "🐟"),
       g("No, I ___.", ["don't", "doesn't"], "don't", "")],
      [t("Do you + like ->", "like", ["like", "likes", "liking"], "like"),
       t("Do you + want ->", "want", ["want", "wants", "wanting"], "want"),
       t("Do you + eat ->", "eat", ["eat", "eats", "eating"], "eat")],
      [f("Do you like pasta?", "Do you likes pasta?", "🍝"),
       f("Do you like soup?", "Does you like soup?", "🥣"),
       f("No, I don't.", "No, I doesn't.", "")],
      srt("Do", "Does",
          [tok("I", "A", "🙋"), tok("you", "A", "👉"), tok("we", "A", "👫"),
           tok("he", "B", "👦"), tok("she", "B", "👧"), tok("it", "B", "🐱")]),
      [qa("Do you like pasta?", "Yes, I do."),
       qa("Do you like soup?", "No, I don't."),
       qa("Do you like fish or cake?", "I like cake."),
       qa("What do you like?", "I like salad.")]),

    L("Mr Gluto Returns",
      [("banana", "🍌"), ("cake", "🍰"), ("toast", "🍞"), ("milk", "🥛"), ("rice", "🍚"), ("fish", "🐟")],
      "He / She likes",
      ["She likes cake.", "He likes milk.", "She likes rice.",
       "He likes fish.", "She likes toast.", "He likes bananas."],
      [g("She ___ cake.", ["likes", "like"], "likes", "🍰"),
       g("He ___ milk.", ["likes", "like"], "likes", "🥛"),
       g("She ___ rice.", ["likes", "like"], "likes", "🍚"),
       g("He ___ toast.", ["likes", "like"], "likes", "🍞")],
      [t("she + like ->", "like", ["likes", "like", "liking"], "likes"),
       t("he + eat ->", "eat", ["eats", "eat", "eates"], "eats"),
       t("she + want ->", "want", ["wants", "want", "wantes"], "wants")],
      [f("She likes cake.", "She like cake.", "🍰"),
       f("He likes fish.", "He like fish.", "🐟"),
       f("She likes rice.", "She like rice.", "🍚")],
      srt("like", "likes",
          [tok("I", "A", "🙋"), tok("you", "A", "👉"), tok("the kids", "A", "🧒"),
           tok("she", "B", "👧"), tok("Tom", "B", "👦"), tok("my dog", "B", "🐶")]),
      [qa("What does she like?", "She likes cake."),
       qa("What does he like?", "He likes fish."),
       qa("Does she like milk?", "Yes, she does."),
       qa("Does he like rice?", "No, he doesn't.")]),

    L("Nice Mr Gluto",
      [("sandwich", "🥪"), ("fries", "🍟"), ("pizza", "🍕"), ("cake", "🍰"), ("apple", "🍎"), ("juice", "🧃")],
      "He / She doesn't like",
      ["He doesn't like pizza.", "She doesn't like cake.", "He doesn't like juice.",
       "She doesn't like fries.", "He doesn't like apples."],
      [g("He ___ like pizza.", ["doesn't", "don't"], "doesn't", "🍕"),
       g("She ___ like cake.", ["doesn't", "don't"], "doesn't", "🍰"),
       g("He doesn't ___ juice.", ["like", "likes"], "like", "🧃"),
       g("She ___ like fries.", ["doesn't", "don't"], "doesn't", "🍟")],
      [t("doesn't + like ->", "like", ["like", "likes", "liked"], "like"),
       t("doesn't + eat ->", "eat", ["eat", "eats", "ate"], "eat"),
       t("doesn't + want ->", "want", ["want", "wants", "wanted"], "want")],
      [f("He doesn't like pizza.", "He doesn't likes pizza.", "🍕"),
       f("She doesn't like cake.", "She don't like cake.", "🍰"),
       f("He doesn't like juice.", "He doesn't likes juice.", "🧃")],
      srt("don't", "doesn't",
          [tok("I", "A", "🙋"), tok("you", "A", "👉"), tok("they", "A", "👬"),
           tok("he", "B", "👦"), tok("she", "B", "👧"), tok("it", "B", "🐱")]),
      [qa("Does he like juice?", "No, he doesn't."),
       qa("Does she like cake?", "No, she doesn't."),
       qa("What doesn't he like?", "He doesn't like pizza."),
       qa("What doesn't she like?", "She doesn't like fries.")]),

    L("Does he?",
      [("rice", "🍚"), ("milk", "🥛"), ("cake", "🍰"), ("soup", "🥣"), ("fish", "🐟"), ("salad", "🥗")],
      "Does he / she like...?",
      ["Does she like rice?", "Yes, she does.", "Does he like soup?",
       "No, he doesn't.", "Does she like cake?", "Does he like fish?"],
      [g("___ she like rice?", ["Does", "Do"], "Does", "🍚"),
       g("Does he ___ soup?", ["like", "likes"], "like", "🥣"),
       g("___ he like fish?", ["Does", "Do"], "Does", "🐟"),
       g("Does she ___ cake?", ["like", "likes"], "like", "🍰")],
      [t("Does she + like ->", "like", ["like", "likes", "liked"], "like"),
       t("Does he + eat ->", "eat", ["eat", "eats", "ate"], "eat"),
       t("Does she + want ->", "want", ["want", "wants", "wanted"], "want")],
      [f("Does she like rice?", "Does she likes rice?", "🍚"),
       f("Does he like soup?", "Do he like soup?", "🥣"),
       f("Does she like cake?", "Does she likes cake?", "🍰")],
      srt("Do", "Does",
          [tok("you", "A", "👉"), tok("they", "A", "👬"), tok("my friends", "A", "🧑‍🤝‍🧑"),
           tok("she", "B", "👧"), tok("Tom", "B", "👦"), tok("my mom", "B", "👩")]),
      [qa("Does she like rice?", "Yes, she does."),
       qa("Does he like soup?", "No, he doesn't."),
       qa("Does he like cake?", "Yes, he does."),
       qa("Does she like fish?", "No, she doesn't.")]),

    L("Me & Them",
      [("eggs", "🥚"), ("yogurt", "🍦"), ("fruit", "🍓"), ("cake", "🍰"), ("milk", "🥛"), ("soup", "🥣")],
      "Object pronouns: it / them / him / her",
      ["I like it.", "She likes them.", "He likes it.",
       "They like them.", "She likes me.", "I like him."],
      [g("I like ___.", ["it", "them"], "it", "🍰"),
       g("She likes ___.", ["them", "it"], "them", "🥚"),
       g("He likes ___.", ["it", "them"], "it", "🥛"),
       g("They like ___.", ["them", "it"], "them", "🥚")],
      [t("the cake ->", "cake", ["it", "them", "he"], "it"),
       t("the eggs ->", "eggs", ["them", "it", "they"], "them"),
       t("the milk ->", "milk", ["it", "them", "she"], "it")],
      [f("I like them.", "I like they.", "🥚"),
       f("He likes her.", "He likes she.", "👧"),
       f("I like him.", "I like he.", "👦")],
      srt("it", "them",
          [tok("cake", "A", "🍰"), tok("milk", "A", "🥛"), tok("soup", "A", "🥣"),
           tok("eggs", "B", "🥚"), tok("cookies", "B", "🍪"), tok("apples", "B", "🍎")]),
      [qa("Do you like cake?", "Yes, I like it."),
       qa("Do you like eggs?", "Yes, I like them."),
       qa("Does she like milk?", "Yes, she likes it."),
       qa("Does he like apples?", "No, he doesn't like them.")]),

    L("Food Court",
      [("sushi", "🍣"), ("tacos", "🌮"), ("donut", "🍩"), ("soup", "🥣"), ("stew", "🍲"), ("fruit", "🍓")],
      "like / likes",
      ["I like sushi.", "She likes tacos.", "He likes soup.",
       "We like fruit.", "They like donuts.", "She likes stew."],
      [g("I ___ sushi.", ["like", "likes"], "like", "🍣"),
       g("She ___ tacos.", ["likes", "like"], "likes", "🌮"),
       g("They ___ fruit.", ["like", "likes"], "like", "🍓"),
       g("He ___ soup.", ["likes", "like"], "likes", "🥣")],
      [t("he + like ->", "like", ["likes", "like", "liked"], "likes"),
       t("she + eat ->", "eat", ["eats", "eat", "eaten"], "eats"),
       t("it + want ->", "want", ["wants", "want", "wanted"], "wants")],
      [f("She likes tacos.", "She like tacos.", "🌮"),
       f("I like sushi.", "I likes sushi.", "🍣"),
       f("He likes soup.", "He like soup.", "🥣")],
      srt("like", "likes",
          [tok("I", "A", "🙋"), tok("we", "A", "👫"), tok("they", "A", "👬"),
           tok("he", "B", "👦"), tok("she", "B", "👧"), tok("the cat", "B", "🐱")]),
      [qa("Do you like sushi?", "Yes, I do."),
       qa("Does she like tacos?", "Yes, she does."),
       qa("What do they like?", "They like fruit."),
       qa("What does he like?", "He likes stew.")]),

    L("Ludo's Doubts",
      [("cookie", "🍪"), ("candy", "🍬"), ("fruit", "🍓"), ("milk", "🥛"), ("cake", "🍰"), ("fish", "🐟")],
      "like vs likes",
      ["She likes cake.", "I like cookies.", "He likes fish.",
       "We like candy.", "They like fruit.", "She likes milk."],
      [g("She ___ cake.", ["likes", "like"], "likes", "🍰"),
       g("I ___ cookies.", ["like", "likes"], "like", "🍪"),
       g("He ___ fish.", ["likes", "like"], "likes", "🐟"),
       g("We ___ candy.", ["like", "likes"], "like", "🍬")],
      [t("she + like ->", "like", ["likes", "like", "liking"], "likes"),
       t("we + like ->", "like", ["like", "likes", "liked"], "like"),
       t("he + like ->", "like", ["likes", "like", "liking"], "likes")],
      [f("She likes cake.", "She like cake.", "🍰"),
       f("I like cookies.", "I likes cookies.", "🍪"),
       f("He likes fish.", "He like fish.", "🐟"),
       f("They like candy.", "They likes candy.", "🍬")],
      srt("like", "likes",
          [tok("I", "A", "🙋"), tok("you", "A", "👉"), tok("they", "A", "👬"),
           tok("he", "B", "👦"), tok("she", "B", "👧"), tok("it", "B", "🐱")]),
      [qa("Does she like cake?", "Yes, she does."),
       qa("Do you like cookies?", "Yes, I do."),
       qa("What does he like?", "He likes fish."),
       qa("What do they like?", "They like fruit.")]),

    L("Sound Lab: st/nd/mp",
      [("nest", "🪹"), ("hand", "✋"), ("jump", "🦘"), ("lamp", "💡"), ("pond", "🏞️"), ("fast", "🏃")],
      "End blends: st, nd, mp",
      ["I see a nest.", "Give me your hand.", "The frog can jump.",
       "I turn on the lamp.", "Fish live in the pond.", "The car is fast."],
      [g("Hold my ___.", ["hand", "hant"], "hand", "✋"),
       g("Turn on the ___.", ["lamp", "lam"], "lamp", "💡"),
       g("A bird has a ___.", ["nest", "nes"], "nest", "🪹"),
       g("The car is ___.", ["fast", "fas"], "fast", "🏃")],
      [t("one nest -> many...?", "nest", ["nests", "nest", "nestes"], "nests"),
       t("one lamp -> many...?", "lamp", ["lamps", "lamp", "lampes"], "lamps"),
       t("one hand -> many...?", "hand", ["hands", "hand", "handes"], "hands")],
      [f("I see a nest.", "I see a nes.", "🪹"),
       f("Turn on the lamp.", "Turn on the lam.", "💡"),
       f("Give me your hand.", "Give me your hant.", "✋")],
      srt("st", "mp",
          [tok("nest", "A", "🪹"), tok("fast", "A", "🏃"), tok("best", "A", "👍"),
           tok("jump", "B", "🦘"), tok("lamp", "B", "💡"), tok("camp", "B", "⛺")]),
      [qa("What do you see?", "I see a nest."),
       qa("Where do frogs live?", "They live in the pond."),
       qa("Can you jump?", "Yes, I can."),
       qa("Is the car fast?", "Yes, it is.")]),

    L("Food Champion",
      [("pizza", "🍕"), ("cake", "🍰"), ("fish", "🐟"), ("milk", "🥛"), ("rice", "🍚"), ("fruit", "🍓")],
      "like, likes, don't, doesn't",
      ["I like pizza.", "She likes cake.", "He doesn't like milk.",
       "We don't like fish.", "Do you like rice?", "Does she like fruit?"],
      [g("She ___ cake.", ["likes", "like"], "likes", "🍰"),
       g("He ___ like milk.", ["doesn't", "don't"], "doesn't", "🥛"),
       g("___ you like rice?", ["Do", "Does"], "Do", "🍚"),
       g("___ she like fruit?", ["Does", "Do"], "Does", "🍓")],
      [t("she + like ->", "like", ["likes", "like", "liked"], "likes"),
       t("Does he + like ->", "like", ["like", "likes", "liked"], "like"),
       t("doesn't + like ->", "like", ["like", "likes", "liked"], "like")],
      [f("She likes cake.", "She like cake.", "🍰"),
       f("He doesn't like milk.", "He doesn't likes milk.", "🥛"),
       f("Do you like rice?", "Does you like rice?", "🍚"),
       f("I don't like fish.", "I doesn't like fish.", "🐟")],
      srt("like", "likes",
          [tok("I", "A", "🙋"), tok("you", "A", "👉"), tok("we", "A", "👫"),
           tok("he", "B", "👦"), tok("she", "B", "👧"), tok("it", "B", "🐱")]),
      [qa("Do you like pizza?", "Yes, I do."),
       qa("Does she like cake?", "Yes, she does."),
       qa("Does he like milk?", "No, he doesn't."),
       qa("What do you like?", "I like rice.")]),
])
