# -*- coding: utf-8 -*-
from grammar_helpers import g, t, f, tok, srt, qa, L, W

# ===========================================================================
# WORLD 6 — Unit 6 · My Daily Routine  (Levels 151-160)
# Grammar arc: present simple (I / you / he / she -s), telling time,
# negatives (don't / doesn't + base), questions (do / does), frequency
# adverbs (always / sometimes / never), reading blends br / cr / dr.
# ===========================================================================
WORLD = W("My Daily Routine", "Present simple & time — Magic Academy Unit 6", [

    L("Barsu Wakes Up",
      [("wash", "🧼"), ("eat", "🍽️"), ("play", "⚽"), ("sleep", "😴"), ("read", "📖"), ("walk", "🚶")],
      "Present simple: I ...",
      ["I wash my face.", "I eat breakfast.", "I read a book.",
       "I play with my friends.", "I walk to school."],
      [g("I ___ my face.", ["wash", "washes"], "wash", "🧼"),
       g("I ___ breakfast.", ["eat", "eats"], "eat", "🍽️"),
       g("I ___ a book.", ["read", "reads"], "read", "📖"),
       g("I ___ to school.", ["walk", "walks"], "walk", "🚶")],
      [t("I + wash ->", "wash", ["wash", "washes", "washs"], "wash"),
       t("I + eat ->", "eat", ["eats", "eat", "eates"], "eat"),
       t("I + read ->", "read", ["reads", "reades", "read"], "read")],
      [f("I wash my face.", "I washes my face.", "🧼"),
       f("I eat breakfast.", "I eats breakfast.", "🍽️"),
       f("I read a book.", "I reads a book.", "📖")],
      srt("morning", "night",
          [tok("wake up", "A", "🌅"), tok("eat breakfast", "A", "🍳"), tok("go to school", "A", "🏫"),
           tok("go to bed", "B", "🛏️"), tok("sleep", "B", "😴"), tok("say goodnight", "B", "🌙")]),
      [qa("What do you do in the morning?", "I wash my face."),
       qa("Do you eat breakfast?", "Yes, I do."),
       qa("What do you read?", "I read a book."),
       qa("How do you go to school?", "I walk to school.")]),

    L("My Day",
      [("wake", "⏰"), ("wash", "🧼"), ("eat", "🍽️"), ("go", "🚶"), ("read", "📖"), ("play", "⚽")],
      "Present simple: I / you",
      ["I get up at seven.", "You go to school.", "I eat my breakfast.",
       "You read every day.", "I play after school."],
      [g("You ___ to school.", ["go", "goes"], "go", "🏫"),
       g("I ___ up at seven.", ["get", "gets"], "get", "⏰"),
       g("You ___ every day.", ["read", "reads"], "read", "📖"),
       g("I ___ after school.", ["play", "plays"], "play", "⚽")],
      [t("you + go ->", "go", ["go", "goes", "gos"], "go"),
       t("I + wash ->", "wash", ["washes", "wash", "washs"], "wash"),
       t("you + play ->", "play", ["plays", "play", "playes"], "play")],
      [f("You go to school.", "You goes to school.", "🏫"),
       f("I get up early.", "I gets up early.", "⏰"),
       f("You read every day.", "You reads every day.", "📖")],
      srt("morning", "evening",
          [tok("wake up", "A", "⏰"), tok("wash my face", "A", "🧼"), tok("go to school", "A", "🏫"),
           tok("do homework", "B", "📚"), tok("eat dinner", "B", "🍽️"), tok("go to bed", "B", "🛏️")]),
      [qa("What time do you get up?", "I get up at seven."),
       qa("Do you go to school?", "Yes, I do."),
       qa("What do you do after school?", "I play with friends."),
       qa("Do you read every day?", "No, I don't.")]),

    L("Students Are Not OK",
      [("go", "🚶"), ("eat", "🍽️"), ("read", "📖"), ("play", "⚽"), ("sleep", "😴"), ("walk", "🚶")],
      "He / She + verb -s",
      ["She goes to school.", "He reads a book.", "She plays every day.",
       "He eats breakfast.", "She walks to school."],
      [g("She ___ to school.", ["goes", "go"], "goes", "🏫"),
       g("He ___ a book.", ["reads", "read"], "reads", "📖"),
       g("She ___ every day.", ["plays", "play"], "plays", "⚽"),
       g("He ___ breakfast.", ["eats", "eat"], "eats", "🍽️")],
      [t("she + go ->", "go", ["goes", "gos", "go"], "goes"),
       t("he + play ->", "play", ["plays", "playes", "play"], "plays"),
       t("she + read ->", "read", ["reads", "reades", "read"], "reads")],
      [f("She goes to school.", "She go to school.", "🏫"),
       f("He reads a book.", "He read a book.", "📖"),
       f("She plays every day.", "She play every day.", "⚽"),
       f("He eats breakfast.", "He eat breakfast.", "🍽️")],
      srt("no -s (I / you)", "add -s (he / she)",
          [tok("I go", "A", "🚶"), tok("you eat", "A", "🍽️"), tok("I play", "A", "⚽"),
           tok("he goes", "B", "🚶"), tok("she eats", "B", "🍽️"), tok("she plays", "B", "⚽")]),
      [qa("Where does she go?", "She goes to school."),
       qa("Does he read books?", "Yes, he does."),
       qa("What does she do every day?", "She plays outside."),
       qa("Does she walk to school?", "Yes, she does.")]),

    L("Ludo Has a Plan",
      [("clock", "🕐"), ("seven", "7️⃣"), ("eight", "8️⃣"), ("morning", "🌅"), ("night", "🌙"), ("noon", "☀️")],
      "Telling time: o'clock / half past",
      ["It is seven o'clock.", "It is half past eight.", "It is eight o'clock.",
       "I get up at seven.", "I go to bed at night."],
      [g("It's seven ___.", ["o'clock", "past"], "o'clock", "🕖"),
       g("It's ___ past eight.", ["half", "o'clock"], "half", "🕗"),
       g("It's ___ o'clock.", ["eight", "half"], "eight", "8️⃣"),
       g("It's half ___ eight.", ["past", "to"], "past", "🕗")],
      [t("7:00 ->", "seven", ["seven o'clock", "seven oclock", "seven a clock"], "seven o'clock"),
       t("8:00 ->", "eight", ["eight o'clock", "eight oclock", "eight aclock"], "eight o'clock"),
       t("8:30 ->", "eight", ["half past eight", "half to eight", "half past eights"], "half past eight")],
      [f("It is seven o'clock.", "It is seven o'clocks.", "🕖"),
       f("It is half past eight.", "It is half to eight.", "🕗"),
       f("It is eight o'clock.", "It is eights o'clock.", "8️⃣")],
      srt("o'clock", "half past",
          [tok("7:00", "A", "🕖"), tok("8:00", "A", "🕗"), tok("9:00", "A", "🕘"),
           tok("7:30", "B", "🕢"), tok("8:30", "B", "🕣"), tok("9:30", "B", "🕤")]),
      [qa("What time is it?", "It is seven o'clock."),
       qa("Is it eight o'clock?", "No, it is half past eight."),
       qa("What time do you get up?", "I get up at seven."),
       qa("When do you go to bed?", "I go to bed at night.")]),

    L("Not Every Day",
      [("cook", "🍳"), ("clean", "🧹"), ("shop", "🛒"), ("swim", "🏊"), ("run", "🏃"), ("sleep", "😴")],
      "Negative: don't / doesn't",
      ["I don't cook.", "He doesn't sleep at noon.", "She doesn't swim.",
       "We don't shop today.", "I don't run at night."],
      [g("I ___ cook.", ["don't", "doesn't"], "don't", "🍳"),
       g("He ___ swim.", ["doesn't", "don't"], "doesn't", "🏊"),
       g("She doesn't ___.", ["run", "runs"], "run", "🏃"),
       g("They ___ clean.", ["don't", "doesn't"], "don't", "🧹")],
      [t("I do not + cook ->", "cook", ["don't cook", "don't cooks", "doesn't cook"], "don't cook"),
       t("she does not + run ->", "run", ["doesn't run", "doesn't runs", "don't run"], "doesn't run"),
       t("he does not + sleep ->", "sleep", ["doesn't sleep", "doesn't sleeps", "don't sleep"], "doesn't sleep")],
      [f("I don't cook.", "I doesn't cook.", "🍳"),
       f("He doesn't swim.", "He doesn't swims.", "🏊"),
       f("She doesn't run.", "She don't run.", "🏃"),
       f("We don't shop today.", "We doesn't shop today.", "🛒")],
      srt("don't (I / you / we)", "doesn't (he / she)",
          [tok("I don't cook", "A", "🍳"), tok("you don't run", "A", "🏃"), tok("we don't shop", "A", "🛒"),
           tok("he doesn't swim", "B", "🏊"), tok("she doesn't clean", "B", "🧹"), tok("she doesn't cook", "B", "🍳")]),
      [qa("Do you cook?", "No, I don't."),
       qa("Does he swim?", "No, he doesn't."),
       qa("Does she run at night?", "No, she doesn't."),
       qa("Do they shop today?", "No, they don't.")]),

    L("When do you...?",
      [("eat", "🍽️"), ("go", "🚶"), ("play", "⚽"), ("read", "📖"), ("study", "📚"), ("wash", "🧼")],
      "Questions: Do you / What time do you",
      ["Do you eat breakfast?", "What time do you get up?", "Do you go to school?",
       "When do you play?", "What time does he sleep?"],
      [g("___ you eat breakfast?", ["Do", "Does"], "Do", "🍽️"),
       g("What time ___ she get up?", ["does", "do"], "does", "⏰"),
       g("Do you ___ to school?", ["go", "goes"], "go", "🏫"),
       g("Does he ___ books?", ["read", "reads"], "read", "📖")],
      [t("you / eat ->", "eat", ["Do you eat?", "Do you eats?", "Does you eat?"], "Do you eat?"),
       t("he / play ->", "play", ["Does he play?", "Does he plays?", "Do he play?"], "Does he play?"),
       t("she / go ->", "go", ["Does she go?", "Does she goes?", "Do she go?"], "Does she go?")],
      [f("Do you eat breakfast?", "Does you eat breakfast?", "🍽️"),
       f("What time does he sleep?", "What time do he sleep?", "😴"),
       f("Does she read books?", "Does she reads books?", "📖")],
      srt("Do you...?", "Does he / she...?",
          [tok("Do you eat?", "A", "🍽️"), tok("Do you go?", "A", "🚶"), tok("Do you play?", "A", "⚽"),
           tok("Does he read?", "B", "📖"), tok("Does she go?", "B", "🚶"), tok("Does he study?", "B", "📚")]),
      [qa("What time do you get up?", "I get up at seven."),
       qa("Do you go to school?", "Yes, I do."),
       qa("When does she play?", "She plays after school."),
       qa("Does he read books?", "Yes, he does.")]),

    L("Always & Never",
      [("brush", "🪥"), ("wash", "🧼"), ("read", "📖"), ("sleep", "😴"), ("walk", "🚶"), ("help", "🤝")],
      "Always / sometimes / never",
      ["I always brush my teeth.", "She never eats candy.", "I sometimes read at night.",
       "He is never late.", "We never sleep late."],
      [g("I always ___ my teeth.", ["brush", "brushes"], "brush", "🪥"),
       g("She ___ eats candy.", ["never", "not"], "never", "🍬"),
       g("I ___ read at night.", ["sometimes", "sometime"], "sometimes", "📖"),
       g("He always ___ to school.", ["walks", "walk"], "walks", "🚶")],
      [t("she + never + eat ->", "eat", ["never eats", "eats never", "never eat"], "never eats"),
       t("I + always + brush ->", "brush", ["always brush", "brush always", "always brushes"], "always brush"),
       t("he + sometimes + walk ->", "walk", ["sometimes walks", "walks sometimes", "sometimes walk"], "sometimes walks")],
      [f("She never eats candy.", "She never eat candy.", "🍬"),
       f("I always brush my teeth.", "I always brushes my teeth.", "🪥"),
       f("He sometimes walks home.", "He sometimes walk home.", "🚶")],
      srt("a lot", "not much",
          [tok("always", "A", "✅"), tok("usually", "A", "👍"), tok("often", "A", "🔁"),
           tok("sometimes", "B", "🤷"), tok("rarely", "B", "🙁"), tok("never", "B", "❌")]),
      [qa("Do you brush your teeth?", "Yes, I always do."),
       qa("Does she eat candy?", "No, she never does."),
       qa("How often do you read?", "I sometimes read."),
       qa("Do you help at home?", "Yes, I always help.")]),

    L("Slime Portal",
      [("open", "🚪"), ("close", "🔒"), ("wait", "⏳"), ("read", "📖"), ("eat", "🍽️"), ("sleep", "😴")],
      "Routine + time",
      ["I read at night.", "The portal opens at noon.", "I eat lunch at noon.",
       "We wait for the portal.", "I sleep at night."],
      [g("I read a book ___ night.", ["at", "in"], "at", "🌙"),
       g("The portal opens ___ noon.", ["at", "in"], "at", "☀️"),
       g("I wake up ___ the morning.", ["in", "at"], "in", "🌅"),
       g("I sleep ___ night.", ["at", "on"], "at", "😴")],
      [t("he + open ->", "open", ["opens", "open", "openes"], "opens"),
       t("she + wait ->", "wait", ["waits", "wait", "waites"], "waits"),
       t("it + close ->", "close", ["closes", "close", "closs"], "closes")],
      [f("I read at night.", "I read on night.", "🌙"),
       f("The portal opens at noon.", "The portal open at noon.", "☀️"),
       f("I wake up in the morning.", "I wake up on the morning.", "🌅")],
      srt("at ...", "in ...",
          [tok("at noon", "A", "☀️"), tok("at night", "A", "🌙"), tok("at seven", "A", "🕖"),
           tok("in the morning", "B", "🌅"), tok("in the day", "B", "🌤️"), tok("in the evening", "B", "🌆")]),
      [qa("When do you read?", "I read at night."),
       qa("What time does the portal open?", "It opens at noon."),
       qa("Do you sleep at night?", "Yes, I do."),
       qa("When do you wake up?", "I wake up in the morning.")]),

    L("Sound Lab: br/cr/dr blends",
      [("brush", "🪥"), ("crab", "🦀"), ("drum", "🥁"), ("frog", "🐸"), ("green", "🟢"), ("grass", "🌱")],
      "Reading blends: br / cr / dr",
      ["I brush my teeth.", "The crab is red.", "I play the drum.",
       "The frog is green.", "The grass is green."],
      [g("I ___ my teeth.", ["brush", "crab"], "brush", "🪥"),
       g("The ___ is green.", ["frog", "drum"], "frog", "🐸"),
       g("I play the ___.", ["drum", "grass"], "drum", "🥁"),
       g("The ___ is red.", ["crab", "green"], "crab", "🦀")],
      [t("say: brush ->", "brush", ["brush", "bursh", "brsuh"], "brush"),
       t("say: drum ->", "drum", ["drum", "durm", "drumm"], "drum"),
       t("say: green ->", "green", ["green", "gren", "greeen"], "green")],
      [f("The frog is green.", "The frog is grean.", "🐸"),
       f("I play the drum.", "I play the durm.", "🥁"),
       f("The crab is red.", "The crob is red.", "🦀")],
      srt("br", "dr",
          [tok("brush", "A", "🪥"), tok("bread", "A", "🍞"), tok("brick", "A", "🧱"),
           tok("drum", "B", "🥁"), tok("dress", "B", "👗"), tok("drink", "B", "🥤")]),
      [qa("What is green?", "The frog is green."),
       qa("What do you play?", "I play the drum."),
       qa("What color is the grass?", "The grass is green."),
       qa("What is the first sound in 'drum'?", "The dr sound.")]),

    L("Routine Champion",
      [("wake", "⏰"), ("wash", "🧼"), ("eat", "🍽️"), ("read", "📖"), ("brush", "🪥"), ("sleep", "😴")],
      "Unit 6 review",
      ["I wake up at seven.", "She goes to school.", "He doesn't sleep at noon.",
       "I always brush my teeth.", "You read every day."],
      [g("She ___ to school.", ["goes", "go"], "goes", "🏫"),
       g("He ___ sleep at noon.", ["doesn't", "don't"], "doesn't", "😴"),
       g("I always ___ my teeth.", ["brush", "brushes"], "brush", "🪥"),
       g("___ you eat breakfast?", ["Do", "Does"], "Do", "🍽️")],
      [t("she + go ->", "go", ["goes", "gos", "go"], "goes"),
       t("he does not + sleep ->", "sleep", ["doesn't sleep", "doesn't sleeps", "don't sleep"], "doesn't sleep"),
       t("you / eat ->", "eat", ["Do you eat?", "Does you eat?", "Do you eats?"], "Do you eat?")],
      [f("She goes to school.", "She go to school.", "🏫"),
       f("He doesn't sleep at noon.", "He doesn't sleeps at noon.", "😴"),
       f("I always brush my teeth.", "I always brushes my teeth.", "🪥"),
       f("Do you eat breakfast?", "Does you eat breakfast?", "🍽️")],
      srt("no -s (I / you)", "add -s (he / she)",
          [tok("I wake up", "A", "⏰"), tok("you eat", "A", "🍽️"), tok("I read", "A", "📖"),
           tok("he sleeps", "B", "😴"), tok("she brushes", "B", "🪥"), tok("she goes", "B", "🏫")]),
      [qa("What time do you wake up?", "I wake up at seven."),
       qa("Does she go to school?", "Yes, she does."),
       qa("Do you brush your teeth?", "Yes, I always do."),
       qa("Does he sleep at noon?", "No, he doesn't.")]),
])
