# -*- coding: utf-8 -*-
from grammar_helpers import g, t, f, tok, srt, qa, L, W

# ===========================================================================
# WORLD 7 — Unit 7 · Activities I Love  (Present continuous: am/is/are + -ing)
# Grammar arc: I am + -ing, he/she is + -ing, they/we are + -ing, negative,
# questions, -ing spelling rules, seasons, now vs every day, tr/dr/gr, review.
# Core rule: present continuous = am/is/are + verb-ing.
#   I am / he,she,it is / you,we,they are.  Never "He are running" or "She is run".
# ===========================================================================
WORLD = W("Activities I Love", "Present continuous (-ing) — Magic Academy Unit 7", [

    L("The Camping Trip",
      [("running", "🏃"), ("swimming", "🏊"), ("riding", "🚴"),
       ("jumping", "🤸"), ("reading", "📖"), ("camping", "🏕️")],
      "I am + -ing",
      ["I am running.", "I am reading.", "I am jumping high.",
       "I am riding my bike.", "I am camping today.", "I am swimming now."],
      [g("I ___ running.", ["am", "is"], "am", "🏃"),
       g("I ___ reading.", ["am", "are"], "am", "📖"),
       g("I am ___.", ["jumping", "jump"], "jumping", "🤸"),
       g("I ___ camping.", ["am", "is"], "am", "🏕️")],
      [t("read + ing ->", "read", ["reading", "readding", "reads"], "reading"),
       t("jump + ing ->", "jump", ["jumping", "jumpping", "jumps"], "jumping"),
       t("camp + ing ->", "camp", ["camping", "campping", "camps"], "camping")],
      [f("I am running.", "I am run.", "🏃"),
       f("I am reading.", "I is reading.", "📖"),
       f("I am jumping.", "I are jumping.", "🤸"),
       f("I am camping.", "I am camp.", "🏕️")],
      srt("-ing", "base",
          [tok("running", "A", "🏃"), tok("reading", "A", "📖"), tok("jumping", "A", "🤸"),
           tok("run", "B", "🏃"), tok("read", "B", "📖"), tok("jump", "B", "🤸")]),
      [qa("What are you doing?", "I am running."),
       qa("Are you reading?", "Yes, I am reading."),
       qa("Are you swimming?", "No, I am camping."),
       qa("What are you doing now?", "I am jumping.")]),

    L("The Comet",
      [("flying", "🦅"), ("dancing", "💃"), ("painting", "🎨"),
       ("drawing", "✏️"), ("cooking", "🍳"), ("singing", "🎤")],
      "He / She is + -ing",
      ["She is swimming.", "He is cooking.", "She is dancing.",
       "He is drawing.", "She is singing.", "He is painting."],
      [g("She ___ dancing.", ["is", "am"], "is", "💃"),
       g("He ___ cooking.", ["is", "are"], "is", "🍳"),
       g("She is ___.", ["singing", "sing"], "singing", "🎤"),
       g("He ___ drawing.", ["is", "am"], "is", "✏️")],
      [t("cook + ing ->", "cook", ["cooking", "cookking", "cooks"], "cooking"),
       t("sing + ing ->", "sing", ["singing", "singging", "sings"], "singing"),
       t("draw + ing ->", "draw", ["drawing", "drawwing", "draws"], "drawing")],
      [f("She is dancing.", "She is dance.", "💃"),
       f("He is cooking.", "He are cooking.", "🍳"),
       f("She is singing.", "She am singing.", "🎤"),
       f("He is drawing.", "He is draw.", "✏️")],
      srt("is", "are",
          [tok("he", "A", "👦"), tok("she", "A", "👧"), tok("it", "A", "🐱"),
           tok("we", "B", "👫"), tok("they", "B", "👨‍👩‍👧"), tok("you", "B", "🧒")]),
      [qa("What is she doing?", "She is dancing."),
       qa("Is he cooking?", "Yes, he is."),
       qa("What is he doing?", "He is drawing."),
       qa("Is she singing?", "No, she is dancing.")]),

    L("Everyone's Busy",
      [("studying", "📚"), ("cooking", "🍳"), ("cleaning", "🧹"),
       ("playing", "⚽"), ("singing", "🎤"), ("dancing", "💃")],
      "They / We are + -ing",
      ["They are camping.", "We are playing.", "They are singing.",
       "We are cooking.", "They are dancing.", "We are studying."],
      [g("They ___ playing.", ["are", "is"], "are", "⚽"),
       g("We ___ cooking.", ["are", "am"], "are", "🍳"),
       g("They are ___.", ["dancing", "dance"], "dancing", "💃"),
       g("We ___ studying.", ["are", "is"], "are", "📚")],
      [t("play + ing ->", "play", ["playing", "plaiing", "plays"], "playing"),
       t("clean + ing ->", "clean", ["cleaning", "cleanning", "cleans"], "cleaning"),
       t("study + ing ->", "study", ["studying", "studing", "studdying"], "studying")],
      [f("They are playing.", "They is playing.", "⚽"),
       f("We are cooking.", "We are cook.", "🍳"),
       f("They are dancing.", "They am dancing.", "💃"),
       f("We are singing.", "We is singing.", "🎤")],
      srt("-ing", "base",
          [tok("playing", "A", "⚽"), tok("cooking", "A", "🍳"), tok("singing", "A", "🎤"),
           tok("play", "B", "⚽"), tok("cook", "B", "🍳"), tok("sing", "B", "🎤")]),
      [qa("What are they doing?", "They are playing."),
       qa("What are you doing?", "We are cooking."),
       qa("Are they singing?", "Yes, they are."),
       qa("Are you dancing?", "No, we are studying.")]),

    L("Not Now",
      [("resting", "😴"), ("sleeping", "🛌"), ("walking", "🚶"),
       ("talking", "🗣️"), ("watching", "📺"), ("reading", "📖")],
      "isn't / aren't + -ing",
      ["He isn't cooking.", "They aren't sleeping.", "She isn't walking.",
       "We aren't talking.", "He isn't reading.", "They aren't resting."],
      [g("He ___ walking.", ["isn't", "aren't"], "isn't", "🚶"),
       g("They ___ sleeping.", ["aren't", "isn't"], "aren't", "🛌"),
       g("She ___ talking.", ["isn't", "aren't"], "isn't", "🗣️"),
       g("We ___ resting.", ["aren't", "isn't"], "aren't", "😴")],
      [t("is not ->", "is not", ["isn't", "isnt", "aren't"], "isn't"),
       t("are not ->", "are not", ["aren't", "arent", "isn't"], "aren't"),
       t("walk + ing ->", "walk", ["walking", "walkking", "walks"], "walking")],
      [f("He isn't cooking.", "He aren't cooking.", "🍳"),
       f("They aren't sleeping.", "They isn't sleeping.", "🛌"),
       f("She isn't walking.", "She isn't walk.", "🚶"),
       f("We aren't talking.", "We aren't talk.", "🗣️")],
      srt("isn't", "aren't",
          [tok("he", "A", "👦"), tok("she", "A", "👧"), tok("it", "A", "🐱"),
           tok("we", "B", "👫"), tok("they", "B", "👨‍👩‍👧"), tok("you", "B", "🧒")]),
      [qa("Is he sleeping?", "No, he isn't."),
       qa("Are they cooking?", "No, they aren't."),
       qa("Is she talking?", "No, she isn't."),
       qa("Are you resting?", "No, we aren't.")]),

    L("What are you doing?",
      [("doing", "🤔"), ("playing", "⚽"), ("reading", "📖"),
       ("cooking", "🍳"), ("painting", "🎨"), ("eating", "🍽️")],
      "Questions: What are you doing?",
      ["What are you doing?", "I am painting.", "Is she reading?",
       "Yes, she is.", "What is he doing?", "He is cooking."],
      [g("What ___ you doing?", ["are", "is"], "are", "🤔"),
       g("___ she reading?", ["Is", "Are"], "Is", "📖"),
       g("What ___ he doing?", ["is", "are"], "is", "🍳"),
       g("___ they playing?", ["Are", "Is"], "Are", "⚽")],
      [t("paint + ing ->", "paint", ["painting", "paintting", "paints"], "painting"),
       t("eat + ing ->", "eat", ["eating", "eatting", "eats"], "eating"),
       t("play + ing ->", "play", ["playing", "plaiing", "plays"], "playing")],
      [f("What are you doing?", "What is you doing?", "🤔"),
       f("Is she reading?", "Are she reading?", "📖"),
       f("What is he doing?", "What are he doing?", "🍳"),
       f("Are they playing?", "Is they playing?", "⚽")],
      srt("Is ...?", "Are ...?",
          [tok("he", "A", "👦"), tok("she", "A", "👧"), tok("it", "A", "🐱"),
           tok("we", "B", "👫"), tok("they", "B", "👨‍👩‍👧"), tok("you", "B", "🧒")]),
      [qa("What are you doing?", "I am painting."),
       qa("Is she reading?", "Yes, she is."),
       qa("What is he doing?", "He is cooking."),
       qa("Are they playing?", "Yes, they are.")]),

    L("Sally's Lost Bag",
      [("run", "🏃"), ("ride", "🚴"), ("swim", "🏊"),
       ("make", "🔨"), ("cook", "🍳"), ("read", "📖")],
      "Spelling: add -ing",
      ["I am running fast.", "She is riding a bike.", "We are swimming now.",
       "He is making a cake.", "They are cooking dinner.", "I am reading a book."],
      [g("run + ing = ___", ["running", "runing"], "running", "🏃"),
       g("ride + ing = ___", ["riding", "rideing"], "riding", "🚴"),
       g("swim + ing = ___", ["swimming", "swiming"], "swimming", "🏊"),
       g("cook + ing = ___", ["cooking", "cookking"], "cooking", "🍳")],
      [t("run ->", "run", ["running", "runing", "runs"], "running"),
       t("ride ->", "ride", ["rideing", "riding", "ridding"], "riding"),
       t("make ->", "make", ["makeing", "making", "makking"], "making")],
      [f("I am running fast.", "I am runing fast.", "🏃"),
       f("She is riding home.", "She is rideing home.", "🚴"),
       f("We are swimming now.", "We are swiming now.", "🏊"),
       f("He is making cake.", "He is makeing cake.", "🔨")],
      srt("double letter", "drop e",
          [tok("run", "A", "🏃"), tok("swim", "A", "🏊"), tok("sit", "A", "🪑"),
           tok("ride", "B", "🚴"), tok("make", "B", "🔨"), tok("write", "B", "✍️")]),
      [qa("How do you spell run + ing?", "It is running."),
       qa("How do you spell ride + ing?", "It is riding."),
       qa("Does run double the n?", "Yes, it does."),
       qa("Does ride keep the e?", "No, it doesn't.")]),

    L("Seasons & Months",
      [("spring", "🌸"), ("summer", "☀️"), ("autumn", "🍂"),
       ("winter", "❄️"), ("rainy", "🌧️"), ("sunny", "😎")],
      "Seasons + -ing",
      ["In summer I am swimming.", "In winter we are skiing.",
       "In spring flowers are growing.", "It is raining today.",
       "In autumn leaves are falling.", "The sun is shining."],
      [g("In summer I ___ swimming.", ["am", "is"], "am", "☀️"),
       g("In winter we ___ skiing.", ["are", "is"], "are", "❄️"),
       g("It ___ raining now.", ["is", "are"], "is", "🌧️"),
       g("The sun ___ shining.", ["is", "are"], "is", "😎")],
      [t("rain + ing ->", "rain", ["raining", "rainning", "rains"], "raining"),
       t("shine + ing ->", "shine", ["shining", "shineing", "shinning"], "shining"),
       t("grow + ing ->", "grow", ["growing", "growwing", "grows"], "growing")],
      [f("It is raining today.", "It is rain today.", "🌧️"),
       f("The sun is shining.", "The sun are shining.", "😎"),
       f("In summer I am swimming.", "In summer I is swimming.", "☀️"),
       f("In winter we are skiing.", "In winter we is skiing.", "❄️")],
      srt("season", "weather",
          [tok("spring", "A", "🌸"), tok("summer", "A", "☀️"), tok("winter", "A", "❄️"),
           tok("rainy", "B", "🌧️"), tok("sunny", "B", "😎"), tok("snowy", "B", "🌨️")]),
      [qa("What are you doing in summer?", "I am swimming."),
       qa("What is the weather like?", "It is raining."),
       qa("Is it snowing?", "Yes, it is."),
       qa("What season is it?", "It is winter.")]),

    L("Now vs Every Day",
      [("play", "⚽"), ("read", "📖"), ("cook", "🍳"),
       ("run", "🏃"), ("eat", "🍎"), ("sing", "🎤")],
      "now (-ing) vs every day",
      ["Right now I am playing.", "Every day I play.", "Now she is reading.",
       "Every day she reads.", "Right now we are eating.", "Every day we eat."],
      [g("Right now I am ___.", ["playing", "play"], "playing", "⚽"),
       g("Every day I ___.", ["play", "playing"], "play", "⚽"),
       g("Now she is ___.", ["reading", "reads"], "reading", "📖"),
       g("Every day she ___.", ["reads", "reading"], "reads", "📖")],
      [t("play + ing ->", "play", ["playing", "plaiing", "plays"], "playing"),
       t("run + ing ->", "run", ["running", "runing", "runs"], "running"),
       t("eat + ing ->", "eat", ["eating", "eatting", "eats"], "eating")],
      [f("Right now I am playing.", "Right now I am play.", "⚽"),
       f("Every day I play.", "Every day I playing.", "⚽"),
       f("Now she is reading.", "Now she is reads.", "📖"),
       f("Every day she reads.", "Every day she read.", "📖")],
      srt("now", "every day",
          [tok("now", "A", "⏰"), tok("right now", "A", "⏰"), tok("today", "A", "📅"),
           tok("every day", "B", "🔁"), tok("always", "B", "🔁"), tok("usually", "B", "🔁")]),
      [qa("What are you doing now?", "I am playing."),
       qa("What do you do every day?", "I play soccer."),
       qa("Is she reading now?", "Yes, she is."),
       qa("What does she do every day?", "She reads books.")]),

    L("Sound Lab: tr/dr/gr",
      [("tree", "🌳"), ("truck", "🚚"), ("drum", "🥁"),
       ("dress", "👗"), ("green", "🟢"), ("grass", "🌱")],
      "Blends: tr / dr / gr",
      ["The truck is driving.", "She is playing the drum.",
       "The grass is growing.", "He is climbing a tree.",
       "She is wearing a green dress.", "The tree is growing tall."],
      [g("The ___ is driving.", ["truck", "truk"], "truck", "🚚"),
       g("She plays the ___.", ["drum", "durm"], "drum", "🥁"),
       g("The ___ is green.", ["grass", "gras"], "grass", "🌱"),
       g("He climbs a ___.", ["tree", "tre"], "tree", "🌳")],
      [t("one tree -> many...?", "tree", ["trees", "treees", "tree"], "trees"),
       t("one truck -> many...?", "truck", ["trucks", "truckes", "truck"], "trucks"),
       t("one dress -> many...?", "dress", ["dresses", "dresss", "dress"], "dresses")],
      [f("The truck is driving.", "The truk is driving.", "🚚"),
       f("The grass is green.", "The gras is green.", "🌱"),
       f("She plays the drum.", "She plays the durm.", "🥁"),
       f("He climbs a tree.", "He climbs a tre.", "🌳")],
      srt("tr", "dr",
          [tok("tree", "A", "🌳"), tok("truck", "A", "🚚"), tok("train", "A", "🚂"),
           tok("drum", "B", "🥁"), tok("dress", "B", "👗"), tok("drink", "B", "🥤")]),
      [qa("What starts with tr?", "Tree and truck."),
       qa("What starts with dr?", "Drum and dress."),
       qa("What color is the grass?", "It is green."),
       qa("What is she playing?", "She is playing the drum.")]),

    L("Action Champion",
      [("running", "🏃"), ("cooking", "🍳"), ("playing", "⚽"),
       ("reading", "📖"), ("dancing", "💃"), ("singing", "🎤")],
      "Review: am / is / are + -ing",
      ["I am running.", "She is cooking dinner.", "They are playing outside.",
       "He isn't reading now.", "What are you doing?", "We are singing a song."],
      [g("I ___ running.", ["am", "is"], "am", "🏃"),
       g("She ___ cooking.", ["is", "are"], "is", "🍳"),
       g("They ___ playing.", ["are", "is"], "are", "⚽"),
       g("He ___ reading now.", ["isn't", "aren't"], "isn't", "📖")],
      [t("run ->", "run", ["running", "runing", "runs"], "running"),
       t("dance ->", "dance", ["danceing", "dancing", "dancding"], "dancing"),
       t("sing ->", "sing", ["singing", "singging", "sings"], "singing")],
      [f("She is cooking dinner.", "She is cook dinner.", "🍳"),
       f("They are playing outside.", "They is playing outside.", "⚽"),
       f("He isn't reading now.", "He aren't reading now.", "📖"),
       f("I am running fast.", "I am runing fast.", "🏃")],
      srt("is", "are",
          [tok("he", "A", "👦"), tok("she", "A", "👧"), tok("it", "A", "🐱"),
           tok("we", "B", "👫"), tok("they", "B", "👨‍👩‍👧"), tok("you", "B", "🧒")]),
      [qa("What are you doing?", "I am running."),
       qa("What is she doing?", "She is cooking."),
       qa("Are they playing?", "Yes, they are."),
       qa("Is he sleeping?", "No, he isn't.")]),
])
