# -*- coding: utf-8 -*-
from grammar_helpers import g, t, f, tok, srt, qa, L, W

WORLD = W("How Much, How Many", "Quantity & prepositions — Magic Academy Unit 8", [

    L("The Plopster",
      [("apples", "🍎"), ("eggs", "🥚"), ("bananas", "🍌"), ("water", "💧"), ("rice", "🍚"), ("milk", "🥛")],
      "count vs don't count",
      ["I see many apples.", "There are three eggs.", "I like bananas.",
       "I want some water.", "There is some rice.", "I drink milk."],
      [g("How ___ apples?", ["many", "much"], "many", "🍎"),
       g("How ___ water?", ["many", "much"], "much", "💧"),
       g("How ___ eggs?", ["many", "much"], "many", "🥚"),
       g("How ___ milk?", ["many", "much"], "much", "🥛")],
      [t("one apple -> many...?", "apple", ["apples", "appls", "apple"], "apples"),
       t("one egg -> many...?", "egg", ["eggs", "egges", "egg"], "eggs"),
       t("one banana -> many...?", "banana", ["bananas", "bananaes", "banana"], "bananas")],
      [f("How many apples?", "How much apples?", "🍎"),
       f("How much water?", "How many water?", "💧"),
       f("How many eggs?", "How much eggs?", "🥚"),
       f("How much rice?", "How many rice?", "🍚")],
      srt("count (many)", "don't count (much)",
          [tok("apples", "A", "🍎"), tok("eggs", "A", "🥚"), tok("bananas", "A", "🍌"),
           tok("water", "B", "💧"), tok("rice", "B", "🍚"), tok("milk", "B", "🥛")]),
      [qa("How many apples?", "I see five apples."),
       qa("How much water?", "Just a little."),
       qa("Do you like bananas?", "Yes, I do."),
       qa("Do you want milk?", "No, thank you.")]),

    L("A, An, Some",
      [("egg", "🥚"), ("apple", "🍎"), ("rice", "🍚"), ("bread", "🍞"), ("water", "💧"), ("banana", "🍌")],
      "a / an / some",
      ["I want an egg.", "I want some rice.", "I have an apple.",
       "I have some bread.", "I need a banana.", "I need some water."],
      [g("I want ___ egg.", ["a", "an", "some"], "an", "🥚"),
       g("I want ___ rice.", ["a", "an", "some"], "some", "🍚"),
       g("I have ___ apple.", ["a", "an", "some"], "an", "🍎"),
       g("I need ___ water.", ["a", "an", "some"], "some", "💧")],
      [t("one egg -> many...?", "egg", ["eggs", "egges", "egg"], "eggs"),
       t("one apple -> many...?", "apple", ["apples", "appls", "apple"], "apples"),
       t("one banana -> many...?", "banana", ["bananas", "bananaes", "banana"], "bananas")],
      [f("I want an egg.", "I want a egg.", "🥚"),
       f("I have some rice.", "I have a rice.", "🍚"),
       f("I need some water.", "I need a water.", "💧"),
       f("I have some bread.", "I have a bread.", "🍞")],
      srt("a / an", "some",
          [tok("egg", "A", "🥚"), tok("apple", "A", "🍎"), tok("banana", "A", "🍌"),
           tok("rice", "B", "🍚"), tok("bread", "B", "🍞"), tok("water", "B", "💧")]),
      [qa("What do you want?", "I want an egg."),
       qa("Do you want rice?", "Yes, some rice, please."),
       qa("Is there any bread?", "Yes, there is some bread."),
       qa("Can I have an apple?", "Yes, here you are.")]),

    L("Count Them",
      [("apples", "🍎"), ("eggs", "🥚"), ("bananas", "🍌"), ("oranges", "🍊"), ("pears", "🍐"), ("grapes", "🍇")],
      "How many ...?",
      ["How many apples?", "There are three apples.", "How many eggs are there?",
       "I have five bananas.", "How many oranges do you see?", "I see two pears."],
      [g("How ___ apples?", ["many", "much"], "many", "🍎"),
       g("How ___ eggs?", ["many", "much"], "many", "🥚"),
       g("How ___ pears?", ["many", "much"], "many", "🍐"),
       g("How ___ grapes?", ["many", "much"], "many", "🍇")],
      [t("one apple -> many...?", "apple", ["apples", "appls", "apple"], "apples"),
       t("one orange -> many...?", "orange", ["oranges", "orangs", "orange"], "oranges"),
       t("one pear -> many...?", "pear", ["pears", "peares", "pear"], "pears")],
      [f("How many apples?", "How much apples?", "🍎"),
       f("How many oranges?", "How much oranges?", "🍊"),
       f("How many grapes?", "How much grapes?", "🍇"),
       f("There are five eggs.", "There are five egg.", "🥚")],
      srt("how many", "how much",
          [tok("apples", "A", "🍎"), tok("eggs", "A", "🥚"), tok("bananas", "A", "🍌"),
           tok("water", "B", "💧"), tok("milk", "B", "🥛"), tok("rice", "B", "🍚")]),
      [qa("How many apples?", "There are three."),
       qa("How many eggs?", "There are six."),
       qa("How many bananas?", "There are two."),
       qa("How many oranges?", "There are four.")]),

    L("Plopster Asleep",
      [("water", "💧"), ("juice", "🧃"), ("rice", "🍚"), ("sugar", "🧂"), ("milk", "🥛"), ("bread", "🍞")],
      "How much ...?",
      ["How much water?", "How much juice do you want?", "I want some milk.",
       "How much sugar is there?", "There is a little rice.", "I have some bread."],
      [g("How ___ water?", ["many", "much"], "much", "💧"),
       g("How ___ juice?", ["many", "much"], "much", "🧃"),
       g("How ___ sugar?", ["many", "much"], "much", "🧂"),
       g("How ___ milk?", ["many", "much"], "much", "🥛")],
      [t("no plural ->", "water", ["waters", "water", "waterz"], "water"),
       t("no plural ->", "rice", ["rices", "rice", "ricees"], "rice"),
       t("no plural ->", "sugar", ["sugars", "sugar", "suger"], "sugar")],
      [f("How much water?", "How many water?", "💧"),
       f("How much juice?", "How many juice?", "🧃"),
       f("How much sugar?", "How many sugar?", "🧂"),
       f("How much bread?", "How many bread?", "🍞")],
      srt("how much", "how many",
          [tok("water", "A", "💧"), tok("juice", "A", "🧃"), tok("milk", "A", "🥛"),
           tok("apples", "B", "🍎"), tok("eggs", "B", "🥚"), tok("oranges", "B", "🍊")]),
      [qa("How much water?", "Just a little."),
       qa("How much juice do you want?", "A big glass, please."),
       qa("How much sugar?", "Not much, thanks."),
       qa("Do you want some milk?", "Yes, please.")]),

    L("Some or Any?",
      [("apples", "🍎"), ("rice", "🍚"), ("juice", "🧃"), ("eggs", "🥚"), ("sugar", "🧂"), ("milk", "🥛")],
      "some / any",
      ["I have some juice.", "I don't have any sugar.", "Do you have any milk?",
       "There are some apples.", "We don't have any eggs.", "Is there any rice?"],
      [g("I have ___ juice.", ["some", "any"], "some", "🧃"),
       g("I don't have ___ sugar.", ["some", "any"], "any", "🧂"),
       g("Do you have ___ milk?", ["some", "any"], "any", "🥛"),
       g("There are ___ apples.", ["some", "any"], "some", "🍎")],
      [t("one apple -> many...?", "apple", ["apples", "appls", "apple"], "apples"),
       t("one egg -> many...?", "egg", ["eggs", "egges", "egg"], "eggs"),
       t("one orange -> many...?", "orange", ["oranges", "orangs", "orange"], "oranges")],
      [f("I have some juice.", "I have any juice.", "🧃"),
       f("We don't have any eggs.", "We don't have some eggs.", "🥚"),
       f("There are some apples.", "There are any apples.", "🍎"),
       f("I don't have any rice.", "I don't have some rice.", "🍚")],
      srt("some", "any",
          [tok("I have some milk.", "A", "🥛"), tok("There is some rice.", "A", "🍚"), tok("I want some juice.", "A", "🧃"),
           tok("I don't have any milk.", "B", "🥛"), tok("Is there any rice?", "B", "🍚"), tok("Do you want any juice?", "B", "🧃")]),
      [qa("Do you have any juice?", "Yes, I have some."),
       qa("Is there any sugar?", "No, there isn't any."),
       qa("Do you want some milk?", "Yes, please."),
       qa("Are there any eggs?", "No, there aren't any.")]),

    L("Wake the Plopster",
      [("juice", "🧃"), ("water", "💧"), ("milk", "🥛"), ("cake", "🍰"), ("bread", "🍞"), ("rice", "🍚")],
      "I would like ...",
      ["I would like some juice.", "I would like some cake.", "I'd like some water, please.",
       "I would like some milk.", "I'd like some bread.", "Would you like some rice?"],
      [g("I ___ like some juice.", ["would", "will"], "would", "🧃"),
       g("I ___ like some cake.", ["would", "will"], "would", "🍰"),
       g("I'd like ___ water.", ["some", "a"], "some", "💧"),
       g("Would you like ___ milk?", ["some", "a"], "some", "🥛")],
      [t("I would ->", "I would", ["I'd", "Ied", "I'ld"], "I'd"),
       t("you would ->", "you would", ["you'd", "youd", "yould"], "you'd"),
       t("we would ->", "we would", ["we'd", "wed", "we'ld"], "we'd")],
      [f("I would like some water.", "I would like a water.", "💧"),
       f("Would you like some milk?", "Would you like a milk?", "🥛"),
       f("I would like some rice.", "I would like some rices.", "🍚")],
      srt("I would like", "Would you like?",
          [tok("I'd like juice.", "A", "🧃"), tok("I would like cake.", "A", "🍰"), tok("I'd like water.", "A", "💧"),
           tok("Would you like milk?", "B", "🥛"), tok("Would you like bread?", "B", "🍞"), tok("Would you like rice?", "B", "🍚")]),
      [qa("Would you like some juice?", "Yes, please."),
       qa("What would you like?", "I would like some cake."),
       qa("Would you like some milk?", "No, thank you."),
       qa("Would you like tea or juice?", "Juice, please.")]),

    L("Where's the Egg?",
      [("egg", "🥚"), ("box", "📦"), ("cup", "☕"), ("bag", "🎒"), ("table", "🍽️"), ("chair", "🪑")],
      "in / on / under / next to",
      ["The egg is in the box.", "The egg is on the table.", "The cup is under the chair.",
       "The bag is on the chair.", "The egg is next to the cup.", "It is in the bag."],
      [g("The egg is ___ the box.", ["in", "under"], "in", "🥚"),
       g("The cup is ___ the table.", ["on", "under"], "on", "☕"),
       g("The bag is ___ the chair.", ["on", "in"], "on", "🎒"),
       g("The egg is ___ the cup.", ["next to", "on"], "next to", "🥚")],
      [t("one box -> many...?", "box", ["boxes", "boxs", "box"], "boxes"),
       t("one cup -> many...?", "cup", ["cups", "cupes", "cup"], "cups"),
       t("one egg -> many...?", "egg", ["eggs", "egges", "egg"], "eggs")],
      [f("The eggs are in the box.", "The eggs is in the box.", "🥚"),
       f("The cups are on the table.", "The cups is on the table.", "☕"),
       f("The egg is under the chair.", "The egg are under the chair.", "🪑")],
      srt("in", "on",
          [tok("in the box", "A", "📦"), tok("in the bag", "A", "🎒"), tok("in the cup", "A", "☕"),
           tok("on the table", "B", "🍽️"), tok("on the chair", "B", "🪑"), tok("on the box", "B", "📦")]),
      [qa("Where is the egg?", "It is in the box."),
       qa("Where is the cup?", "It is on the table."),
       qa("Where is the bag?", "It is under the chair."),
       qa("Is the egg on the table?", "No, it is under the table.")]),

    L("Big Letters",
      [("name", "🏷️"), ("day", "📅"), ("city", "🏙️"), ("school", "🏫"), ("home", "🏠"), ("book", "📕")],
      "Capital letters",
      ["My name is Dan.", "I live in London.", "We go to school.",
       "I read my book.", "Monday is a fun day.", "I am at home."],
      [g("___ name is Ben.", ["My", "my"], "My", "🏷️"),
       g("My friend is ___.", ["Dan", "dan"], "Dan", "🏷️"),
       g("___ am happy.", ["I", "i"], "I", "😀"),
       g("I go to ___ today.", ["school", "School"], "school", "🏫")],
      [t("a name ->", "dan", ["Dan", "dan", "DAN"], "Dan"),
       t("a city ->", "paris", ["Paris", "paris", "PARIS"], "Paris"),
       t("the word I ->", "I", ["I", "i", "ai"], "I")],
      [f("My name is Dan.", "My name is dan.", "🏷️"),
       f("I like books.", "i like books.", "📕"),
       f("We live in London.", "We live in london.", "🏙️"),
       f("Monday is fun.", "monday is fun.", "📅")],
      srt("capital letter", "small letter",
          [tok("Dan", "A", "🏷️"), tok("London", "A", "🏙️"), tok("Monday", "A", "📅"),
           tok("book", "B", "📕"), tok("school", "B", "🏫"), tok("home", "B", "🏠")]),
      [qa("What is your name?", "My name is Dan."),
       qa("Where do you live?", "I live in London."),
       qa("What day is it?", "It is Monday."),
       qa("Do you like school?", "Yes, I do.")]),

    L("Sound Lab: bl/fl/cl/pl",
      [("blue", "🔵"), ("flag", "🚩"), ("clock", "🕐"), ("plan", "📋"), ("glad", "😄"), ("plum", "🟣")],
      "Start blends: bl fl cl pl",
      ["The flag is blue.", "The clock is here.", "I have a plan.",
       "I am so glad.", "The plum is sweet.", "I see a blue clock."],
      [g("The sky is ___.", ["blue", "blu"], "blue", "🔵"),
       g("Look at the ___.", ["clock", "clok"], "clock", "🕐"),
       g("I have a ___.", ["plan", "plen"], "plan", "📋"),
       g("I am ___.", ["glad", "glid"], "glad", "😄")],
      [t("one flag -> many...?", "flag", ["flags", "flages", "flag"], "flags"),
       t("one clock -> many...?", "clock", ["clocks", "clockes", "clock"], "clocks"),
       t("one plum -> many...?", "plum", ["plums", "plumes", "plum"], "plums")],
      [f("The flag is blue.", "The flag is blu.", "🔵"),
       f("I have a plan.", "I have a plen.", "📋"),
       f("The clock is here.", "The clok is here.", "🕐"),
       f("I am so glad.", "I am so glid.", "😄")],
      srt("cl-", "pl-",
          [tok("clock", "A", "🕐"), tok("clap", "A", "👏"), tok("clean", "A", "🧼"),
           tok("plan", "B", "📋"), tok("plum", "B", "🟣"), tok("play", "B", "🎮")]),
      [qa("What color is the flag?", "It is blue."),
       qa("What is that?", "It is a clock."),
       qa("Do you have a plan?", "Yes, I do."),
       qa("Are you glad?", "Yes, I am glad.")]),

    L("Quantity Champion",
      [("apple", "🍎"), ("egg", "🥚"), ("water", "💧"), ("rice", "🍚"), ("juice", "🧃"), ("milk", "🥛")],
      "Unit 8 review",
      ["I would like some juice.", "How many apples?", "How much water?",
       "I don't have any rice.", "There is an egg.", "I have some milk."],
      [g("How ___ apples?", ["many", "much"], "many", "🍎"),
       g("How ___ water?", ["many", "much"], "much", "💧"),
       g("I don't have ___ rice.", ["some", "any"], "any", "🍚"),
       g("I want ___ egg.", ["an", "some"], "an", "🥚")],
      [t("one apple -> many...?", "apple", ["apples", "appls", "apple"], "apples"),
       t("one egg -> many...?", "egg", ["eggs", "egges", "egg"], "eggs"),
       t("one orange -> many...?", "orange", ["oranges", "orangs", "orange"], "oranges")],
      [f("How many eggs?", "How much eggs?", "🥚"),
       f("How much water?", "How many water?", "💧"),
       f("I have some milk.", "I have any milk.", "🥛"),
       f("I want an apple.", "I want a apple.", "🍎")],
      srt("how many", "how much",
          [tok("apples", "A", "🍎"), tok("eggs", "A", "🥚"), tok("oranges", "A", "🍊"),
           tok("water", "B", "💧"), tok("rice", "B", "🍚"), tok("milk", "B", "🥛")]),
      [qa("How many apples?", "There are four."),
       qa("How much juice?", "Just a little."),
       qa("Would you like some milk?", "Yes, please."),
       qa("Do you have any rice?", "No, I don't.")]),
])
