# -*- coding: utf-8 -*-
from grammar_helpers import g, t, f, tok, srt, qa, L, W

# ===========================================================================
# WORLD 9 — Unit 9 · Let's Compare  (Comparative adjectives)
# Grammar arc: base adjectives -> -er -> -er than -> spelling rules ->
# irregular better/worse -> more + long adjective -> countries/nationalities
# -> comparing things -> sm/sp/tw blends -> review.
# KEY: short adj + -er (double / y->i); long adj use "more ..."; irregular
# good->better, bad->worse, far->farther; comparisons use "than".
# NEVER apply -er/more to nouns or countries.
# ===========================================================================
WORLD = W("Let's Compare", "Comparative adjectives — Magic Academy Unit 9", [

    L("The Empty Zoo",
      [("big", "🐘"), ("small", "🐜"), ("fast", "🐆"), ("slow", "🐢"), ("tall", "🦒"), ("short", "🐇")],
      "Adjectives (base form)",
      ["The lion is big.", "The mouse is small.", "The cheetah is fast.",
       "The turtle is slow.", "The giraffe is tall."],
      [g("The lion ___ big.", ["is", "are"], "is", "🦁"),
       g("The mice ___ small.", ["are", "is"], "are", "🐭"),
       g("The turtle is ___.", ["slow", "fast"], "slow", "🐢"),
       g("The giraffe is ___.", ["tall", "short"], "tall", "🦒")],
      [t("spell it ->", "small", ["small", "smal", "smoll"], "small"),
       t("spell it ->", "fast", ["fast", "fasst", "faste"], "fast"),
       t("spell it ->", "short", ["short", "shortt", "shrot"], "short")],
      [f("The lion is big.", "The lion is bigs.", "🦁"),
       f("The turtle is slow.", "The turtle is slows.", "🐢"),
       f("The giraffe is tall.", "The giraffe is talls.", "🦒")],
      srt("big", "small",
          [tok("elephant", "A", "🐘"), tok("whale", "A", "🐋"), tok("lion", "A", "🦁"),
           tok("ant", "B", "🐜"), tok("mouse", "B", "🐭"), tok("bee", "B", "🐝")]),
      [qa("Is the lion big?", "Yes, it is big."),
       qa("Is the mouse big?", "No, it is small."),
       qa("Is the turtle fast?", "No, it is slow."),
       qa("How tall is the giraffe?", "It is very tall.")]),

    L("The Fireflies",
      [("big", "🐘"), ("small", "🐜"), ("fast", "🐆"), ("slow", "🐢"), ("tall", "🦒"), ("short", "🐇")],
      "Comparative (-er)",
      ["A lion is bigger.", "A mouse is smaller.", "A cheetah is faster.",
       "A turtle is slower.", "A giraffe is taller."],
      [g("A whale is ___.", ["bigger", "big"], "bigger", "🐋"),
       g("A snail is ___.", ["slower", "slow"], "slower", "🐌"),
       g("A jet is ___.", ["faster", "fast"], "faster", "✈️"),
       g("A tree is ___.", ["taller", "tall"], "taller", "🌳")],
      [t("big ->", "big", ["bigger", "biger", "bigest"], "bigger"),
       t("small ->", "small", ["smaller", "smoller", "smallest"], "smaller"),
       t("fast ->", "fast", ["faster", "fastar", "fastest"], "faster"),
       t("tall ->", "tall", ["taller", "tallor", "tallest"], "taller")],
      [f("A lion is bigger.", "A lion is biger.", "🦁"),
       f("A tree is taller.", "A tree is tallest.", "🌳"),
       f("A jet is faster.", "A jet is fastest.", "✈️")],
      srt("size", "speed",
          [tok("bigger", "A"), tok("smaller", "A"), tok("taller", "A"),
           tok("faster", "B"), tok("slower", "B"), tok("quicker", "B")]),
      [qa("Is a lion bigger?", "Yes, it is bigger."),
       qa("Is a snail faster?", "No, it is slower."),
       qa("Which is taller?", "The giraffe is taller."),
       qa("Which is smaller?", "The mouse is smaller.")]),

    L("Bigger Than",
      [("lion", "🦁"), ("cat", "🐱"), ("mouse", "🐭"), ("giraffe", "🦒"), ("turtle", "🐢"), ("rabbit", "🐇")],
      "-er than",
      ["A lion is bigger than a cat.", "A giraffe is taller than a dog.",
       "A cat is bigger than a mouse.", "A rabbit is faster than a turtle.",
       "A mouse is smaller than a cat."],
      [g("A lion is bigger ___ a cat.", ["than", "then"], "than", "🦁"),
       g("A cat is bigger than ___ mouse.", ["a", "an"], "a", "🐱"),
       g("A giraffe is ___ than a dog.", ["taller", "tall"], "taller", "🦒"),
       g("A turtle is slower ___ a rabbit.", ["than", "that"], "than", "🐢")],
      [t("big ->", "big", ["bigger", "biger", "bigest"], "bigger"),
       t("small ->", "small", ["smaller", "smaler", "smallest"], "smaller"),
       t("slow ->", "slow", ["slower", "slowest", "slowwer"], "slower")],
      [f("A lion is bigger than a cat.", "A lion is bigger then a cat.", "🦁"),
       f("A cat is bigger than a mouse.", "A cat is bigger than an mouse.", "🐱"),
       f("A giraffe is taller than a dog.", "A giraffe is tall than a dog.", "🦒")],
      srt("big", "small",
          [tok("lion", "A", "🦁"), tok("giraffe", "A", "🦒"), tok("horse", "A", "🐴"),
           tok("mouse", "B", "🐭"), tok("ant", "B", "🐜"), tok("rabbit", "B", "🐇")]),
      [qa("Is a lion bigger than a cat?", "Yes, it is."),
       qa("Is a mouse bigger than a cat?", "No, it is smaller."),
       qa("Which is taller, a giraffe or a dog?", "The giraffe is taller."),
       qa("Which is faster, a rabbit or a turtle?", "The rabbit is faster.")]),

    L("Spelling Rules",
      [("big", "🐘"), ("hot", "🔥"), ("happy", "😀"), ("nice", "🙂"), ("large", "🐋"), ("sad", "😢")],
      "Spelling comparatives",
      ["This box is bigger.", "Today is hotter than yesterday.", "She is happier now.",
       "That flower is nicer.", "A whale is larger than a fish."],
      [g("Today is ___ than ice.", ["hotter", "hoter"], "hotter", "🔥"),
       g("She is ___ today.", ["happier", "happyer"], "happier", "😀"),
       g("This box is ___.", ["bigger", "biger"], "bigger", "📦"),
       g("This flower is ___.", ["nicer", "niceer"], "nicer", "🌸")],
      [t("happy ->", "happy", ["happier", "happyer", "happior"], "happier"),
       t("big ->", "big", ["bigger", "biger", "bigest"], "bigger"),
       t("nice ->", "nice", ["nicer", "nicerr", "niceer"], "nicer"),
       t("hot ->", "hot", ["hotter", "hoter", "hotier"], "hotter")],
      [f("This box is bigger.", "This box is biger.", "📦"),
       f("She is happier now.", "She is happyer now.", "😀"),
       f("That flower is nicer.", "That flower is niceer.", "🌸"),
       f("Today is hotter.", "Today is hoter.", "🔥")],
      srt("double", "add -er",
          [tok("big", "A"), tok("hot", "A"), tok("sad", "A"),
           tok("small", "B"), tok("tall", "B"), tok("clean", "B")]),
      [qa("How do you spell bigger?", "B-I-G-G-E-R."),
       qa("Is it happyer or happier?", "It is happier."),
       qa("Does nice become nicer?", "Yes, just add r."),
       qa("Is today hotter?", "Yes, it is hotter.")]),

    L("Better or Worse",
      [("good", "👍"), ("bad", "👎"), ("far", "🛣️"), ("big", "🐘"), ("small", "🐜"), ("fast", "🏎️")],
      "Irregular comparatives",
      ["This book is better than that one.", "The weather is worse today.",
       "My grade is better now.", "The traffic is worse than before.",
       "The park is farther than the shop."],
      [g("This is ___ than that.", ["better", "gooder"], "better", "👍"),
       g("The weather is ___ today.", ["worse", "badder"], "worse", "👎"),
       g("Cake is ___ than soup.", ["better", "more good"], "better", "🍰"),
       g("The rain makes it ___.", ["worse", "worser"], "worse", "🌧️")],
      [t("good ->", "good", ["gooder", "better", "best"], "better"),
       t("bad ->", "bad", ["badder", "worse", "worser"], "worse"),
       t("far ->", "far", ["farther", "farer", "more far"], "farther")],
      [f("This book is better.", "This book is gooder.", "👍"),
       f("The weather is worse.", "The weather is badder.", "👎"),
       f("The soup is worse than cake.", "The soup is worser than cake.", "🍲")],
      srt("good", "bad",
          [tok("great", "A", "🌟"), tok("happy", "A", "😀"), tok("nice", "A", "🙂"),
           tok("awful", "B", "😖"), tok("sad", "B", "😢"), tok("sick", "B", "🤒")]),
      [qa("Is this better or worse?", "It is better."),
       qa("How is the weather?", "It is worse than before."),
       qa("Is cake better than soup?", "Yes, it is better."),
       qa("Which is farther?", "The park is farther.")]),

    L("More Beautiful",
      [("careful", "⚠️"), ("famous", "⭐"), ("helpful", "🤝"), ("friendly", "😊"), ("useful", "🔧"), ("tasty", "😋")],
      "more + adjective",
      ["A rose is more beautiful than a weed.", "This book is more interesting.",
       "This tool is more useful.", "That cake is more delicious.",
       "He is more famous than you."],
      [g("A rose is ___ than a weed.", ["more beautiful", "beautifuler"], "more beautiful", "🌹"),
       g("This tool is ___.", ["more useful", "usefuler"], "more useful", "🔧"),
       g("She is ___ than me.", ["more careful", "carefuler"], "more careful", "⚠️"),
       g("This book is ___.", ["more interesting", "interestinger"], "more interesting", "📖")],
      [t("beautiful ->", "beautiful", ["more beautiful", "beautifuler", "beautifulest"], "more beautiful"),
       t("careful ->", "careful", ["more careful", "carefuler", "carefulest"], "more careful"),
       t("famous ->", "famous", ["more famous", "famouser", "famousest"], "more famous"),
       t("useful ->", "useful", ["more useful", "usefuler", "usefulest"], "more useful")],
      [f("A rose is more beautiful than a weed.", "A rose is more beautiful then a weed.", "🌹"),
       f("This tool is more useful.", "This tool is most useful.", "🔧"),
       f("He is more famous.", "He is most famous.", "⭐")],
      srt("add -er", "use more",
          [tok("big", "A"), tok("fast", "A"), tok("tall", "A"),
           tok("famous", "B"), tok("careful", "B"), tok("helpful", "B")]),
      [qa("Is a rose more beautiful than a weed?", "Yes, it is."),
       qa("Which book is more interesting?", "This one is more interesting."),
       qa("Is he more famous now?", "Yes, he is more famous."),
       qa("Which tool is more useful?", "The hammer is more useful.")]),

    L("Slime Maker",
      [("Spain", "🇪🇸"), ("France", "🇫🇷"), ("Japan", "🇯🇵"), ("Brazil", "🇧🇷"), ("India", "🇮🇳"), ("Italy", "🇮🇹")],
      "from + nationality",
      ["She is from Spain.", "He is from Japan.", "She is Spanish.",
       "He is Japanese.", "They are from Brazil.", "We are Italian."],
      [g("She is from Spain. She is ___.", ["Spanish", "Spainish"], "Spanish", "🇪🇸"),
       g("He is from Japan. He is ___.", ["Japanese", "Japanish"], "Japanese", "🇯🇵"),
       g("She is from France. She is ___.", ["French", "Franch"], "French", "🇫🇷"),
       g("He is from Italy. He is ___.", ["Italian", "Italish"], "Italian", "🇮🇹")],
      [t("Spain ->", "Spain", ["Spanish", "Spainish", "Spainer"], "Spanish"),
       t("Japan ->", "Japan", ["Japanese", "Japanish", "Japaner"], "Japanese"),
       t("France ->", "France", ["French", "Franch", "Francer"], "French"),
       t("Italy ->", "Italy", ["Italian", "Italish", "Italier"], "Italian")],
      [f("She is from Spain.", "She is from Spanish.", "🇪🇸"),
       f("He is Japanese.", "He is Japan.", "🇯🇵"),
       f("She is French.", "She is France.", "🇫🇷"),
       f("They are from Italy.", "They are from Italian.", "🇮🇹")],
      srt("country", "nationality",
          [tok("Spain", "A", "🇪🇸"), tok("Japan", "A", "🇯🇵"), tok("France", "A", "🇫🇷"),
           tok("Spanish", "B"), tok("Japanese", "B"), tok("French", "B")]),
      [qa("Where is she from?", "She is from Spain."),
       qa("Is he Japanese?", "Yes, he is from Japan."),
       qa("Where are they from?", "They are from Italy."),
       qa("Is she French?", "Yes, she is from France.")]),

    L("The Talking Bubbles",
      [("shark", "🦈"), ("dolphin", "🐬"), ("whale", "🐋"), ("crab", "🦀"), ("fish", "🐟"), ("turtle", "🐢")],
      "Comparing things",
      ["A whale is bigger than a fish.", "A shark is faster than a crab.",
       "A dolphin is smarter than a fish.", "A whale is heavier than a shark.",
       "A crab is smaller than a turtle."],
      [g("A whale is ___ than a fish.", ["bigger", "biger"], "bigger", "🐋"),
       g("A shark is faster ___ a crab.", ["than", "then"], "than", "🦈"),
       g("A dolphin is ___ than a crab.", ["smarter", "more smart"], "smarter", "🐬"),
       g("A crab is ___ than a whale.", ["smaller", "smallest"], "smaller", "🦀")],
      [t("big ->", "big", ["bigger", "biger", "bigest"], "bigger"),
       t("fast ->", "fast", ["faster", "fastest", "fastar"], "faster"),
       t("heavy ->", "heavy", ["heavier", "heavyer", "heaviest"], "heavier"),
       t("small ->", "small", ["smaller", "smaler", "smallest"], "smaller")],
      [f("A whale is bigger than a fish.", "A whale is biger than a fish.", "🐋"),
       f("A shark is faster than a crab.", "A shark is faster then a crab.", "🦈"),
       f("A dolphin is smarter than a fish.", "A dolphin is smart than a fish.", "🐬")],
      srt("big", "small",
          [tok("whale", "A", "🐋"), tok("shark", "A", "🦈"), tok("dolphin", "A", "🐬"),
           tok("crab", "B", "🦀"), tok("fish", "B", "🐟"), tok("shrimp", "B", "🦐")]),
      [qa("Is a whale bigger than a fish?", "Yes, it is."),
       qa("Which is faster, a shark or a crab?", "The shark is faster."),
       qa("Is a crab bigger than a whale?", "No, it is smaller."),
       qa("Which is heavier?", "The whale is heavier.")]),

    L("Sound Lab: sm/sp/tw",
      [("small", "🐜"), ("smile", "😊"), ("spoon", "🥄"), ("spin", "🌀"), ("twin", "👯"), ("twelve", "🕛")],
      "Blends sm / sp / tw",
      ["I see a big smile.", "Please pass the spoon.", "The top can spin.",
       "I have a twin.", "There are twelve eggs."],
      [g("Please pass the ___.", ["spoon", "spuun"], "spoon", "🥄"),
       g("The top can ___.", ["spin", "spen"], "spin", "🌀"),
       g("I have a ___ brother.", ["twin", "twen"], "twin", "👯"),
       g("She has a big ___.", ["smile", "smyle"], "smile", "😊")],
      [t("spell it ->", "smile", ["smile", "smyle", "smil"], "smile"),
       t("spell it ->", "spoon", ["spoon", "spone", "spoun"], "spoon"),
       t("spell it ->", "twelve", ["twelve", "twelv", "twelfe"], "twelve"),
       t("spell it ->", "small", ["small", "smal", "smoll"], "small")],
      [f("Please pass the spoon.", "Please pass the spuun.", "🥄"),
       f("The top can spin.", "The top can spen.", "🌀"),
       f("She has a nice smile.", "She has a nice smyle.", "😊")],
      srt("sm", "sp",
          [tok("small", "A"), tok("smile", "A"), tok("smell", "A"),
           tok("spoon", "B"), tok("spin", "B"), tok("spider", "B")]),
      [qa("What starts with sp?", "Spoon starts with sp."),
       qa("Can the top spin?", "Yes, it can spin."),
       qa("Do you have a twin?", "Yes, I have a twin."),
       qa("How many eggs?", "There are twelve eggs.")]),

    L("Compare Champion",
      [("tall", "🦒"), ("good", "👍"), ("bad", "👎"), ("happy", "😀"), ("famous", "⭐"), ("fast", "🏎️")],
      "Comparatives review",
      ["A giraffe is taller than a dog.", "This book is better than that one.",
       "The weather is worse today.", "A rose is more beautiful than a weed.",
       "A cheetah is faster than a cat.", "She is happier now."],
      [g("A giraffe is ___ than a dog.", ["taller", "more tall"], "taller", "🦒"),
       g("This is ___ than that.", ["better", "gooder"], "better", "👍"),
       g("A rose is ___ than a weed.", ["more beautiful", "beautifuler"], "more beautiful", "🌹"),
       g("The weather is ___ today.", ["worse", "badder"], "worse", "👎")],
      [t("tall ->", "tall", ["taller", "more tall", "tallest"], "taller"),
       t("good ->", "good", ["gooder", "better", "best"], "better"),
       t("bad ->", "bad", ["badder", "worse", "worser"], "worse"),
       t("beautiful ->", "beautiful", ["more beautiful", "beautifuler", "beautifulest"], "more beautiful")],
      [f("A giraffe is taller than a dog.", "A giraffe is taller then a dog.", "🦒"),
       f("This book is better.", "This book is gooder.", "👍"),
       f("The weather is worse.", "The weather is worser.", "👎"),
       f("A cheetah is faster than a cat.", "A cheetah is fast than a cat.", "🏎️")],
      srt("add -er", "use more",
          [tok("tall", "A"), tok("fast", "A"), tok("big", "A"),
           tok("famous", "B"), tok("careful", "B"), tok("important", "B")]),
      [qa("Is a giraffe taller than a dog?", "Yes, it is."),
       qa("Which is better?", "This one is better."),
       qa("How is the weather?", "It is worse than before."),
       qa("Is a rose more beautiful than a weed?", "Yes, it is more beautiful.")]),
])
