# -*- coding: utf-8 -*-
from grammar_helpers import g, t, f, tok, srt, qa, L, W

# ===========================================================================
# WORLD 10 — Unit 10 · Places & Past  (was/were, there was/were, directions)
# Grammar arc: places & transport -> was/were (+/-/?) -> there was/were ->
# directions -> past time words -> build with was/were -> str/nch reading ->
# mastery review (was/were, there was/were, a/an, likes, can).
# ===========================================================================
WORLD = W("Places & Past", "Was/were & there was — Magic Academy Unit 10", [

    L("Don't Look at the Slime",
      [("school", "🏫"), ("park", "🏞️"), ("shop", "🏪"), ("bus", "🚌"), ("car", "🚗"), ("train", "🚆")],
      "Places & transport",
      ["This is a park.", "I go by bus.", "This is a school.", "I go by car.", "This is a shop.", "I go to the park."],
      [g("I go ___ bus.", ["by", "to"], "by", "🚌"),
       g("This is ___ park.", ["a", "an"], "a", "🏞️"),
       g("I go ___ school.", ["to", "by"], "to", "🏫"),
       g("This is ___ shop.", ["a", "an"], "a", "🏪")],
      [t("one bus -> many...?", "bus", ["buses", "buss", "bus"], "buses"),
       t("one car -> many...?", "car", ["cars", "cares", "car"], "cars"),
       t("one train -> many...?", "train", ["trains", "traines", "train"], "trains")],
      [f("This is a park.", "This is an park.", "🏞️"),
       f("I go to school.", "I go at school.", "🏫"),
       f("I go by car.", "I go by cars.", "🚗"),
       f("This is a shop.", "This is an shop.", "🏪")],
      srt("place", "transport",
          [tok("park", "A", "🏞️"), tok("school", "A", "🏫"), tok("shop", "A", "🏪"),
           tok("bus", "B", "🚌"), tok("car", "B", "🚗"), tok("train", "B", "🚆")]),
      [qa("Where do you go?", "I go to school."),
       qa("How do you go?", "I go by bus."),
       qa("Is this a park?", "Yes, it is."),
       qa("What is this?", "It is a shop.")]),

    L("The Shrinking Machine",
      [("school", "🏫"), ("park", "🏞️"), ("home", "🏠"), ("bus", "🚌"), ("car", "🚗"), ("train", "🚆")],
      "was / were",
      ["I was at school.", "They were at the park.", "He was at home.", "We were on the bus.", "She was in the car.", "You were at school."],
      [g("I ___ at school.", ["was", "were"], "was", "🏫"),
       g("They ___ at the park.", ["were", "was"], "were", "🏞️"),
       g("He ___ at home.", ["was", "were"], "was", "🏠"),
       g("We ___ on the bus.", ["were", "was"], "were", "🚌")],
      [t("I + be (past) ->", "I", ["was", "were", "am"], "was"),
       t("they + be (past) ->", "they", ["were", "was", "are"], "were"),
       t("he + be (past) ->", "he", ["was", "were", "is"], "was")],
      [f("I was at school.", "I were at school.", "🏫"),
       f("They were at the park.", "They was at the park.", "🏞️"),
       f("He was at home.", "He were at home.", "🏠"),
       f("We were on the bus.", "We was on the bus.", "🚌")],
      srt("was", "were",
          [tok("I", "A"), tok("he", "A"), tok("she", "A"),
           tok("you", "B"), tok("we", "B"), tok("they", "B")]),
      [qa("Where were you?", "I was at school."),
       qa("Where was he?", "He was at home."),
       qa("Where were they?", "They were at the park."),
       qa("Were you on the bus?", "Yes, I was.")]),

    L("Not There",
      [("bus", "🚌"), ("park", "🏞️"), ("home", "🏠"), ("shop", "🏪"), ("school", "🏫"), ("car", "🚗")],
      "wasn't / weren't",
      ["He wasn't on the bus.", "We weren't at home.", "I wasn't at school.", "They weren't at the park.", "She wasn't at the shop.", "You weren't in the car."],
      [g("He ___ on the bus.", ["wasn't", "weren't"], "wasn't", "🚌"),
       g("We ___ at home.", ["weren't", "wasn't"], "weren't", "🏠"),
       g("I ___ at school.", ["wasn't", "weren't"], "wasn't", "🏫"),
       g("They ___ at the park.", ["weren't", "wasn't"], "weren't", "🏞️")],
      [t("he + not (past) ->", "he", ["wasn't", "weren't", "isn't"], "wasn't"),
       t("we + not (past) ->", "we", ["weren't", "wasn't", "aren't"], "weren't"),
       t("they + not (past) ->", "they", ["weren't", "wasn't", "aren't"], "weren't")],
      [f("He wasn't on the bus.", "He weren't on the bus.", "🚌"),
       f("We weren't at home.", "We wasn't at home.", "🏠"),
       f("She wasn't at the shop.", "She weren't at the shop.", "🏪"),
       f("They weren't at the park.", "They wasn't at the park.", "🏞️")],
      srt("wasn't", "weren't",
          [tok("I", "A"), tok("he", "A"), tok("she", "A"),
           tok("you", "B"), tok("we", "B"), tok("they", "B")]),
      [qa("Was he on the bus?", "No, he wasn't."),
       qa("Were you at home?", "No, I wasn't."),
       qa("Were they at the park?", "No, they weren't."),
       qa("Was she at the shop?", "No, she wasn't.")]),

    L("The Slime Empire",
      [("school", "🏫"), ("park", "🏞️"), ("home", "🏠"), ("shop", "🏪"), ("bus", "🚌"), ("car", "🚗")],
      "Was / Were questions",
      ["Were you at school?", "Was he at home?", "Was she at the park?", "Were they on the bus?", "Were you in the car?", "Was I at the shop?"],
      [g("___ you at school?", ["Were", "Was"], "Were", "🏫"),
       g("___ he at home?", ["Was", "Were"], "Was", "🏠"),
       g("___ they on the bus?", ["Were", "Was"], "Were", "🚌"),
       g("___ she at the park?", ["Was", "Were"], "Was", "🏞️")],
      [t("ask: you ... ? ->", "you", ["Were", "Was", "Are"], "Were"),
       t("ask: he ... ? ->", "he", ["Was", "Were", "Is"], "Was"),
       t("ask: they ... ? ->", "they", ["Were", "Was", "Are"], "Were")],
      [f("Was he at home?", "Were he at home?", "🏠"),
       f("Were you at school?", "Was you at school?", "🏫"),
       f("Were they on the bus?", "Was they on the bus?", "🚌"),
       f("Was she at the park?", "Were she at the park?", "🏞️")],
      srt("Was ...?", "Were ...?",
          [tok("he", "A"), tok("she", "A"), tok("it", "A"),
           tok("you", "B"), tok("we", "B"), tok("they", "B")]),
      [qa("Were you at school?", "Yes, I was."),
       qa("Was he at home?", "No, he wasn't."),
       qa("Were they on the bus?", "Yes, they were."),
       qa("Was she at the park?", "No, she wasn't.")]),

    L("There Was a Slime",
      [("car", "🚗"), ("tree", "🌳"), ("bird", "🐦"), ("cloud", "☁️"), ("house", "🏠"), ("star", "⭐")],
      "There was / There were",
      ["There was a tree.", "There were three cars.", "There was a bird.", "There were two clouds.", "There was a house.", "There were many stars."],
      [g("There ___ a tree.", ["was", "were"], "was", "🌳"),
       g("There ___ three cars.", ["were", "was"], "were", "🚗"),
       g("There ___ a bird.", ["was", "were"], "was", "🐦"),
       g("There ___ two clouds.", ["were", "was"], "were", "☁️")],
      [t("one tree -> many...?", "tree", ["trees", "treees", "tree"], "trees"),
       t("one bird -> many...?", "bird", ["birds", "birdes", "bird"], "birds"),
       t("one star -> many...?", "star", ["stars", "stares", "star"], "stars")],
      [f("There was a tree.", "There were a tree.", "🌳"),
       f("There were three cars.", "There was three cars.", "🚗"),
       f("There was a bird.", "There were a bird.", "🐦"),
       f("There were two clouds.", "There was two clouds.", "☁️")],
      srt("There was", "There were",
          [tok("a tree", "A", "🌳"), tok("a bird", "A", "🐦"), tok("a house", "A", "🏠"),
           tok("two cars", "B", "🚗"), tok("three stars", "B", "⭐"), tok("many clouds", "B", "☁️")]),
      [qa("What was there?", "There was a tree."),
       qa("How many cars were there?", "There were three cars."),
       qa("Was there a bird?", "Yes, there was."),
       qa("Were there any stars?", "Yes, there were.")]),

    L("Giving Directions",
      [("left", "⬅️"), ("right", "➡️"), ("park", "🏞️"), ("shop", "🏪"), ("school", "🏫"), ("corner", "📍")],
      "Directions & prepositions",
      ["Turn left at the corner.", "It's next to the shop.", "Turn right at the shop.", "The park is near the school.", "It's on the corner.", "Go to the corner."],
      [g("Turn ___ (⬅️).", ["left", "right"], "left", "⬅️"),
       g("Turn ___ (➡️).", ["right", "left"], "right", "➡️"),
       g("The park is ___ the school.", ["near", "next"], "near", "🏫"),
       g("It's ___ the corner.", ["on", "in"], "on", "📍")],
      [t("one park -> many...?", "park", ["parks", "parkes", "park"], "parks"),
       t("one shop -> many...?", "shop", ["shops", "shopes", "shop"], "shops"),
       t("one corner -> many...?", "corner", ["corners", "corneres", "corner"], "corners")],
      [f("It's next to the shop.", "It's next at the shop.", "🏪"),
       f("Go to the corner.", "Go at the corner.", "📍"),
       f("The shop is on the left.", "The shop is in the left.", "⬅️")],
      srt("turn words", "position words",
          [tok("left", "A", "⬅️"), tok("right", "A", "➡️"), tok("straight", "A", "⬆️"),
           tok("next to", "B", "🏪"), tok("near", "B", "🏫"), tok("on the corner", "B", "📍")]),
      [qa("Where is the shop?", "It's next to the park."),
       qa("How do I get there?", "Turn left at the corner."),
       qa("Is the school near?", "Yes, it's very near."),
       qa("Is it on the left?", "No, it's on the right.")]),

    L("Yesterday",
      [("yesterday", "📅"), ("today", "📆"), ("morning", "🌅"), ("night", "🌙"), ("park", "🏞️"), ("home", "🏠")],
      "Past time words",
      ["Yesterday I was at the park.", "Last night I was at home.", "Last week we were at school.", "This morning I was at home.", "Yesterday she was at the shop."],
      [g("Yesterday I ___ at the park.", ["was", "were"], "was", "🏞️"),
       g("Last night we ___ at home.", ["were", "was"], "were", "🏠"),
       g("___ I was at home.", ["Yesterday", "Tomorrow"], "Yesterday", "📅"),
       g("___ night I was at home.", ["Last", "Next"], "Last", "🌙")],
      [t("one morning -> many...?", "morning", ["mornings", "morninges", "morning"], "mornings"),
       t("one night -> many...?", "night", ["nights", "nightes", "night"], "nights"),
       t("one park -> many...?", "park", ["parks", "parkes", "park"], "parks")],
      [f("Yesterday I was at the park.", "Yesterday I were at the park.", "🏞️"),
       f("Last night I was at home.", "Last night I were at home.", "🏠"),
       f("Last week we were at school.", "Last week we was at school.", "🏫"),
       f("Yesterday she was at the shop.", "Yesterday she were at the shop.", "🏪")],
      srt("past time", "not past",
          [tok("yesterday", "A", "📅"), tok("last night", "A", "🌙"), tok("last week", "A", "📆"),
           tok("today", "B", "📆"), tok("tonight", "B", "🌃"), tok("tomorrow", "B", "🌅")]),
      [qa("Where were you yesterday?", "Yesterday I was at the park."),
       qa("Where were you last night?", "Last night I was at home."),
       qa("Where were you last week?", "Last week I was at school."),
       qa("Were you at home this morning?", "Yes, I was.")]),

    L("Novus Comes to Help",
      [("hero", "🦸"), ("robot", "🤖"), ("park", "🏞️"), ("school", "🏫"), ("home", "🏠"), ("shop", "🏪")],
      "was / were with places",
      ["The hero was at school.", "The robot was in the park.", "The heroes were at home.", "We were at the shop.", "Novus the robot was at home."],
      [g("The hero ___ at school.", ["was", "were"], "was", "🏫"),
       g("The robot ___ in the park.", ["was", "were"], "was", "🤖"),
       g("The heroes ___ at home.", ["were", "was"], "were", "🦸"),
       g("We ___ at the shop.", ["were", "was"], "were", "🏪")],
      [t("one hero -> many...?", "hero", ["heroes", "heros", "hero"], "heroes"),
       t("one robot -> many...?", "robot", ["robots", "robotes", "robot"], "robots"),
       t("one shop -> many...?", "shop", ["shops", "shopes", "shop"], "shops")],
      [f("The hero was at school.", "The hero were at school.", "🏫"),
       f("The heroes were at home.", "The heroes was at home.", "🦸"),
       f("The robot was in the park.", "The robot were in the park.", "🤖"),
       f("We were at the shop.", "We was at the shop.", "🏪")],
      srt("was", "were",
          [tok("the hero", "A", "🦸"), tok("the robot", "A", "🤖"), tok("she", "A"),
           tok("the heroes", "B", "🦸"), tok("the robots", "B", "🤖"), tok("we", "B")]),
      [qa("Where was the hero?", "The hero was at school."),
       qa("Where was the robot?", "The robot was in the park."),
       qa("Where were the heroes?", "The heroes were at home."),
       qa("Was Novus at home?", "Yes, he was.")]),

    L("Sound Lab: str/nch blends",
      [("lunch", "🍱"), ("bench", "🪑"), ("strong", "💪"), ("string", "🧵"), ("street", "🛣️"), ("strap", "🔗")],
      "reading: str / nch",
      ["I eat my lunch.", "Sit on the bench.", "He is very strong.", "This is a long string.", "We walk down the street."],
      [g("I eat my ___.", ["lunch", "bench"], "lunch", "🍱"),
       g("Sit on the ___.", ["bench", "lunch"], "bench", "🪑"),
       g("He is very ___.", ["strong", "string"], "strong", "💪"),
       g("We walk down the ___.", ["street", "strap"], "street", "🛣️")],
      [t("one lunch -> many...?", "lunch", ["lunches", "lunchs", "lunch"], "lunches"),
       t("one bench -> many...?", "bench", ["benches", "benchs", "bench"], "benches"),
       t("one street -> many...?", "street", ["streets", "streetes", "street"], "streets")],
      [f("I eat my lunch.", "I eat my launch.", "🍱"),
       f("Sit on the bench.", "Sit on the bunch.", "🪑"),
       f("He is very strong.", "He is very strung.", "💪"),
       f("We walk down the street.", "We walk down the streat.", "🛣️")],
      srt("str-", "-nch",
          [tok("strong", "A", "💪"), tok("string", "A", "🧵"), tok("street", "A", "🛣️"),
           tok("lunch", "B", "🍱"), tok("bench", "B", "🪑"), tok("branch", "B", "🌿")]),
      [qa("What do you eat?", "I eat my lunch."),
       qa("Where do you sit?", "I sit on the bench."),
       qa("Is he strong?", "Yes, he is very strong."),
       qa("What starts with 'str'?", "Street starts with 'str'.")]),

    L("Grand Grammar Finale",
      [("park", "🏞️"), ("home", "🏠"), ("apple", "🍎"), ("robot", "🤖"), ("star", "⭐"), ("bus", "🚌")],
      "Unit 10 review",
      ["I was at the park.", "There were three stars.", "This is an apple.", "She likes the robot.", "He can run fast.", "We were at home."],
      [g("I ___ at the park.", ["was", "were"], "was", "🏞️"),
       g("There ___ three stars.", ["were", "was"], "were", "⭐"),
       g("This is ___ apple.", ["an", "a"], "an", "🍎"),
       g("She ___ the robot.", ["likes", "like"], "likes", "🤖")],
      [t("she + like ->", "like", ["likes", "likez", "like"], "likes"),
       t("one apple -> many...?", "apple", ["apples", "appls", "apple"], "apples"),
       t("they + be (past) ->", "they", ["were", "was", "are"], "were")],
      [f("I was at the park.", "I were at the park.", "🏞️"),
       f("There were three stars.", "There was three stars.", "⭐"),
       f("This is an apple.", "This is a apple.", "🍎"),
       f("She likes the robot.", "She like the robot.", "🤖")],
      srt("was", "were",
          [tok("I", "A"), tok("he", "A"), tok("she", "A"),
           tok("you", "B"), tok("we", "B"), tok("they", "B")]),
      [qa("Where were you?", "I was at the park."),
       qa("How many stars were there?", "There were three stars."),
       qa("Is this an apple?", "Yes, it is."),
       qa("Can he run fast?", "Yes, he can.")]),
])
