# -*- coding: utf-8 -*-
# ===========================================================================
# WORLD 11 — Tense Trek  (advanced: verb tenses across time)
# Grammar arc: present simple vs continuous, past simple (regular + irregular),
# past continuous, present/past perfect, future (will / going to),
# present + past perfect continuous. Slightly older learners.
# ===========================================================================
from grammar_helpers import g, t, f, tok, srt, qa, L, W

WORLD = W("Tense Trek", "Verb tenses across time", [

    L("Every Day or Right Now?",
      [("play", "⚽"), ("eat", "🍎"), ("read", "📖"), ("run", "🏃"), ("swim", "🏊"), ("sleep", "😴")],
      "every day vs right now",
      ["I play soccer every day.", "I am playing now.", "She reads every day.",
       "She is reading now.", "We swim on Sundays.", "Look! He is running."],
      [g("I ___ soccer every day.", ["play", "am playing"], "play", "⚽"),
       g("Look! I ___ now.", ["am playing", "play"], "am playing", "🎮"),
       g("She ___ every day.", ["reads", "is reading"], "reads", "📖"),
       g("Look! She ___ now.", ["is reading", "reads"], "is reading", "📖")],
      [t("play + -ing ->", "play", ["playing", "plaing", "playeing"], "playing"),
       t("run + -ing ->", "run", ["runing", "running", "runnig"], "running"),
       t("swim + -ing ->", "swim", ["swiming", "swimming", "swimmng"], "swimming")],
      [f("She is reading now.", "She is read now.", "📖"),
       f("They are playing now.", "They are play now.", "⚽"),
       f("He is running now.", "He is run now.", "🏃")],
      srt("every day", "right now",
          [tok("I play", "A", "⚽"), tok("she reads", "A", "📖"), tok("they run", "A", "🏃"),
           tok("I am playing", "B", "⚽"), tok("she is reading", "B", "📖"), tok("they are running", "B", "🏃")]),
      [qa("What do you do every day?", "I play soccer."),
       qa("What are you doing now?", "I am reading."),
       qa("Is she playing now?", "Yes, she is."),
       qa("Do you read every day?", "Yes, I do.")]),

    L("Yesterday: Add -ed",
      [("play", "⚽"), ("cook", "🍳"), ("clean", "🧹"), ("help", "🤝"), ("watch", "📺"), ("walk", "🚶")],
      "Past simple (-ed)",
      ["Yesterday I played.", "She cooked dinner.", "We cleaned the room.",
       "He helped me.", "They watched a movie.", "I walked to school."],
      [g("Yesterday I ___ soccer.", ["played", "play"], "played", "⚽"),
       g("Last night she ___ dinner.", ["cooked", "cook"], "cooked", "🍳"),
       g("We ___ the room.", ["cleaned", "clean"], "cleaned", "🧹"),
       g("He ___ me yesterday.", ["helped", "help"], "helped", "🤝")],
      [t("play ->", "play", ["played", "plaid", "playd"], "played"),
       t("cook ->", "cook", ["cookd", "cooked", "cookt"], "cooked"),
       t("clean ->", "clean", ["cleaned", "cleand", "cleant"], "cleaned")],
      [f("Yesterday I played.", "Yesterday I play.", "⚽"),
       f("She cooked dinner.", "She cook dinner.", "🍳"),
       f("We cleaned the room.", "We clean the room.", "🧹")],
      srt("today", "yesterday",
          [tok("play", "A", "⚽"), tok("cook", "A", "🍳"), tok("help", "A", "🤝"),
           tok("played", "B", "⚽"), tok("cooked", "B", "🍳"), tok("helped", "B", "🤝")]),
      [qa("What did you do yesterday?", "I played soccer."),
       qa("Did she cook dinner?", "Yes, she did."),
       qa("Who helped you?", "My friend helped me."),
       qa("Where did you walk?", "I walked to school.")]),

    L("Yesterday: Tricky Verbs",
      [("go", "🏃"), ("eat", "🍎"), ("see", "👀"), ("have", "📦"), ("make", "🎨"), ("take", "🤲")],
      "Past simple (irregular)",
      ["I went to school.", "She ate an apple.", "We saw a bird.",
       "He had a dog.", "They made a cake.", "I took my bag."],
      [g("I ___ to school.", ["went", "goed"], "went", "🏃"),
       g("She ___ an apple.", ["ate", "eated"], "ate", "🍎"),
       g("We ___ a bird.", ["saw", "seed"], "saw", "👀"),
       g("They ___ a cake.", ["made", "maked"], "made", "🎨")],
      [t("go ->", "go", ["goed", "went", "gone"], "went"),
       t("eat ->", "eat", ["ate", "eated", "eaten"], "ate"),
       t("see ->", "see", ["seed", "saw", "seen"], "saw")],
      [f("I went to school.", "I goed to school.", "🏃"),
       f("She ate an apple.", "She eated an apple.", "🍎"),
       f("We saw a bird.", "We seed a bird.", "👀")],
      srt("base", "past",
          [tok("go", "A", "🏃"), tok("eat", "A", "🍎"), tok("see", "A", "👀"),
           tok("went", "B", "🏃"), tok("ate", "B", "🍎"), tok("saw", "B", "👀")]),
      [qa("Where did you go?", "I went to school."),
       qa("What did she eat?", "She ate an apple."),
       qa("Did you see the bird?", "Yes, I did."),
       qa("What did they make?", "They made a cake.")]),

    L("It Was Happening",
      [("read", "📖"), ("play", "⚽"), ("sleep", "😴"), ("cook", "🍳"), ("write", "✍️"), ("sing", "🎤")],
      "Past continuous (was/were + -ing)",
      ["I was reading.", "They were playing.", "She was cooking.",
       "We were singing.", "He was sleeping.", "You were writing."],
      [g("I ___ reading.", ["was", "were"], "was", "📖"),
       g("They ___ playing.", ["were", "was"], "were", "⚽"),
       g("She was ___.", ["cooking", "cooked"], "cooking", "🍳"),
       g("We ___ singing.", ["were", "was"], "were", "🎤")],
      [t("read + -ing ->", "read", ["reading", "readding", "readeing"], "reading"),
       t("sleep + -ing ->", "sleep", ["sleepping", "sleeping", "sleepng"], "sleeping"),
       t("write + -ing ->", "write", ["writeing", "writing", "writting"], "writing")],
      [f("I was reading.", "I were reading.", "📖"),
       f("They were playing.", "They was playing.", "⚽"),
       f("She was cooking.", "She was cook.", "🍳")],
      srt("was", "were",
          [tok("I", "A", "🙋"), tok("she", "A", "👧"), tok("he", "A", "👦"),
           tok("we", "B", "👨‍👩‍👧"), tok("they", "B", "👫"), tok("you", "B", "🫵")]),
      [qa("What were you doing?", "I was reading."),
       qa("Were they playing?", "Yes, they were."),
       qa("Was she cooking?", "Yes, she was."),
       qa("What were they doing?", "They were singing.")]),

    L("Already Done",
      [("finish", "🏁"), ("eat", "🍎"), ("see", "👀"), ("go", "🚪"), ("leave", "👋"), ("make", "🎨")],
      "Present perfect (have/has + done)",
      ["I have finished.", "She has eaten.", "They have gone home.",
       "He has just left.", "We have seen it.", "I have already eaten."],
      [g("I ___ finished.", ["have", "has"], "have", "🏁"),
       g("She ___ eaten.", ["has", "have"], "has", "🍎"),
       g("They ___ gone home.", ["have", "has"], "have", "🚪"),
       g("She has ___ it.", ["seen", "saw"], "seen", "👀")],
      [t("eat ->", "eat", ["eaten", "eated", "ate"], "eaten"),
       t("see ->", "see", ["seed", "seen", "saw"], "seen"),
       t("go ->", "go", ["goed", "gone", "went"], "gone")],
      [f("She has eaten.", "She have eaten.", "🍎"),
       f("I have finished.", "I has finished.", "🏁"),
       f("They have gone home.", "They has gone home.", "🚪")],
      srt("have", "has",
          [tok("I", "A", "🙋"), tok("we", "A", "👨‍👩‍👧"), tok("they", "A", "👫"),
           tok("she", "B", "👧"), tok("he", "B", "👦"), tok("it", "B", "🐱")]),
      [qa("Have you finished?", "Yes, I have."),
       qa("Has she eaten?", "Yes, she has."),
       qa("Have they gone home?", "Yes, they have."),
       qa("What have you done?", "I have finished my work.")]),

    L("Done Before",
      [("eat", "🍎"), ("go", "🚪"), ("finish", "🏁"), ("leave", "👋"), ("see", "👀"), ("make", "🎨")],
      "Past perfect (had + done)",
      ["I had eaten before school.", "They had gone home.", "She had finished her work.",
       "We had seen the film.", "He had left early.", "I had made lunch."],
      [g("I ___ eaten before school.", ["had", "have"], "had", "🍎"),
       g("They ___ gone home.", ["had", "has"], "had", "🚪"),
       g("She had ___ her work.", ["finished", "finish"], "finished", "🏁"),
       g("We had ___ the film.", ["seen", "saw"], "seen", "👀")],
      [t("eat ->", "eat", ["ate", "eaten", "eated"], "eaten"),
       t("go ->", "go", ["gone", "went", "goed"], "gone"),
       t("see ->", "see", ["saw", "seen", "seed"], "seen")],
      [f("She had finished her work.", "She had finish her work.", "🏁"),
       f("They had gone home.", "They had go home.", "🚪"),
       f("We had seen the film.", "We had saw the film.", "👀")],
      srt("past simple", "past perfect",
          [tok("I ate", "A", "🍎"), tok("they went", "A", "🚪"), tok("she saw", "A", "👀"),
           tok("I had eaten", "B", "🍎"), tok("they had gone", "B", "🚪"), tok("she had seen", "B", "👀")]),
      [qa("Had you eaten before school?", "Yes, I had."),
       qa("What had they done?", "They had gone home."),
       qa("Had she finished her work?", "Yes, she had."),
       qa("Where had he gone?", "He had left for home.")]),

    L("It Will Happen",
      [("help", "🤝"), ("rain", "🌧️"), ("come", "👋"), ("go", "🚪"), ("play", "⚽"), ("win", "🏆")],
      "Future with will",
      ["I will help you.", "It will rain.", "They will come soon.",
       "She will win.", "We will play later.", "He will go home."],
      [g("I will ___ you.", ["help", "helps"], "help", "🤝"),
       g("It will ___.", ["rain", "rains"], "rain", "🌧️"),
       g("They ___ come soon.", ["will", "wills"], "will", "👋"),
       g("She will ___.", ["win", "wins"], "win", "🏆")],
      [t("will + help ->", "help", ["will help", "will helps", "will to help"], "will help"),
       t("will + go ->", "go", ["will goes", "will to go", "will go"], "will go"),
       t("will + rain ->", "rain", ["will rain", "will rains", "will to rain"], "will rain")],
      [f("I will help you.", "I will helps you.", "🤝"),
       f("It will rain.", "It will rains.", "🌧️"),
       f("She will win.", "She will wins.", "🏆")],
      srt("now", "later (will)",
          [tok("I help", "A", "🤝"), tok("it rains", "A", "🌧️"), tok("she wins", "A", "🏆"),
           tok("I will help", "B", "🤝"), tok("it will rain", "B", "🌧️"), tok("she will win", "B", "🏆")]),
      [qa("Will you help me?", "Yes, I will."),
       qa("Will it rain today?", "No, it will not."),
       qa("Who will win?", "Our team will win."),
       qa("Will they come soon?", "Yes, they will.")]),

    L("I'm Going To",
      [("travel", "✈️"), ("cook", "🍳"), ("play", "⚽"), ("visit", "🏠"), ("study", "📚"), ("help", "🤝")],
      "Going to (future plan)",
      ["I am going to travel.", "She is going to cook.", "They are going to play.",
       "We are going to study.", "He is going to help.", "I am going to visit."],
      [g("I ___ going to travel.", ["am", "is"], "am", "✈️"),
       g("She ___ going to cook.", ["is", "are"], "is", "🍳"),
       g("They ___ going to play.", ["are", "is"], "are", "⚽"),
       g("We ___ going to study.", ["are", "am"], "are", "📚")],
      [t("I ... going to travel", "I", ["am", "is", "are"], "am"),
       t("she ... going to cook", "she", ["is", "am", "are"], "is"),
       t("they ... going to play", "they", ["are", "is", "am"], "are")],
      [f("I am going to travel.", "I is going to travel.", "✈️"),
       f("She is going to cook.", "She are going to cook.", "🍳"),
       f("They are going to play.", "They is going to play.", "⚽")],
      srt("is going to", "are going to",
          [tok("she", "A", "👧"), tok("he", "A", "👦"), tok("it", "A", "🐱"),
           tok("we", "B", "👨‍👩‍👧"), tok("they", "B", "👫"), tok("you", "B", "🫵")]),
      [qa("What are you going to do?", "I am going to travel."),
       qa("Is she going to cook?", "Yes, she is."),
       qa("Are they going to play?", "Yes, they are."),
       qa("What is he going to do?", "He is going to help.")]),

    L("Been Doing It",
      [("read", "📖"), ("work", "💼"), ("play", "⚽"), ("wait", "⏳"), ("run", "🏃"), ("study", "📚")],
      "Present perfect continuous (have been + -ing)",
      ["I have been reading.", "She has been working.", "They have been playing.",
       "We have been waiting.", "He has been running.", "I have been studying."],
      [g("I ___ been reading.", ["have", "has"], "have", "📖"),
       g("She ___ been working.", ["has", "have"], "has", "💼"),
       g("They have ___ playing.", ["been", "being"], "been", "⚽"),
       g("He ___ been running.", ["has", "have"], "has", "🏃")],
      [t("read + -ing ->", "read", ["reading", "readding", "readeing"], "reading"),
       t("run + -ing ->", "run", ["runing", "running", "runnng"], "running"),
       t("study + -ing ->", "study", ["studing", "studying", "studdying"], "studying")],
      [f("She has been working.", "She have been working.", "💼"),
       f("I have been reading.", "I has been reading.", "📖"),
       f("They have been playing.", "They have been play.", "⚽")],
      srt("have been", "has been",
          [tok("I", "A", "🙋"), tok("we", "A", "👨‍👩‍👧"), tok("they", "A", "👫"),
           tok("she", "B", "👧"), tok("he", "B", "👦"), tok("it", "B", "🐱")]),
      [qa("What have you been doing?", "I have been reading."),
       qa("Has she been working?", "Yes, she has."),
       qa("Have they been playing?", "Yes, they have."),
       qa("How long have you been waiting?", "For ten minutes.")]),

    L("Had Been Doing It",
      [("play", "⚽"), ("wait", "⏳"), ("read", "📖"), ("work", "💼"), ("run", "🏃"), ("sleep", "😴")],
      "Past perfect continuous (had been + -ing)",
      ["They had been playing.", "I had been waiting.", "She had been reading.",
       "We had been working.", "He had been running.", "You had been sleeping."],
      [g("They ___ been playing.", ["had", "have"], "had", "⚽"),
       g("I had ___ waiting.", ["been", "being"], "been", "⏳"),
       g("She ___ been reading.", ["had", "has"], "had", "📖"),
       g("We had been ___.", ["working", "worked"], "working", "💼")],
      [t("play + -ing ->", "play", ["playing", "plaing", "playeing"], "playing"),
       t("wait + -ing ->", "wait", ["waiting", "waitting", "waitng"], "waiting"),
       t("run + -ing ->", "run", ["running", "runing", "runnng"], "running")],
      [f("They had been playing.", "They has been playing.", "⚽"),
       f("I had been waiting.", "I had been wait.", "⏳"),
       f("She had been reading.", "She had been read.", "📖")],
      srt("have been", "had been",
          [tok("I have been", "A", "🙋"), tok("she has been", "A", "👧"), tok("they have been", "A", "👫"),
           tok("I had been", "B", "🙋"), tok("she had been", "B", "👧"), tok("they had been", "B", "👫")]),
      [qa("What had they been doing?", "They had been playing."),
       qa("How long had you been waiting?", "For an hour."),
       qa("Had she been reading?", "Yes, she had."),
       qa("Had you been sleeping?", "No, I had not.")]),
])
