# -*- coding: utf-8 -*-
# ===========================================================================
# WORLD 12 — Modal Mountain  (Levels 111-120)
# Grammar arc: modal verbs. After a modal (can, could, may, might, must,
# should, will, would) the main verb is the BASE form (no -s, no -ing, no
# "to"). Modals themselves never add -s (he can, she should). "have to" and
# "used to" DO take "to" + base verb.
# ===========================================================================
from grammar_helpers import g, t, f, tok, srt, qa, L, W

WORLD = W("Modal Mountain", "Modal verbs: can, must, should...", [

    L("Ability: can / could",
      [("can", "💪"), ("could", "💭"), ("swim", "🏊"), ("run", "🏃"), ("read", "📖"), ("ride", "🚲")],
      "can (now) / could (past)",
      ["I can swim now.", "I could swim last year.", "She can run fast.",
       "He could read at five.", "We can ride bikes."],
      [g("I ___ swim now.", ["can", "could"], "can", "🏊"),
       g("I ___ swim last year.", ["could", "can"], "could", "🏊"),
       g("She can ___ fast.", ["run", "runs"], "run", "🏃"),
       g("He can ___ a bike.", ["ride", "rides"], "ride", "🚲")],
      [t("She can (run) ->", "run", ["run", "runs", "running"], "run"),
       t("I can (swim) ->", "swim", ["swims", "swim", "swimming"], "swim"),
       t("He could (read) ->", "read", ["reads", "reading", "read"], "read")],
      [f("She can run fast.", "She can runs fast.", "🏃"),
       f("I can swim now.", "I can swims now.", "🏊"),
       f("He could read at five.", "He could reads at five.", "📖"),
       f("We can ride bikes.", "We can rides bikes.", "🚲")],
      srt("can (now)", "could (past)",
          [tok("I can swim now", "A", "🏊"), tok("She can run now", "A", "🏃"), tok("We can read today", "A", "📖"),
           tok("I could swim then", "B", "🏊"), tok("She could run then", "B", "🏃"), tok("We could read last year", "B", "📖")]),
      [qa("Can you swim?", "Yes, I can."),
       qa("Could you swim last year?", "No, I could not."),
       qa("What can she do?", "She can run fast."),
       qa("Can he ride a bike?", "Yes, he can.")]),

    L("Possibility: may / might",
      [("may", "🤔"), ("might", "🤷"), ("rain", "🌧️"), ("snow", "❄️"), ("come", "👋"), ("help", "🤝")],
      "may / might (maybe)",
      ["It may rain today.", "She might come later.", "It might snow tonight.",
       "He may help us.", "They might be late."],
      [g("It may ___ today.", ["rain", "rains"], "rain", "🌧️"),
       g("She might ___ later.", ["come", "comes"], "come", "👋"),
       g("It ___ snow tonight.", ["might", "mights"], "might", "❄️"),
       g("He may ___ us.", ["help", "helps"], "help", "🤝")],
      [t("It may (rain) ->", "rain", ["rains", "rain", "raining"], "rain"),
       t("She might (come) ->", "come", ["comes", "coming", "come"], "come"),
       t("He may (help) ->", "help", ["helps", "help", "helping"], "help")],
      [f("It may rain today.", "It may rains today.", "🌧️"),
       f("She might come later.", "She might comes later.", "👋"),
       f("It might snow tonight.", "It might snows tonight.", "❄️"),
       f("He may help us.", "He may helps us.", "🤝")],
      srt("sure", "maybe",
          [tok("She is here", "A", "✅"), tok("It is sunny", "A", "☀️"), tok("I am ready", "A", "👍"),
           tok("It might rain", "B", "🌧️"), tok("She may come", "B", "👋"), tok("He might help", "B", "🤝")]),
      [qa("Will it rain?", "It might rain."),
       qa("Is she coming?", "She may come later."),
       qa("Will he help?", "He might help us."),
       qa("Is it going to snow?", "It might snow.")]),

    L("Obligation: must / have to",
      [("must", "❗"), ("stop", "🛑"), ("study", "📚"), ("wait", "⏳"), ("wear", "🧢"), ("help", "🤝")],
      "must / have to (necessary)",
      ["You must stop now.", "I have to study today.", "We must wait here.",
       "She has to help us.", "You must wear a coat."],
      [g("You ___ stop now.", ["must", "musts"], "must", "🛑"),
       g("I ___ study today.", ["have to", "has to"], "have to", "📚"),
       g("She ___ help us.", ["has to", "have to"], "has to", "🤝"),
       g("You must ___ a coat.", ["wear", "wears"], "wear", "🧢")],
      [t("You must (stop) ->", "stop", ["stops", "stop", "stopping"], "stop"),
       t("We must (wait) ->", "wait", ["waits", "waiting", "wait"], "wait"),
       t("You must (wear) ->", "wear", ["wears", "wear", "wearing"], "wear")],
      [f("You must stop now.", "You must stops now.", "🛑"),
       f("I have to study today.", "I have to studies today.", "📚"),
       f("We must wait here.", "We must waits here.", "⏳"),
       f("She has to help us.", "She have to help us.", "🤝")],
      srt("must + verb", "have to + verb",
          [tok("must stop", "A", "🛑"), tok("must wait", "A", "⏳"), tok("must wear", "A", "🧢"),
           tok("have to study", "B", "📚"), tok("have to help", "B", "🤝"), tok("have to go", "B", "🚪")]),
      [qa("What must I do?", "You must stop."),
       qa("Do I have to study?", "Yes, you have to."),
       qa("Must we wait?", "Yes, you must."),
       qa("Does she have to help?", "Yes, she has to.")]),

    L("Advice: should / ought to",
      [("should", "👍"), ("rest", "😴"), ("drink", "🥤"), ("water", "💧"), ("sleep", "🛌"), ("eat", "🍎")],
      "should (good idea)",
      ["You should rest now.", "You should drink water.", "She should sleep more.",
       "We should eat well.", "He should study hard."],
      [g("You ___ rest now.", ["should", "shoulds"], "should", "😴"),
       g("You should ___ water.", ["drink", "drinks"], "drink", "💧"),
       g("She should ___ more.", ["sleep", "sleeps"], "sleep", "🛌"),
       g("We should ___ well.", ["eat", "eats"], "eat", "🍎")],
      [t("You should (rest) ->", "rest", ["rests", "rest", "resting"], "rest"),
       t("She should (drink) ->", "drink", ["drinks", "drinking", "drink"], "drink"),
       t("We should (eat) ->", "eat", ["eats", "eat", "eating"], "eat")],
      [f("You should rest now.", "You should rests now.", "😴"),
       f("You should drink water.", "You should drinks water.", "💧"),
       f("She should sleep more.", "She should sleeps more.", "🛌"),
       f("We should eat well.", "We should eats well.", "🍎")],
      srt("should", "should not",
          [tok("eat fruit", "A", "🍎"), tok("drink water", "A", "💧"), tok("get sleep", "A", "🛌"),
           tok("skip meals", "B", "🍽️"), tok("stay up late", "B", "🌙"), tok("eat candy", "B", "🍬")]),
      [qa("I am tired.", "You should rest."),
       qa("I am thirsty.", "You should drink water."),
       qa("Should I sleep more?", "Yes, you should."),
       qa("What should I eat?", "You should eat fruit.")]),

    L("Habits & past: would / used to",
      [("used", "📅"), ("would", "🕰️"), ("play", "⚽"), ("visit", "🏡"), ("walk", "🚶"), ("ride", "🚲")],
      "used to / would (past habit)",
      ["I used to play there.", "We would visit grandma.", "She used to walk to school.",
       "They would play all day.", "He used to ride a bike."],
      [g("I used to ___ there.", ["play", "played"], "play", "⚽"),
       g("We ___ visit grandma.", ["would", "will"], "would", "🏡"),
       g("She used to ___ to school.", ["walk", "walked"], "walk", "🚶"),
       g("He used to ___ a bike.", ["ride", "rode"], "ride", "🚲")],
      [t("I used to (play) ->", "play", ["played", "play", "playing"], "play"),
       t("She used to (walk) ->", "walk", ["walked", "walking", "walk"], "walk"),
       t("We would (visit) ->", "visit", ["visited", "visit", "visiting"], "visit")],
      [f("I used to play there.", "I used to played there.", "⚽"),
       f("We would visit grandma.", "We would visited grandma.", "🏡"),
       f("She used to walk far.", "She used to walked far.", "🚶"),
       f("They would play all day.", "They would played all day.", "⚽")],
      srt("now", "used to (past)",
          [tok("I play now", "A", "⚽"), tok("I walk now", "A", "🚶"), tok("I ride now", "A", "🚲"),
           tok("I used to play", "B", "⚽"), tok("I used to walk", "B", "🚶"), tok("I used to ride", "B", "🚲")]),
      [qa("Did you play here?", "I used to play here."),
       qa("Where did you walk?", "I used to walk to school."),
       qa("Did you visit grandma?", "Yes, we would visit her."),
       qa("What did you ride?", "I used to ride a bike.")]),

    L("Permission & requests",
      [("can", "🙋"), ("may", "🤚"), ("could", "💭"), ("water", "💧"), ("help", "🤝"), ("please", "🙏")],
      "Can I / May I / Could you",
      ["May I go now?", "Can I have some water?", "Could you help me?",
       "Can I come in?", "Could you please wait?"],
      [g("___ I go now?", ["May", "Mays"], "May", "🤚"),
       g("Can I ___ some water?", ["have", "has"], "have", "💧"),
       g("Could you ___ me?", ["help", "helps"], "help", "🤝"),
       g("___ I come in?", ["Can", "Cans"], "Can", "🙋")],
      [t("Can I (have) ->", "have", ["has", "have", "having"], "have"),
       t("May I (go) ->", "go", ["goes", "going", "go"], "go"),
       t("Could you (help) ->", "help", ["helps", "help", "helping"], "help")],
      [f("May I go now?", "May I goes now?", "🚪"),
       f("Can I have water?", "Can I has water?", "💧"),
       f("Could you help me?", "Could you helps me?", "🤝"),
       f("Can I come in?", "Can I comes in?", "🙋")],
      srt("ask for me", "ask someone",
          [tok("May I go?", "A", "🤚"), tok("Can I come in?", "A", "🙋"), tok("Can I have water?", "A", "💧"),
           tok("Could you help?", "B", "🤝"), tok("Can you wait?", "B", "⏳"), tok("Could you come?", "B", "👋")]),
      [qa("May I go?", "Yes, you may."),
       qa("Can I have some water?", "Of course."),
       qa("Could you help me?", "Sure, I can."),
       qa("Can I come in?", "Yes, please do.")]),

    L("Necessity & no necessity",
      [("must", "❗"), ("helmet", "⛑️"), ("wear", "🧢"), ("come", "👋"), ("need", "🤔"), ("stay", "🏠")],
      "must vs don't have to",
      ["You must wear a helmet.", "You don't have to come.", "We must stay here.",
       "You don't have to wait.", "She must wear a coat."],
      [g("You ___ wear a helmet.", ["must", "musts"], "must", "⛑️"),
       g("You don't ___ to come.", ["have", "has"], "have", "👋"),
       g("We must ___ here.", ["stay", "stays"], "stay", "🏠"),
       g("You must ___ a coat.", ["wear", "wears"], "wear", "🧢")],
      [t("You must (wear) ->", "wear", ["wears", "wear", "wearing"], "wear"),
       t("We must (stay) ->", "stay", ["stays", "staying", "stay"], "stay"),
       t("You must (come) ->", "come", ["comes", "come", "coming"], "come")],
      [f("You must wear a helmet.", "You must wears a helmet.", "⛑️"),
       f("You don't have to come.", "You don't have to comes.", "👋"),
       f("We must stay here.", "We must stays here.", "🏠"),
       f("You don't have to wait.", "You don't has to wait.", "⏳")],
      srt("you must", "you don't have to",
          [tok("wear a helmet", "A", "⛑️"), tok("stop at red", "A", "🛑"), tok("stay in line", "A", "🚸"),
           tok("come early", "B", "👋"), tok("bring a gift", "B", "🎁"), tok("wait outside", "B", "⏳")]),
      [qa("Must I wear a helmet?", "Yes, you must."),
       qa("Do I have to come?", "No, you don't have to."),
       qa("Do I need to wait?", "No, you needn't."),
       qa("Must we stay here?", "Yes, you have to.")]),

    L("Polite obligation vs orders",
      [("please", "🙏"), ("could", "💭"), ("wait", "⏳"), ("help", "🤝"), ("stop", "🛑"), ("sit", "🪑")],
      "Could you please... vs Wait!",
      ["Could you please wait?", "Please sit down.", "Would you please help?",
       "Please stop now.", "Could you help me?"],
      [g("Could you please ___?", ["wait", "waits"], "wait", "⏳"),
       g("Please ___ down.", ["sit", "sits"], "sit", "🪑"),
       g("Could you ___ me?", ["help", "helps"], "help", "🤝"),
       g("Please ___ now.", ["stop", "stops"], "stop", "🛑")],
      [t("Could you (wait) ->", "wait", ["waits", "wait", "waiting"], "wait"),
       t("Please (sit) ->", "sit", ["sits", "sitting", "sit"], "sit"),
       t("Could you (help) ->", "help", ["helps", "help", "helping"], "help")],
      [f("Could you please wait?", "Could you please waits?", "⏳"),
       f("Please sit down.", "Please sits down.", "🪑"),
       f("Could you help me?", "Could you helps me?", "🤝"),
       f("Please stop now.", "Please stops now.", "🛑")],
      srt("polite", "order",
          [tok("Could you wait?", "A", "⏳"), tok("Could you help?", "A", "🤝"), tok("Would you sit?", "A", "🪑"),
           tok("Wait!", "B", "⏳"), tok("Help me!", "B", "🤝"), tok("Sit down!", "B", "🪑")]),
      [qa("Could you please wait?", "Yes, of course."),
       qa("Could you help me?", "Sure, I can."),
       qa("Would you please sit down?", "Yes, I will."),
       qa("Can you please stop?", "Okay, I will stop.")]),

    L("Modal questions & short answers",
      [("can", "🙋"), ("should", "👍"), ("swim", "🏊"), ("help", "🤝"), ("wait", "⏳"), ("come", "👋")],
      "Can you...? Should I...?",
      ["Can you swim?", "Should I wait here?", "Can you help me?",
       "Should we come now?", "Can she swim well?"],
      [g("Can you ___?", ["swim", "swims"], "swim", "🏊"),
       g("Should I ___ here?", ["wait", "waits"], "wait", "⏳"),
       g("Can you ___ me?", ["help", "helps"], "help", "🤝"),
       g("___ we come now?", ["Should", "Shoulds"], "Should", "👋")],
      [t("Can you (swim) ->", "swim", ["swims", "swim", "swimming"], "swim"),
       t("Should I (wait) ->", "wait", ["waits", "wait", "waiting"], "wait"),
       t("Can she (help) ->", "help", ["helps", "help", "helping"], "help")],
      [f("Can you swim well?", "Can you swims well?", "🏊"),
       f("Should I wait here?", "Should I waits here?", "⏳"),
       f("Can you help me?", "Can you helps me?", "🤝"),
       f("Should we come now?", "Should we comes now?", "👋")],
      srt("Yes answer", "No answer",
          [tok("Yes, I can.", "A", "✅"), tok("Yes, you should.", "A", "👍"), tok("Yes, she can.", "A", "🙋"),
           tok("No, I can't.", "B", "🚫"), tok("No, you shouldn't.", "B", "👎"), tok("No, we can't.", "B", "❌")]),
      [qa("Can you swim?", "Yes, I can."),
       qa("Should I wait here?", "No, you shouldn't."),
       qa("Can you help me?", "No, I can't."),
       qa("Should we come now?", "Yes, you should.")]),

    L("Mixed modal review",
      [("can", "🙋"), ("must", "❗"), ("should", "👍"), ("might", "🤷"), ("swim", "🏊"), ("help", "🤝")],
      "Modal review",
      ["I can swim fast.", "You must stop now.", "You should rest today.",
       "It might rain later.", "We would visit grandma."],
      [g("I ___ swim fast.", ["can", "cans"], "can", "🏊"),
       g("You must ___ now.", ["stop", "stops"], "stop", "🛑"),
       g("You ___ rest today.", ["should", "shoulds"], "should", "👍"),
       g("It might ___ later.", ["rain", "rains"], "rain", "🌧️")],
      [t("You must (stop) ->", "stop", ["stops", "stop", "stopping"], "stop"),
       t("I can (swim) ->", "swim", ["swims", "swim", "swimming"], "swim"),
       t("You should (rest) ->", "rest", ["rests", "rest", "resting"], "rest")],
      [f("I can swim fast.", "I can swims fast.", "🏊"),
       f("You must stop now.", "You must stops now.", "🛑"),
       f("You should rest today.", "You should rests today.", "👍"),
       f("It might rain later.", "It might rains later.", "🌧️")],
      srt("can (able)", "might (maybe)",
          [tok("I can swim", "A", "🏊"), tok("She can run", "A", "🏃"), tok("We can help", "A", "🤝"),
           tok("It might rain", "B", "🌧️"), tok("He might come", "B", "👋"), tok("It might snow", "B", "❄️")]),
      [qa("Can you swim?", "Yes, I can."),
       qa("Must I stop?", "Yes, you must."),
       qa("Should I rest?", "Yes, you should."),
       qa("Will it rain?", "It might rain.")]),
])
