# -*- coding: utf-8 -*-
from grammar_helpers import g, t, f, tok, srt, qa, L, W

# ===========================================================================
# WORLD 13 — Conditional Cove  (ADVANCED)
# Grammar arc: zero / first / second / third conditionals, mixed practice,
# advice, time connectives, dialogue, cause->result, review.
# Rule of thumb per type:
#   zero   : if + present, present            (facts)
#   first  : if + present, will + base        (real future)
#   second : if + past (were), would + base   (unreal present)
#   third  : if + had + PP, would have + PP    (unreal past)
# ===========================================================================
WORLD = W("Conditional Cove", "If... then... sentences", [

    L("Zero Conditional (facts)",
      [("ice", "🧊"), ("rain", "🌧️"), ("fire", "🔥"), ("water", "💧"), ("plant", "🌱"), ("sun", "☀️")],
      "Zero conditional (facts)",
      ["If you heat ice, it melts.",
       "If it rains, the ground gets wet.",
       "If you touch fire, it hurts.",
       "Plants grow if they get water.",
       "If you drop it, it falls."],
      [g("If you heat ice, it ___.", ["melts", "melt"], "melts", "🧊"),
       g("If it ___, the ground gets wet.", ["rains", "will rain"], "rains", "🌧️"),
       g("If you touch fire, it ___.", ["hurts", "hurt"], "hurts", "🔥"),
       g("Ice ___ if you heat it.", ["melts", "melt"], "melts", "🧊")],
      [t("it (melt) ->", "melt", ["melts", "melt", "melting"], "melts"),
       t("it (hurt) ->", "hurt", ["hurts", "hurt", "hurting"], "hurts"),
       t("it (fall) ->", "fall", ["falls", "fall", "falles"], "falls")],
      [f("If you heat ice, it melts.", "If you heat ice, it melt.", "🧊"),
       f("If it rains, the ground gets wet.", "If it rains, the ground get wet.", "🌧️"),
       f("If you touch fire, it hurts.", "If you touch fire, it hurt.", "🔥")],
      srt("if-part", "result-part",
          [tok("If you heat ice", "A", "🧊"), tok("If it rains", "A", "🌧️"), tok("If you touch fire", "A", "🔥"),
           tok("it melts", "B", "🧊"), tok("the ground gets wet", "B", "🌧️"), tok("it hurts", "B", "🔥")]),
      [qa("What happens if you heat ice?", "It melts."),
       qa("What happens if it rains?", "The ground gets wet."),
       qa("What happens if you touch fire?", "It hurts."),
       qa("What happens if plants get water?", "They grow.")]),

    L("First Conditional (real future)",
      [("rain", "🌧️"), ("help", "🤝"), ("study", "📚"), ("win", "🏆"), ("run", "🏃"), ("home", "🏠")],
      "First conditional (will)",
      ["If it rains, I will stay home.",
       "If you help, we will finish.",
       "If you run, you will win.",
       "If I study, I will pass.",
       "If it snows, we will play."],
      [g("If it ___, I will stay home.", ["rains", "will rain"], "rains", "🌧️"),
       g("If you help, we will ___.", ["finish", "finished"], "finish", "🤝"),
       g("If I study, I will ___.", ["pass", "passed"], "pass", "📚"),
       g("If you run, you will ___.", ["win", "won"], "win", "🏆")],
      [t("will + (finish) ->", "finish", ["finish", "finishes", "finished"], "finish"),
       t("will + (pass) ->", "pass", ["pass", "passes", "passed"], "pass"),
       t("will + (win) ->", "win", ["win", "wins", "won"], "win")],
      [f("If it rains, I will stay home.", "If it rains, I will stayed home.", "🌧️"),
       f("If you help, we will finish.", "If you help, we will finished.", "🤝"),
       f("If I study, I will pass.", "If I study, I will passed.", "📚")],
      srt("if-part", "will-part",
          [tok("If it rains", "A", "🌧️"), tok("If you help", "A", "🤝"), tok("If I study", "A", "📚"),
           tok("I will stay", "B", "🏠"), tok("we will finish", "B", "🤝"), tok("I will pass", "B", "🏆")]),
      [qa("What will you do if it rains?", "I will stay home."),
       qa("Will you win if you run?", "Yes, I will."),
       qa("What will happen if you study?", "I will pass."),
       qa("Will we finish if you help?", "Yes, we will.")]),

    L("Second Conditional (unreal present)",
      [("rich", "💰"), ("wings", "🪽"), ("fly", "🕊️"), ("travel", "✈️"), ("tall", "📏"), ("win", "🏆")],
      "Second conditional (would)",
      ["If I were rich, I would travel.",
       "If I had wings, I would fly.",
       "If I were tall, I would win.",
       "If she were here, she would help.",
       "If I won, I would be happy."],
      [g("If I ___ rich, I would travel.", ["were", "am"], "were", "💰"),
       g("If I had wings, I ___ fly.", ["would", "will"], "would", "🪽"),
       g("If I were tall, I would ___.", ["win", "won"], "win", "🏆"),
       g("If she ___ here, she would help.", ["were", "was"], "were", "🙋")],
      [t("I ... (be) rich ->", "be", ["were", "was", "am"], "were"),
       t("I would ... (travel) ->", "travel", ["travel", "traveled", "travels"], "travel"),
       t("I would ... (fly) ->", "fly", ["fly", "flew", "flies"], "fly")],
      [f("If I were rich, I would travel.", "If I was rich, I would travel.", "💰"),
       f("If I had wings, I would fly.", "If I had wings, I will fly.", "🪽"),
       f("If I were tall, I would win.", "If I were tall, I would won.", "🏆")],
      srt("real (will)", "unreal (would)",
          [tok("I will travel", "A", "✈️"), tok("I will fly", "A", "🕊️"), tok("I will win", "A", "🏆"),
           tok("I would travel", "B", "✈️"), tok("I would fly", "B", "🕊️"), tok("I would win", "B", "🏆")]),
      [qa("What would you do if you were rich?", "I would travel."),
       qa("What would you do if you had wings?", "I would fly."),
       qa("Would you be happy if you won?", "Yes, I would."),
       qa("What would she do if she were here?", "She would help.")]),

    L("Third Conditional (unreal past)",
      [("known", "💡"), ("asked", "🙋"), ("helped", "🤝"), ("passed", "✅"), ("called", "📞"), ("come", "🚶")],
      "Third conditional (would have)",
      ["If I had known, I would have helped.",
       "If you had asked, I would have come.",
       "If I had studied, I would have passed.",
       "If she had called, I would have answered.",
       "If we had left, we would have arrived."],
      [g("If I ___ known, I would have helped.", ["had", "have"], "had", "💡"),
       g("If I had known, I would ___ helped.", ["have", "had"], "have", "🤝"),
       g("If you had asked, I would have ___.", ["come", "came"], "come", "🙋"),
       g("If I had ___, I would have passed.", ["studied", "study"], "studied", "📚")],
      [t("would have + (help) ->", "help", ["helped", "help", "helps"], "helped"),
       t("had + (know) ->", "know", ["known", "knew", "knowed"], "known"),
       t("would have + (come) ->", "come", ["come", "came", "comed"], "come")],
      [f("If I had known, I would have helped.", "If I had knew, I would have helped.", "💡"),
       f("If you had asked, I would have come.", "If you had asked, I would had come.", "🙋"),
       f("If I had studied, I would have passed.", "If I had studied, I would have pass.", "✅")],
      srt("if-part (had)", "result (would have)",
          [tok("If I had known", "A", "💡"), tok("If you had asked", "A", "🙋"), tok("If I had studied", "A", "📚"),
           tok("I would have helped", "B", "🤝"), tok("I would have come", "B", "🚶"), tok("I would have passed", "B", "✅")]),
      [qa("What would you have done if you had known?", "I would have helped."),
       qa("Would you have come if I had asked?", "Yes, I would have."),
       qa("What would have happened if you had studied?", "I would have passed."),
       qa("Would she have answered if you had called?", "Yes, she would have.")]),

    L("Mixed Conditional Practice",
      [("ice", "🧊"), ("rain", "🌧️"), ("rich", "💰"), ("wings", "🪽"), ("help", "🤝"), ("melt", "🫠")],
      "Mixed conditionals",
      ["If you heat ice, it melts.",
       "If it rains, I will stay home.",
       "If I were rich, I would travel.",
       "If you help, we will finish.",
       "If I had wings, I would fly."],
      [g("If you heat ice, it ___.", ["melts", "will melt"], "melts", "🧊"),
       g("If it rains, I ___ home.", ["will stay", "stay"], "will stay", "🌧️"),
       g("If I ___ rich, I would travel.", ["were", "am"], "were", "💰"),
       g("If I had wings, I ___ fly.", ["would", "will"], "would", "🪽")],
      [t("zero: it (melt) ->", "melt", ["melts", "melt", "melted"], "melts"),
       t("second: I (be) ->", "be", ["were", "was", "am"], "were"),
       t("first: will (win) ->", "win", ["win", "wins", "won"], "win")],
      [f("If you heat ice, it melts.", "If you heat ice, it melt.", "🧊"),
       f("If it rains, I will stay home.", "If it rains, I will stayed home.", "🌧️"),
       f("If I were rich, I would travel.", "If I was rich, I would travel.", "💰")],
      srt("real (will)", "unreal (would)",
          [tok("I will stay", "A", "🏠"), tok("we will finish", "A", "🤝"), tok("you will win", "A", "🏆"),
           tok("I would travel", "B", "✈️"), tok("I would fly", "B", "🪽"), tok("I would help", "B", "💰")]),
      [qa("What happens if you heat ice?", "It melts."),
       qa("What will you do if it rains?", "I will stay home."),
       qa("What would you do if you were rich?", "I would travel."),
       qa("What would you do if you had wings?", "I would fly.")]),

    L("Conditional Questions & Advice",
      [("rest", "😴"), ("wait", "⏳"), ("ask", "🙋"), ("sleep", "🛌"), ("sick", "🤒"), ("help", "🤝")],
      "Advice: If I were you",
      ["If I were you, I would rest.",
       "If I were you, I would wait.",
       "If I were you, I would ask.",
       "If I were you, I would sleep.",
       "What would you do if you were lost?"],
      [g("If I were you, I would ___.", ["rest", "rested"], "rest", "😴"),
       g("If I ___ you, I would rest.", ["were", "am"], "were", "🙋"),
       g("If I were you, I ___ wait.", ["would", "will"], "would", "⏳"),
       g("What ___ you do if you were sick?", ["would", "will"], "would", "🤒")],
      [t("I would ... (rest) ->", "rest", ["rest", "rests", "rested"], "rest"),
       t("If I ... (be) you ->", "be", ["were", "was", "am"], "were"),
       t("I would ... (sleep) ->", "sleep", ["sleep", "slept", "sleeps"], "sleep")],
      [f("If I were you, I would rest.", "If I were you, I would rested.", "😴"),
       f("If I were you, I would wait.", "If I was you, I would wait.", "⏳"),
       f("If I were you, I would ask.", "If I were you, I will ask.", "🙋")],
      srt("question", "advice",
          [tok("What would you do?", "A", "❓"), tok("Where would you go?", "A", "❓"), tok("Who would you ask?", "A", "❓"),
           tok("I would rest.", "B", "😴"), tok("I would wait.", "B", "⏳"), tok("I would ask.", "B", "🙋")]),
      [qa("What would you do if you were tired?", "I would rest."),
       qa("What would you do if you were lost?", "I would ask."),
       qa("What would you do if you were sick?", "I would sleep."),
       qa("What would you do if you were bored?", "I would play.")]),

    L("Conditional Time Connectives",
      [("when", "🕐"), ("unless", "🚫"), ("hurry", "⏰"), ("late", "🐌"), ("sleep", "🛌"), ("rain", "🌧️")],
      "if / when / unless / as soon as",
      ["When it rains, I stay inside.",
       "Unless you hurry, you will be late.",
       "When I am tired, I sleep.",
       "As soon as I wake, I eat.",
       "If you call, I will come."],
      [g("___ it rains, I stay inside.", ["When", "Unless"], "When", "🌧️"),
       g("___ you hurry, you will be late.", ["Unless", "When"], "Unless", "⏰"),
       g("When I am tired, I ___.", ["sleep", "sleeps"], "sleep", "🛌"),
       g("___ you call, I will come.", ["If", "Unless"], "If", "📞")],
      [t("I (stay) ->", "stay", ["stay", "stays", "stayed"], "stay"),
       t("you will (be) ->", "be", ["be", "been", "being"], "be"),
       t("I (eat) ->", "eat", ["eat", "eats", "ate"], "eat")],
      [f("When it rains, I stay inside.", "When it rains, I stays inside.", "🌧️"),
       f("Unless you hurry, you will be late.", "Unless you hurry, you will been late.", "⏰"),
       f("When I am tired, I sleep.", "When I am tired, I sleeps.", "🛌")],
      srt("when (time)", "unless (if not)",
          [tok("When it rains", "A", "🌧️"), tok("When I wake", "A", "☀️"), tok("When I am tired", "A", "😴"),
           tok("Unless you hurry", "B", "⏰"), tok("Unless you help", "B", "🤝"), tok("Unless it stops", "B", "🛑")]),
      [qa("What do you do when it rains?", "I stay inside."),
       qa("When do you sleep?", "When I am tired."),
       qa("What happens unless you hurry?", "You will be late."),
       qa("When will you eat?", "As soon as I wake.")]),

    L("Conditionals in Conversation",
      [("ready", "✅"), ("hungry", "🍔"), ("cold", "🥶"), ("coat", "🧥"), ("call", "📞"), ("win", "🏆")],
      "If in conversation",
      ["If you are ready, we can go.",
       "If you are hungry, eat now.",
       "If you win, call me.",
       "If you are cold, take my coat.",
       "If it helps, I will stay."],
      [g("If you ___ ready, we can go.", ["are", "is"], "are", "✅"),
       g("If you are hungry, ___ now.", ["eat", "eats"], "eat", "🍔"),
       g("If it helps, I ___ stay.", ["will", "would"], "will", "🤝"),
       g("If you are cold, take my ___.", ["coat", "coats"], "coat", "🧥")],
      [t("you (be) ->", "be", ["are", "is", "am"], "are"),
       t("will (stay) ->", "stay", ["stay", "stays", "stayed"], "stay"),
       t("I (help) ->", "help", ["help", "helps", "helped"], "help")],
      [f("If you are ready, we can go.", "If you is ready, we can go.", "✅"),
       f("If you are hungry, eat now.", "If you are hungry, eats now.", "🍔"),
       f("If you are cold, take my coat.", "If you are cold, take my coats.", "🧥")],
      srt("asking", "answering",
          [tok("What if it rains?", "A", "🌧️"), tok("What if you win?", "A", "🏆"), tok("What if I help?", "A", "🤝"),
           tok("Then we stay.", "B", "🏠"), tok("Then I call you.", "B", "📞"), tok("Then we are happy.", "B", "😀")]),
      [qa("If it rains, what will we do?", "We will stay home."),
       qa("If you win, what will you do?", "I will call you."),
       qa("If you are cold, what do you need?", "I need a coat."),
       qa("If you are hungry, what will you eat?", "I will eat now.")]),

    L("Outcomes & Consequences",
      [("study", "📚"), ("pass", "✅"), ("run", "🏃"), ("win", "🏆"), ("help", "🤝"), ("sleep", "🛌")],
      "If ... then (cause and result)",
      ["If you study, then you will pass.",
       "If you run, then you will win.",
       "If it rains, then we stay home.",
       "If you help, then we finish fast.",
       "If you sleep, then you feel good."],
      [g("If you study, then you ___ pass.", ["will", "would"], "will", "📚"),
       g("If you run, then you will ___.", ["win", "won"], "win", "🏆"),
       g("If it rains, then we ___ home.", ["stay", "stayed"], "stay", "🌧️"),
       g("If you sleep, then you ___ good.", ["feel", "feels"], "feel", "🛌")],
      [t("will (win) ->", "win", ["win", "wins", "won"], "win"),
       t("will (pass) ->", "pass", ["pass", "passes", "passed"], "pass"),
       t("you (feel) ->", "feel", ["feel", "feels", "felt"], "feel")],
      [f("If you study, then you will pass.", "If you study, then you will passed.", "📚"),
       f("If you run, then you will win.", "If you run, then you will won.", "🏆"),
       f("If you sleep, then you feel good.", "If you sleep, then you feels good.", "🛌")],
      srt("cause (if)", "result (then)",
          [tok("If you study", "A", "📚"), tok("If you run", "A", "🏃"), tok("If you sleep", "A", "🛌"),
           tok("you will pass", "B", "✅"), tok("you will win", "B", "🏆"), tok("you feel good", "B", "😀")]),
      [qa("What happens if you study?", "You will pass."),
       qa("What happens if you run fast?", "You will win."),
       qa("Why will you pass?", "Because I study."),
       qa("Why do you feel good?", "Because I sleep.")]),

    L("Conditional Review Challenge",
      [("ice", "🧊"), ("rain", "🌧️"), ("rich", "💰"), ("known", "💡"), ("rest", "😴"), ("help", "🤝")],
      "Conditionals review",
      ["If you heat ice, it melts.",
       "If it rains, I will stay home.",
       "If I were rich, I would travel.",
       "If I had known, I would have helped.",
       "If I were you, I would rest."],
      [g("If you heat ice, it ___.", ["melts", "melt"], "melts", "🧊"),
       g("If it rains, I ___ home.", ["will stay", "stay"], "will stay", "🌧️"),
       g("If I ___ rich, I would travel.", ["were", "was"], "were", "💰"),
       g("If I had known, I ___ have helped.", ["would", "will"], "would", "💡")],
      [t("zero: it (melt) ->", "melt", ["melts", "melt", "melted"], "melts"),
       t("second: I (be) ->", "be", ["were", "was", "am"], "were"),
       t("third: would have (help) ->", "help", ["helped", "help", "helps"], "helped")],
      [f("If it rains, I will stay home.", "If it rains, I will stayed home.", "🌧️"),
       f("If I were rich, I would travel.", "If I was rich, I would travel.", "💰"),
       f("If I had known, I would have helped.", "If I had knew, I would have helped.", "💡")],
      srt("real (will)", "unreal (would)",
          [tok("I will stay", "A", "🏠"), tok("we will finish", "A", "🤝"), tok("you will pass", "A", "✅"),
           tok("I would travel", "B", "✈️"), tok("I would fly", "B", "🪽"), tok("I would rest", "B", "😴")]),
      [qa("What happens if you heat ice?", "It melts."),
       qa("What will you do if it rains?", "I will stay home."),
       qa("What would you do if you were rich?", "I would travel."),
       qa("What would you have done if you had known?", "I would have helped.")]),
])
