# -*- coding: utf-8 -*-
from grammar_helpers import g, t, f, tok, srt, qa, L, W

# ===========================================================================
# WORLD 14 — Passive Place  (ADVANCED)
# Grammar arc: the passive voice = be (am/is/are/was/were/been) + PAST
# PARTICIPLE. Subject-verb agreement (is/are, was/were) and correct participles
# (made, eaten, written, built, found, sent, done, broken, given, sung).
# ===========================================================================
WORLD = W("Passive Place", "The passive voice", [

    L("Made Right Here",
      [("cakes", "🎂"), ("bread", "🍞"), ("shop", "🏪"), ("made", "🔨"), ("sold", "🏷️"), ("clean", "🧼")],
      "am / is / are + participle",
      ["The cakes are made here.", "English is spoken here.", "The bread is sold here.",
       "The rooms are cleaned daily.", "The car is washed here.", "The toys are sold here."],
      [g("The cake ___ made here.", ["is", "are"], "is", "🎂"),
       g("The cakes ___ made here.", ["are", "is"], "are", "🎂"),
       g("English ___ spoken here.", ["is", "are"], "is"),
       g("The rooms ___ cleaned.", ["are", "is"], "are")],
      [t("make -> is ___", "make", ["made", "maked", "make"], "made"),
       t("sell -> is ___", "sell", ["sold", "selled", "sell"], "sold"),
       t("clean -> is ___", "clean", ["cleaned", "cleant", "clean"], "cleaned")],
      [f("The cake is made here.", "The cake is make here.", "🎂"),
       f("English is spoken here.", "English are spoken here."),
       f("The bread is sold here.", "The bread is sell here.", "🍞")],
      srt("is (one)", "are (many)",
          [tok("the cake", "A", "🎂"), tok("the bread", "A", "🍞"), tok("English", "A", "🗣️"),
           tok("the cakes", "B", "🎂"), tok("the toys", "B", "🧸"), tok("the rooms", "B", "🚪")]),
      [qa("Where are the cakes made?", "They are made here."),
       qa("Is English spoken here?", "Yes, it is."),
       qa("What is sold here?", "Bread is sold here."),
       qa("Are the rooms cleaned?", "Yes, they are.")]),

    L("It Was Done",
      [("cake", "🎂"), ("toys", "🧸"), ("eaten", "🍽️"), ("built", "🏗️"), ("found", "🔦"), ("window", "🪟")],
      "was / were + participle",
      ["The cake was eaten.", "The toys were made in China.", "The house was built last year.",
       "The keys were found.", "The window was broken.", "The cars were washed."],
      [g("The cake ___ eaten.", ["was", "were"], "was", "🎂"),
       g("The toys ___ made here.", ["were", "was"], "were", "🧸"),
       g("The window ___ broken.", ["was", "were"], "was", "🪟"),
       g("The keys ___ found.", ["were", "was"], "were", "🔑")],
      [t("eat -> was ___", "eat", ["eaten", "eated", "ate"], "eaten"),
       t("build -> was ___", "build", ["built", "builded", "build"], "built"),
       t("break -> was ___", "break", ["broken", "breaked", "broke"], "broken")],
      [f("The cake was eaten.", "The cake was ate.", "🎂"),
       f("The toys were made here.", "The toys was made here.", "🧸"),
       f("The window was broken.", "The window were broken.", "🪟")],
      srt("was (one)", "were (many)",
          [tok("the cake", "A", "🎂"), tok("the house", "A", "🏠"), tok("the window", "A", "🪟"),
           tok("the toys", "B", "🧸"), tok("the keys", "B", "🔑"), tok("the cars", "B", "🚗")]),
      [qa("Was the cake eaten?", "Yes, it was."),
       qa("Where were the toys made?", "They were made in China."),
       qa("What was broken?", "The window was broken."),
       qa("Were the keys found?", "Yes, they were.")]),

    L("Will Be, Has Been",
      [("house", "🏠"), ("built", "🏗️"), ("done", "✅"), ("soon", "⏳"), ("fixed", "🔧"), ("sent", "📤")],
      "will be / has been + participle",
      ["The house will be built.", "It has been done.", "The work will be finished soon.",
       "The letter has been sent.", "The car will be fixed.", "The room has been cleaned."],
      [g("The house will ___ built.", ["be", "been"], "be", "🏠"),
       g("It has ___ done.", ["been", "be"], "been", "✅"),
       g("The letter has ___ sent.", ["been", "be"], "been", "📤"),
       g("The car will ___ fixed.", ["be", "been"], "be", "🔧")],
      [t("do -> has been ___", "do", ["done", "did", "doed"], "done"),
       t("send -> has been ___", "send", ["sent", "sended", "send"], "sent"),
       t("finish -> will be ___", "finish", ["finished", "finisht", "finish"], "finished")],
      [f("The house will be built.", "The house will been built.", "🏠"),
       f("It has been done.", "It has be done.", "✅"),
       f("The letter has been sent.", "The letter has been send.", "📤")],
      srt("will be (future)", "has been (perfect)",
          [tok("will be built", "A", "🏗️"), tok("will be fixed", "A", "🔧"), tok("will be done", "A", "✅"),
           tok("has been built", "B", "🏗️"), tok("has been sent", "B", "📤"), tok("has been done", "B", "✅")]),
      [qa("When will the house be built?", "It will be built soon."),
       qa("Has the letter been sent?", "Yes, it has."),
       qa("Will the car be fixed?", "Yes, it will."),
       qa("Is the work done?", "Yes, it has been done.")]),

    L("Made by Mom",
      [("mom", "👩"), ("dad", "👨"), ("cake", "🎂"), ("song", "🎵"), ("made", "🔨"), ("written", "✍️")],
      "...by + person",
      ["The cake was made by mom.", "The song was written by her.", "The house was built by dad.",
       "The book was written by him.", "The room was cleaned by us.", "The toys were made by them."],
      [g("The cake was made ___ mom.", ["by", "to"], "by", "🎂"),
       g("It was written ___ her.", ["by", "of"], "by", "🎵"),
       g("The house was built ___ dad.", ["by", "with"], "by", "👨"),
       g("The room ___ cleaned by us.", ["was", "were"], "was", "🧹")],
      [t("write -> was ___", "write", ["written", "writed", "wrote"], "written"),
       t("make -> was ___", "make", ["made", "maked", "make"], "made"),
       t("build -> was ___", "build", ["built", "builded", "build"], "built")],
      [f("The cake was made by mom.", "The cake was make by mom.", "🎂"),
       f("The song was written by her.", "The song was writed by her.", "🎵"),
       f("The house was built by dad.", "The house was built for dad.", "👨")],
      srt("by (who)", "in / at (where)",
          [tok("by mom", "A", "👩"), tok("by dad", "A", "👨"), tok("by her", "A", "🙋"),
           tok("in China", "B", "🌏"), tok("at home", "B", "🏠"), tok("in the shop", "B", "🏪")]),
      [qa("Who made the cake?", "It was made by mom."),
       qa("Who wrote the song?", "It was written by her."),
       qa("Was it built by dad?", "Yes, it was."),
       qa("Who cleaned the room?", "It was cleaned by us.")]),

    L("Signs & Rules",
      [("shop", "🏪"), ("closed", "🚪"), ("open", "🔓"), ("dogs", "🐕"), ("sold", "🏷️"), ("allowed", "✅")],
      "signs: is closed / not allowed",
      ["The shop is closed.", "Dogs are not allowed.", "The gate is locked.",
       "Tickets are sold here.", "The road is closed.", "Smoking is not allowed."],
      [g("The shop ___ closed.", ["is", "are"], "is", "🏪"),
       g("Dogs ___ not allowed.", ["are", "is"], "are", "🐕"),
       g("The road is ___.", ["closed", "close"], "closed", "🚧"),
       g("Tickets ___ sold here.", ["are", "is"], "are", "🎫")],
      [t("close -> is ___", "close", ["closed", "closd", "close"], "closed"),
       t("lock -> is ___", "lock", ["locked", "lockt", "lock"], "locked"),
       t("allow -> is ___", "allow", ["allowed", "allowd", "allow"], "allowed")],
      [f("The shop is closed.", "The shop is close.", "🏪"),
       f("Dogs are not allowed.", "Dogs is not allowed.", "🐕"),
       f("The gate is locked.", "The gate are locked.", "🔒")],
      srt("is (one)", "are (many)",
          [tok("the shop", "A", "🏪"), tok("the gate", "A", "🚪"), tok("the road", "A", "🚧"),
           tok("dogs", "B", "🐕"), tok("tickets", "B", "🎫"), tok("the shops", "B", "🏪")]),
      [qa("Is the shop open?", "No, it is closed."),
       qa("Are dogs allowed?", "No, they are not."),
       qa("Is the road closed?", "Yes, it is."),
       qa("Are tickets sold here?", "Yes, they are.")]),

    L("Got Broken",
      [("hurt", "🤕"), ("broken", "🪟"), ("lost", "🔍"), ("fixed", "🔧"), ("paid", "💰"), ("wet", "💧")],
      "get + participle (informal)",
      ["He got hurt.", "The window got broken.", "My bag got lost.",
       "The car got fixed.", "She got paid today.", "We got wet."],
      [g("He ___ hurt yesterday.", ["got", "get"], "got", "🤕"),
       g("The window ___ broken.", ["got", "get"], "got", "🪟"),
       g("My bag ___ lost.", ["got", "get"], "got", "🎒"),
       g("She got ___ today.", ["paid", "pay"], "paid", "💰")],
      [t("pay -> got ___", "pay", ["paid", "payed", "pay"], "paid"),
       t("break -> got ___", "break", ["broken", "breaked", "broke"], "broken"),
       t("lose -> got ___", "lose", ["lost", "losed", "loosed"], "lost")],
      [f("He got hurt.", "He got hurted.", "🤕"),
       f("The window got broken.", "The window got broke.", "🪟"),
       f("My bag got lost.", "My bag got lose.", "🎒")],
      srt("got + participle", "was + participle",
          [tok("got hurt", "A", "🤕"), tok("got broken", "A", "🪟"), tok("got lost", "A", "🔍"),
           tok("was hurt", "B", "🤕"), tok("was broken", "B", "🪟"), tok("was lost", "B", "🔍")]),
      [qa("What happened to him?", "He got hurt."),
       qa("Did the window get broken?", "Yes, it did."),
       qa("Did you get wet?", "Yes, we did."),
       qa("Did she get paid?", "Yes, she did.")]),

    L("In the News",
      [("bridge", "🌉"), ("opened", "🎉"), ("dog", "🐕"), ("found", "🔦"), ("park", "🌳"), ("built", "🏗️")],
      "was + participle (news)",
      ["The bridge was opened yesterday.", "A dog was found in the park.", "A new school was built.",
       "The game was won by us.", "The cat was found safe.", "A gift was given to her."],
      [g("The bridge ___ opened.", ["was", "were"], "was", "🌉"),
       g("A dog ___ found here.", ["was", "were"], "was", "🐕"),
       g("Two dogs ___ found.", ["were", "was"], "were", "🐕"),
       g("A school was ___.", ["built", "build"], "built", "🏫")],
      [t("open -> was ___", "open", ["opened", "openned", "open"], "opened"),
       t("find -> was ___", "find", ["found", "finded", "founded"], "found"),
       t("give -> was ___", "give", ["given", "gived", "gave"], "given")],
      [f("The bridge was opened.", "The bridge was opens.", "🌉"),
       f("A dog was found here.", "A dog were found here.", "🐕"),
       f("A school was built.", "A school was build.", "🏫")],
      srt("was (one)", "were (many)",
          [tok("a dog", "A", "🐕"), tok("the bridge", "A", "🌉"), tok("a gift", "A", "🎁"),
           tok("two dogs", "B", "🐕"), tok("the bridges", "B", "🌉"), tok("the games", "B", "🎮")]),
      [qa("What was opened yesterday?", "The bridge was opened."),
       qa("Where was the dog found?", "It was found in the park."),
       qa("Was a new school built?", "Yes, it was."),
       qa("Who won the game?", "It was won by us.")]),

    L("Build It Passive",
      [("letter", "✉️"), ("sent", "📤"), ("cake", "🎂"), ("made", "🔨"), ("book", "📖"), ("read", "📚")],
      "build a passive sentence",
      ["The letter was sent.", "The cake was made here.", "The book was read aloud.",
       "The toys were sold fast.", "The house was painted white.", "The song was sung well."],
      [g("The letter ___ sent.", ["was", "were"], "was", "✉️"),
       g("The letters ___ sent.", ["were", "was"], "were", "✉️"),
       g("The cake was ___ here.", ["made", "make"], "made", "🎂"),
       g("The house was ___ white.", ["painted", "paint"], "painted", "🏠")],
      [t("send -> was ___", "send", ["sent", "sended", "send"], "sent"),
       t("paint -> was ___", "paint", ["painted", "painting", "paint"], "painted"),
       t("sing -> was ___", "sing", ["sung", "singed", "sang"], "sung")],
      [f("The letter was sent.", "The letter was send.", "✉️"),
       f("The cake was made here.", "The cake was make here.", "🎂"),
       f("The toys were sold fast.", "The toys was sold fast.", "🧸")],
      srt("was (one)", "were (many)",
          [tok("the letter", "A", "✉️"), tok("the cake", "A", "🎂"), tok("the book", "A", "📖"),
           tok("the letters", "B", "✉️"), tok("the cakes", "B", "🎂"), tok("the toys", "B", "🧸")]),
      [qa("Was the letter sent?", "Yes, it was."),
       qa("Where was the cake made?", "It was made here."),
       qa("Were the toys sold?", "Yes, they were."),
       qa("What color was the house?", "It was painted white.")]),

    L("Active or Passive?",
      [("cake", "🎂"), ("made", "🔨"), ("mom", "👩"), ("song", "🎵"), ("ball", "⚽"), ("kicked", "🦵")],
      "active -> passive",
      ["The cake is made by mom.", "The song was sung by her.", "The ball was kicked by him.",
       "The book is read by us.", "The room is cleaned by dad.", "The car was washed by me."],
      [g("The cake ___ made by mom.", ["is", "are"], "is", "🎂"),
       g("The cakes ___ made by mom.", ["are", "is"], "are", "🎂"),
       g("The ball ___ kicked by him.", ["was", "were"], "was", "⚽"),
       g("The songs ___ sung by her.", ["were", "was"], "were", "🎵")],
      [t("kick -> was ___", "kick", ["kicked", "kickt", "kick"], "kicked"),
       t("wash -> was ___", "wash", ["washed", "washt", "wash"], "washed"),
       t("sing -> was ___", "sing", ["sung", "singed", "sang"], "sung")],
      [f("The cake is made by mom.", "The cake is make by mom.", "🎂"),
       f("The ball was kicked by him.", "The ball were kicked by him.", "⚽"),
       f("The song was sung by her.", "The song was sang by her.", "🎵")],
      srt("active", "passive",
          [tok("Mom makes it.", "A", "👩"), tok("He kicks it.", "A", "🦵"), tok("She sings.", "A", "🎵"),
           tok("It is made.", "B", "🎂"), tok("It is kicked.", "B", "⚽"), tok("It is sung.", "B", "🎶")]),
      [qa("Who makes the cake?", "It is made by mom."),
       qa("Who kicked the ball?", "It was kicked by him."),
       qa("Who sang the song?", "It was sung by her."),
       qa("Who washed the car?", "It was washed by me.")]),

    L("Passive Review",
      [("made", "🔨"), ("eaten", "🍽️"), ("built", "🏗️"), ("found", "🔦"), ("sent", "📤"), ("sold", "🏷️")],
      "present & past passive",
      ["The cakes are made here.", "The cake was eaten.", "The house was built.",
       "English is spoken here.", "The letter was sent.", "The keys were found."],
      [g("The cakes ___ made here.", ["are", "is"], "are", "🎂"),
       g("The cake ___ eaten.", ["was", "were"], "was", "🍽️"),
       g("English ___ spoken here.", ["is", "are"], "is"),
       g("The keys ___ found.", ["were", "was"], "were", "🔑")],
      [t("eat -> was ___", "eat", ["eaten", "eated", "ate"], "eaten"),
       t("build -> was ___", "build", ["built", "builded", "build"], "built"),
       t("send -> was ___", "send", ["sent", "sended", "send"], "sent")],
      [f("The cake was eaten.", "The cake was eated.", "🍽️"),
       f("English is spoken here.", "English is speak here."),
       f("The keys were found.", "The keys was found.", "🔑")],
      srt("is / are (now)", "was / were (past)",
          [tok("is made", "A", "🔨"), tok("are sold", "A", "🏷️"), tok("is spoken", "A", "🗣️"),
           tok("was eaten", "B", "🍽️"), tok("were found", "B", "🔦"), tok("was built", "B", "🏗️")]),
      [qa("Where are the cakes made?", "They are made here."),
       qa("Was the cake eaten?", "Yes, it was."),
       qa("Is English spoken here?", "Yes, it is."),
       qa("Were the keys found?", "Yes, they were.")]),
])
