# -*- coding: utf-8 -*-
from grammar_helpers import g, t, f, tok, srt, qa, L, W

# ===========================================================================
# WORLD 15 — Speech Street  (ADVANCED)
# Grammar arc: reported speech (say/tell + backshift, reported questions with
# statement order, reported commands with to + verb), relative clauses
# (who/which/that, defining vs non-defining), tag questions, direct & indirect
# objects, and gerunds vs infinitives (enjoy + -ing, want + to). Every sentence
# is kept SHORT and clearly correct.
# ===========================================================================
WORLD = W("Speech Street", "Reported speech, clauses & objects", [

    L("Reported Statements",
      [("said", "💬"), ("told", "🗣️"), ("was", "⏳"), ("were", "👥"), ("happy", "😄"), ("tired", "😴")],
      "said / told + backshift",
      ["She said she was happy.", "He told me he was tired.", "They said they were busy.",
       "She said she was ready.", "He told us he was late."],
      [g("She said she ___ happy.", ["was", "is"], "was", "😄"),
       g("They said they ___ busy.", ["were", "are"], "were", "👥"),
       g("He ___ me he was late.", ["told", "said"], "told", "🗣️"),
       g("She ___ she was ready.", ["said", "told"], "said", "💬")],
      [t("am -> reported", "am", ["was", "were", "is"], "was"),
       t("are -> reported", "are", ["were", "was", "are"], "were"),
       t("is -> reported", "is", ["was", "is", "were"], "was")],
      [f("She said she was happy.", "She said she is happy.", "😄"),
       f("He told me he was tired.", "He told me he is tired.", "😴"),
       f("They said they were busy.", "They said they are busy.", "👥"),
       f("He told us he was late.", "He said us he was late.", "🗣️")],
      srt("was", "were",
          [tok("she was", "A", "😄"), tok("he was", "A", "😴"), tok("I was", "A", "🙂"),
           tok("they were", "B", "👥"), tok("we were", "B", "👨‍👩‍👧"), tok("you were", "B", "🫵")]),
      [qa("What did she say?", "She said she was happy."),
       qa("What did he tell you?", "He told me he was tired."),
       qa("What did they say?", "They said they were busy."),
       qa("Was she ready?", "Yes, she said she was ready.")]),

    L("Reported Questions",
      [("asked", "🙋"), ("where", "📍"), ("when", "🕐"), ("why", "❓"), ("lived", "🏠"), ("live", "🏡")],
      "asked + statement order",
      ["She asked where I lived.", "He asked why I was late.", "She asked what I wanted.",
       "He asked where I was.", "She asked when I left."],
      [g("She asked where I ___.", ["lived", "live"], "lived", "🏠"),
       g("He asked what I ___.", ["wanted", "want"], "wanted", "❓"),
       g("She asked where I ___.", ["was", "am"], "was", "📍"),
       g("He asked when I ___.", ["left", "leave"], "left", "🕐")],
      [t("live -> reported", "live", ["lived", "live", "lives"], "lived"),
       t("want -> reported", "want", ["wanted", "want", "wants"], "wanted"),
       t("is -> reported", "is", ["was", "is", "were"], "was")],
      [f("She asked where I lived.", "She asked where I live.", "🏠"),
       f("He asked what I wanted.", "He asked what I want.", "❓"),
       f("She asked where I was.", "She asked where I were.", "📍"),
       f("He asked when I left.", "He asked when I leave.", "🕐")],
      srt("now (direct)", "reported (past)",
          [tok("I live", "A", "🏡"), tok("I want", "A", "❓"), tok("I am", "A", "🙂"),
           tok("I lived", "B", "🏠"), tok("I wanted", "B", "✅"), tok("I was", "B", "📍")]),
      [qa("What did she ask?", "She asked where I lived."),
       qa("What did he ask?", "He asked why I was late."),
       qa("Did she ask about you?", "Yes, she asked what I wanted."),
       qa("What did the man ask?", "He asked where I was.")]),

    L("Reported Commands",
      [("told", "🗣️"), ("asked", "🙋"), ("sit", "🪑"), ("wait", "⏳"), ("stop", "🛑"), ("help", "🤝")],
      "told / asked + to + verb",
      ["He told me to sit down.", "She asked me to wait.", "He told us to be quiet.",
       "She asked him to help.", "They told me to stop."],
      [g("He told me ___ sit down.", ["to", "for"], "to", "🪑"),
       g("She asked me to ___.", ["wait", "waiting"], "wait", "⏳"),
       g("He told us to ___ quiet.", ["be", "being"], "be", "🤫"),
       g("She asked me to ___.", ["stop", "stopped"], "stop", "🛑")],
      [t("Sit! -> to ___", "sit", ["sit", "sat", "sitting"], "sit"),
       t("Wait! -> to ___", "wait", ["wait", "waited", "waiting"], "wait"),
       t("Stop! -> to ___", "stop", ["stop", "stopped", "stopping"], "stop")],
      [f("He told me to sit down.", "He told me to sat down.", "🪑"),
       f("She asked me to wait.", "She asked me to waiting.", "⏳"),
       f("He told us to stop.", "He told us for stop.", "🛑"),
       f("She asked him to help.", "She asked him to helps.", "🤝")],
      srt("told (order)", "asked (request)",
          [tok("told me to sit", "A", "🪑"), tok("told us to stop", "A", "🛑"), tok("told him to wait", "A", "⏳"),
           tok("asked me to help", "B", "🤝"), tok("asked her to wait", "B", "⏳"), tok("asked me to come", "B", "🚪")]),
      [qa("What did he tell you?", "He told me to sit down."),
       qa("What did she ask?", "She asked me to wait."),
       qa("What did they tell you?", "They told me to stop."),
       qa("Did she ask for help?", "Yes, she asked me to help.")]),

    L("Who, Which, That",
      [("who", "🧑"), ("which", "❔"), ("that", "👉"), ("girl", "👧"), ("book", "📕"), ("dog", "🐶")],
      "who / which / that",
      ["The girl who sings is my friend.", "The book which I read is good.",
       "The dog that barks is big.", "I know the boy who runs fast.",
       "This is the cake that Mom made."],
      [g("The girl ___ sings is nice.", ["who", "which"], "who", "👧"),
       g("The book ___ I read is good.", ["which", "who"], "which", "📕"),
       g("The dog ___ barks is big.", ["that", "who"], "that", "🐶"),
       g("I know the boy ___ runs fast.", ["who", "which"], "who", "🏃")],
      [t("a person -> ___", "person", ["who", "which", "what"], "who"),
       t("a thing -> ___", "thing", ["which", "who", "whom"], "which"),
       t("an animal -> ___", "animal", ["that", "which", "who"], "that")],
      [f("The girl who sings is nice.", "The girl which sings is nice.", "👧"),
       f("The book which I read is good.", "The book who I read is good.", "📕"),
       f("The dog that barks is big.", "The dog what barks is big.", "🐶"),
       f("I know the boy who runs.", "I know the boy which runs.", "🏃")],
      srt("who (people)", "which (things)",
          [tok("girl", "A", "👧"), tok("boy", "A", "👦"), tok("friend", "A", "🧑"),
           tok("book", "B", "📕"), tok("cake", "B", "🍰"), tok("ball", "B", "⚽")]),
      [qa("Who is your friend?", "The girl who sings."),
       qa("Which book is good?", "The book that I read."),
       qa("Which dog is big?", "The dog that barks."),
       qa("Who runs fast?", "The boy who plays.")]),

    L("Extra Info",
      [("comma", "✏️"), ("brown", "🤎"), ("extra", "➕"), ("which", "❔"), ("who", "🧑"), ("dog", "🐶")],
      "extra info with commas",
      ["My dog, which is brown, is friendly.", "My mom, who is kind, cooks well.",
       "This book, which is new, is fun.", "Tom, who is tall, plays ball.",
       "Our cat, which is small, sleeps a lot."],
      [g("My dog, ___ is brown, is nice.", ["which", "who"], "which", "🐶"),
       g("My mom, ___ is kind, cooks.", ["who", "which"], "who", "👩"),
       g("Tom, ___ is tall, plays ball.", ["who", "which"], "who", "🧑"),
       g("This book, ___ is new, is fun.", ["which", "who"], "which", "📗")],
      [t("my mom -> ___", "mom", ["who", "which", "that"], "who"),
       t("this book -> ___", "book", ["which", "who", "what"], "which"),
       t("my friend -> ___", "friend", ["who", "which", "whose"], "who")],
      [f("My dog, which is brown, is nice.", "My dog, who is brown, is nice.", "🐶"),
       f("My mom, who is kind, cooks.", "My mom, which is kind, cooks.", "👩"),
       f("Tom, who is tall, plays ball.", "Tom, which is tall, plays ball.", "🧑"),
       f("This book, which is new, is fun.", "This book, who is new, is fun.", "📗")],
      srt("who (people)", "which (things)",
          [tok("my mom", "A", "👩"), tok("my dad", "A", "👨"), tok("my friend", "A", "🧑"),
           tok("my book", "B", "📗"), tok("my bike", "B", "🚲"), tok("my toy", "B", "🧸")]),
      [qa("What is your dog like?", "My dog, which is brown, is friendly."),
       qa("Tell me about your mom.", "My mom, who is kind, cooks well."),
       qa("What is that book?", "This book, which is new, is fun."),
       qa("Who is Tom?", "Tom, who is tall, plays ball.")]),

    L("Tag Questions",
      [("tag", "🏷️"), ("happy", "😄"), ("swim", "🏊"), ("right", "✅"), ("agree", "🤝"), ("check", "☑️")],
      "statement + tag question",
      ["You are happy, aren't you?", "She can swim, can't she?", "He is tall, isn't he?",
       "They are here, aren't they?", "You like ice cream, don't you?"],
      [g("You are happy, ___ you?", ["aren't", "are"], "aren't", "😄"),
       g("She can swim, ___ she?", ["can't", "can"], "can't", "🏊"),
       g("He is tall, ___ he?", ["isn't", "is"], "isn't", "🧍"),
       g("They are here, ___ they?", ["aren't", "are"], "aren't", "📍")],
      [t("You are... -> ___", "are", ["aren't you", "are you", "aren't he"], "aren't you"),
       t("She can... -> ___", "can", ["can't she", "can she", "can't he"], "can't she"),
       t("He is... -> ___", "is", ["isn't he", "is he", "isn't she"], "isn't he")],
      [f("You are happy, aren't you?", "You are happy, are you?", "😄"),
       f("She can swim, can't she?", "She can swim, can she?", "🏊"),
       f("He is tall, isn't he?", "He is tall, isn't she?", "🧍"),
       f("They are here, aren't they?", "They are here, isn't they?", "📍")],
      srt("be tag", "can tag",
          [tok("isn't he", "A", "🧍"), tok("aren't you", "A", "🙂"), tok("aren't they", "A", "👥"),
           tok("can't she", "B", "🏊"), tok("can't he", "B", "🏃"), tok("can't we", "B", "🤝")]),
      [qa("You are happy, aren't you?", "Yes, I am."),
       qa("She can swim, can't she?", "Yes, she can."),
       qa("He is tall, isn't he?", "Yes, he is."),
       qa("They are here, aren't they?", "Yes, they are.")]),

    L("Give Me the Ball",
      [("gave", "🤲"), ("sent", "✉️"), ("ball", "⚽"), ("gift", "🎁"), ("letter", "📩"), ("book", "📕")],
      "give me / give to me",
      ["She gave me a gift.", "He sent a letter to her.", "I gave him the ball.",
       "She sent me a card.", "He gave the book to me."],
      [g("She gave ___ a gift.", ["me", "to me"], "me", "🎁"),
       g("He sent a letter ___ her.", ["to", "for"], "to", "📩"),
       g("I gave the ball ___ him.", ["to", "at"], "to", "⚽"),
       g("She sent ___ a card.", ["me", "to me"], "me", "💌")],
      [t("a gift ___ me", "gift", ["to", "for", "at"], "to"),
       t("a letter ___ her", "letter", ["to", "for", "in"], "to"),
       t("the ball ___ him", "ball", ["to", "at", "on"], "to")],
      [f("He sent a letter to her.", "He sent a letter for her.", "📩"),
       f("I gave the ball to him.", "I gave the ball at him.", "⚽"),
       f("She gave me a gift.", "She gave my a gift.", "🎁"),
       f("He gave the book to me.", "He gave the book for me.", "📕")],
      srt("give me a gift", "give a gift to me",
          [tok("sent me a card", "A", "💌"), tok("gave me a book", "A", "📕"), tok("told me a joke", "A", "😂"),
           tok("a card to me", "B", "💌"), tok("a book to her", "B", "📕"), tok("a gift to him", "B", "🎁")]),
      [qa("What did she give you?", "She gave me a gift."),
       qa("What did he send?", "He sent a letter to her."),
       qa("Did you give him the ball?", "Yes, I gave him the ball."),
       qa("Who did she send a card to?", "She sent a card to me.")]),

    L("Gerunds & Infinitives",
      [("swim", "🏊"), ("read", "📖"), ("like", "👍"), ("want", "🙏"), ("play", "▶️"), ("run", "🏃")],
      "-ing vs to + verb",
      ["I like swimming.", "I want to swim.", "She likes reading.",
       "He wants to play.", "We like playing.", "I want to read."],
      [g("I want to ___.", ["swim", "swimming"], "swim", "🏊"),
       g("She wants to ___.", ["read", "reading"], "read", "📖"),
       g("He likes ___.", ["playing", "play"], "playing", "▶️"),
       g("They like ___.", ["reading", "read"], "reading", "📖")],
      [t("swim -> -ing", "swim", ["swimming", "swiming", "swim"], "swimming"),
       t("read -> -ing", "read", ["reading", "readding", "read"], "reading"),
       t("run -> -ing", "run", ["running", "runing", "run"], "running")],
      [f("I want to swim.", "I want to swimming.", "🏊"),
       f("She likes reading.", "She likes read.", "📖"),
       f("He wants to play.", "He wants to playing.", "▶️"),
       f("They like playing.", "They like play.", "🎮")],
      srt("-ing", "to + verb",
          [tok("swimming", "A", "🏊"), tok("reading", "A", "📖"), tok("playing", "A", "▶️"),
           tok("to swim", "B", "🏊"), tok("to read", "B", "📖"), tok("to play", "B", "▶️")]),
      [qa("What do you like?", "I like swimming."),
       qa("What do you want to do?", "I want to swim."),
       qa("Does she like reading?", "Yes, she likes reading."),
       qa("What does he want?", "He wants to play.")]),

    L("Verbs + Gerund",
      [("enjoy", "😀"), ("finish", "🏁"), ("avoid", "🚫"), ("keep", "🔁"), ("read", "📖"), ("eat", "🍽️")],
      "enjoy / finish + -ing",
      ["I enjoy reading.", "She finished eating.", "He avoids running.",
       "They keep talking.", "We enjoy playing.", "I finished cooking."],
      [g("I enjoy ___.", ["reading", "to read"], "reading", "📖"),
       g("She finished ___.", ["eating", "to eat"], "eating", "🍽️"),
       g("He avoids ___.", ["running", "to run"], "running", "🏃"),
       g("They keep ___.", ["talking", "to talk"], "talking", "💬")],
      [t("enjoy + read", "read", ["reading", "to read", "read"], "reading"),
       t("finish + eat", "eat", ["eating", "to eat", "eat"], "eating"),
       t("keep + talk", "talk", ["talking", "to talk", "talk"], "talking")],
      [f("I enjoy reading.", "I enjoy read.", "📖"),
       f("She finished eating.", "She finished eat.", "🍽️"),
       f("They keep talking.", "They keep talk.", "💬"),
       f("He avoids running.", "He avoids run.", "🏃")],
      srt("enjoy + -ing", "want + to",
          [tok("enjoy reading", "A", "📖"), tok("finish eating", "A", "🍽️"), tok("keep running", "A", "🏃"),
           tok("want to read", "B", "📖"), tok("hope to eat", "B", "🍽️"), tok("need to run", "B", "🏃")]),
      [qa("What do you enjoy?", "I enjoy reading."),
       qa("Did she finish?", "Yes, she finished eating."),
       qa("What do they keep doing?", "They keep talking."),
       qa("Do you enjoy sports?", "Yes, I enjoy playing.")]),

    L("Verbs + Infinitive",
      [("want", "🙏"), ("need", "❗"), ("hope", "🌟"), ("decide", "🤔"), ("help", "🤝"), ("learn", "📚")],
      "want / need + to + verb",
      ["I want to go.", "She decided to help.", "He needs to sleep.",
       "We hope to win.", "They want to play.", "I need to learn."],
      [g("I want to ___.", ["go", "going"], "go", "🚶"),
       g("She needs to ___.", ["sleep", "sleeping"], "sleep", "😴"),
       g("We hope to ___.", ["win", "winning"], "win", "🏆"),
       g("They decide to ___.", ["help", "helping"], "help", "🤝")],
      [t("want to + go", "go", ["go", "going", "goes"], "go"),
       t("need to + sleep", "sleep", ["sleep", "sleeping", "slept"], "sleep"),
       t("hope to + win", "win", ["win", "winning", "won"], "win")],
      [f("I want to go.", "I want to going.", "🚶"),
       f("She needs to sleep.", "She needs to sleeping.", "😴"),
       f("We hope to win.", "We hope to winning.", "🏆"),
       f("They want to play.", "They want to playing.", "▶️")],
      srt("want + to", "enjoy + -ing",
          [tok("want to go", "A", "🚶"), tok("need to sleep", "A", "😴"), tok("hope to win", "A", "🏆"),
           tok("enjoy playing", "B", "🎮"), tok("finish eating", "B", "🍽️"), tok("keep running", "B", "🏃")]),
      [qa("What do you want?", "I want to go."),
       qa("What did she decide?", "She decided to help."),
       qa("What does he need?", "He needs to sleep."),
       qa("What do they hope?", "They hope to win.")]),
])
