# -*- coding: utf-8 -*-
from grammar_helpers import g, t, f, tok, srt, qa, L, W

# ===========================================================================
# WORLD 16 — Structure Station  (Phrasal verbs & connectors)
# Advanced grammar/usage: phrasal verbs (get/take/put/make/look), idioms,
# collocations, linking words, time expressions, prepositions of time.
# ===========================================================================
WORLD = W("Structure Station", "Phrasal verbs & connectors", [

    L("Phrasal Verbs with GET",
      [("get", "🤲"), ("up", "⬆️"), ("bus", "🚌"), ("off", "🚏"), ("out", "🚪"), ("seven", "7️⃣")],
      "Phrasal verbs: get",
      ["I get up at seven.", "Get on the bus.", "Get off the bus here.",
       "Please get out now.", "We get back at four."],
      [g("I get ___ at seven.", ["up", "off"], "up", "⏰"),
       g("Get ___ the bus.", ["on", "up"], "on", "🚌"),
       g("Get ___ the bus here.", ["off", "up"], "off", "🚏"),
       g("Please get ___ now.", ["out", "on"], "out", "🚪")],
      [t("get -> he form", "get", ["gets", "getes", "get"], "gets"),
       t("get -> past", "get", ["got", "getted", "get"], "got"),
       t("get -> -ing", "get", ["getting", "geting", "gettin"], "getting")],
      [f("She gets up early.", "She get up early.", "⏰"),
       f("He gets off the bus.", "He get off the bus.", "🚏"),
       f("I got up late.", "I getted up late.", "😴")],
      srt("get ON", "get OFF",
          [tok("get on the bus", "A", "🚌"), tok("get on the train", "A", "🚆"), tok("get on the plane", "A", "✈️"),
           tok("get off the bus", "B", "🚏"), tok("get off here", "B", "🚪"), tok("get off the train", "B", "🚆")]),
      [qa("What time do you get up?", "I get up at seven."),
       qa("Where do you get on the bus?", "At school."),
       qa("Do you get up early?", "Yes, I do."),
       qa("When do you get back?", "At four o'clock.")]),

    L("Phrasal Verbs with TAKE",
      [("take", "✋"), ("off", "🛫"), ("out", "🗑️"), ("back", "🔙"), ("shoes", "👟"), ("plane", "✈️")],
      "Phrasal verbs: take",
      ["Take off your shoes.", "Planes take off.", "Please take out the trash.",
       "I take back my book.", "Take out your book.", "I want to take up chess."],
      [g("Take ___ your shoes.", ["off", "out"], "off", "👟"),
       g("Planes take ___.", ["off", "back"], "off", "✈️"),
       g("Please take ___ the trash.", ["out", "up"], "out", "🗑️"),
       g("I want to take ___ chess.", ["up", "off"], "up", "♟️")],
      [t("take -> he form", "take", ["takes", "takees", "take"], "takes"),
       t("take -> past", "take", ["took", "taked", "take"], "took"),
       t("take -> -ing", "take", ["taking", "takeing", "takking"], "taking")],
      [f("She takes off her shoes.", "She take off her shoes.", "👟"),
       f("Planes take off fast.", "Planes takes off fast.", "✈️"),
       f("I took back the book.", "I taked back the book.", "📕"),
       f("Take out the trash.", "Takes out the trash.", "🗑️")],
      srt("take OFF", "take OUT",
          [tok("take off your shoes", "A", "👟"), tok("take off your coat", "A", "🧥"), tok("planes take off", "A", "✈️"),
           tok("take out the trash", "B", "🗑️"), tok("take out your book", "B", "📕"), tok("take out a pen", "B", "🖊️")]),
      [qa("What do you take off?", "I take off my shoes."),
       qa("Do planes take off?", "Yes, they do."),
       qa("What should I take out?", "Take out the trash."),
       qa("Do you want to take up chess?", "Yes, I do.")]),

    L("Phrasal Verbs with PUT",
      [("put", "✋"), ("on", "👕"), ("off", "⏭️"), ("away", "🧸"), ("down", "👇"), ("coat", "🧥")],
      "Phrasal verbs: put",
      ["Put on your coat.", "Put away your toys.", "Please put down the box.",
       "Put on your shoes.", "Put away the books.", "Put down your pen."],
      [g("Put ___ your coat.", ["on", "down"], "on", "🧥"),
       g("Put ___ your toys.", ["away", "on"], "away", "🧸"),
       g("Please put ___ the box.", ["down", "on"], "down", "📦"),
       g("Put ___ your shoes.", ["on", "away"], "on", "👟")],
      [t("put -> he form", "put", ["puts", "putes", "put"], "puts"),
       t("put -> past", "put", ["put", "putted", "puted"], "put"),
       t("put -> -ing", "put", ["putting", "puting", "puttin"], "putting")],
      [f("She puts on her coat.", "She put on her coat.", "🧥"),
       f("Put away your toys.", "Puts away your toys.", "🧸"),
       f("He puts down the box.", "He put down the box.", "📦"),
       f("I am putting it away.", "I am puting it away.", "🧸")],
      srt("put ON", "put AWAY",
          [tok("put on your coat", "A", "🧥"), tok("put on your shoes", "A", "👟"), tok("put on a hat", "A", "🧢"),
           tok("put away your toys", "B", "🧸"), tok("put away the books", "B", "📚"), tok("put away the plates", "B", "🍽️")]),
      [qa("What do you put on?", "I put on my coat."),
       qa("Where do you put your toys?", "I put them away."),
       qa("Can you put down the box?", "Yes, I can."),
       qa("Did you put away the books?", "Yes, I did.")]),

    L("Phrasal Verbs with MAKE",
      [("make", "🔨"), ("sure", "✅"), ("find", "🔍"), ("out", "🔎"), ("up", "🤝"), ("safe", "🦺")],
      "Phrasal verbs: make, find out",
      ["Make sure you are safe.", "They made up.", "I want to find out.",
       "Let's find out the answer.", "She made up a story.", "Please make sure it works."],
      [g("Make ___ you are safe.", ["sure", "up"], "sure", "✅"),
       g("I want to find ___.", ["out", "up"], "out", "🔍"),
       g("She made ___ a story.", ["up", "sure"], "up", "📖"),
       g("Let's find ___ the answer.", ["out", "on"], "out", "🔎")],
      [t("make -> he form", "make", ["makes", "makees", "make"], "makes"),
       t("make -> past", "make", ["made", "maked", "make"], "made"),
       t("find -> past", "find", ["found", "finded", "find"], "found")],
      [f("She makes up a story.", "She make up a story.", "📖"),
       f("They made up quickly.", "They maked up quickly.", "🤝"),
       f("I found out the answer.", "I finded out the answer.", "🔍"),
       f("Make sure it is safe.", "Makes sure it is safe.", "✅")],
      srt("make UP", "make SURE",
          [tok("make up a story", "A", "📖"), tok("make up a game", "A", "🎲"), tok("make up a word", "A", "🔤"),
           tok("make sure it works", "B", "✅"), tok("make sure it fits", "B", "🧩"), tok("make sure it is safe", "B", "🦺")]),
      [qa("Did you find out the answer?", "Yes, I did."),
       qa("What did she make up?", "She made up a story."),
       qa("Are you sure?", "Yes, I am sure."),
       qa("Did they make up?", "Yes, they made up.")]),

    L("Phrasal Verbs with LOOK",
      [("look", "👀"), ("after", "🐾"), ("for", "🔍"), ("out", "⚠️"), ("keys", "🔑"), ("cat", "🐱")],
      "Phrasal verbs: look",
      ["I look after my cat.", "Look out for the car!", "I am looking for my keys.",
       "Please look after the dog.", "I look up new words."],
      [g("I look ___ my cat.", ["after", "out"], "after", "🐱"),
       g("I am looking ___ my keys.", ["for", "after"], "for", "🔑"),
       g("Look ___ for the car!", ["out", "up"], "out", "⚠️"),
       g("I look ___ new words.", ["up", "after"], "up", "📖")],
      [t("look -> he form", "look", ["looks", "lookes", "look"], "looks"),
       t("look -> past", "look", ["looked", "lookd", "look"], "looked"),
       t("look -> -ing", "look", ["looking", "lookking", "lookin"], "looking")],
      [f("She looks after her cat.", "She look after her cat.", "🐱"),
       f("He looks for his keys.", "He look for his keys.", "🔑"),
       f("Look out for the car!", "Looks out for the car!", "⚠️"),
       f("I am looking for it.", "I am lookking for it.", "🔍")],
      srt("look AFTER", "look FOR",
          [tok("look after my cat", "A", "🐱"), tok("look after the dog", "A", "🐕"), tok("look after the baby", "A", "👶"),
           tok("look for my keys", "B", "🔑"), tok("look for my book", "B", "📕"), tok("look for the door", "B", "🚪")]),
      [qa("What are you looking for?", "I am looking for my keys."),
       qa("Do you look after your cat?", "Yes, I do."),
       qa("Can you look after the dog?", "Yes, I can."),
       qa("Where do you look up words?", "In a book.")]),

    L("Common Idioms & Expressions",
      [("cake", "🍰"), ("leg", "🦵"), ("rain", "🌧️"), ("horse", "🐴"), ("easy", "😌"), ("luck", "🍀")],
      "Idioms and their meaning",
      ["It's a piece of cake.", "Break a leg!", "It's raining cats and dogs.",
       "Hold your horses!", "This test is easy.", "Good luck to you!"],
      [g("It's a piece of ___.", ["cake", "leg"], "cake", "🍰"),
       g("Break a ___!", ["leg", "cake"], "leg", "🦵"),
       g("It's raining cats and ___.", ["dogs", "cats"], "dogs", "🐕"),
       g("Hold your ___!", ["horses", "cats"], "horses", "🐴")],
      [t("cake -> many", "cake", ["cakes", "caks", "cake"], "cakes"),
       t("leg -> many", "leg", ["legs", "leges", "leg"], "legs"),
       t("horse -> many", "horse", ["horses", "horss", "horse"], "horses")],
      [f("It's a piece of cake.", "It's a piece of cakes.", "🍰"),
       f("Break a leg!", "Break a legs!", "🦵"),
       f("Hold your horses!", "Hold your horse!", "🐴")],
      srt("means EASY", "means GOOD LUCK",
          [tok("piece of cake", "A", "🍰"), tok("easy as pie", "A", "🥧"), tok("no problem", "A", "👍"),
           tok("break a leg", "B", "🦵"), tok("fingers crossed", "B", "🤞"), tok("best of luck", "B", "🍀")]),
      [qa("What does 'a piece of cake' mean?", "It means very easy."),
       qa("What does 'break a leg' mean?", "It means good luck."),
       qa("What does 'raining cats and dogs' mean?", "It is raining hard."),
       qa("What does 'hold your horses' mean?", "It means please wait.")]),

    L("Common Collocations",
      [("cake", "🍰"), ("photo", "📷"), ("bed", "🛏️"), ("fun", "🎉"), ("lunch", "🥪"), ("mistake", "❌")],
      "Collocations: make, do, have, take",
      ["I make a cake.", "I do my homework.", "We have breakfast.",
       "She takes a photo.", "Please make your bed.", "We have lots of fun."],
      [g("I ___ my homework.", ["do", "make"], "do", "📚"),
       g("We ___ breakfast.", ["have", "do"], "have", "🍳"),
       g("She ___ a photo.", ["takes", "makes"], "takes", "📷"),
       g("I ___ a mistake.", ["make", "do"], "make", "❌")],
      [t("make -> he form", "make", ["makes", "makees", "make"], "makes"),
       t("do -> he form", "do", ["does", "dos", "do"], "does"),
       t("have -> he form", "have", ["has", "haves", "have"], "has")],
      [f("I do my homework.", "I make my homework.", "📚"),
       f("She takes a photo.", "She makes a photo.", "📷"),
       f("We have breakfast.", "We do breakfast.", "🍳"),
       f("I make a mistake.", "I do a mistake.", "❌")],
      srt("MAKE", "DO",
          [tok("make a cake", "A", "🍰"), tok("make your bed", "A", "🛏️"), tok("make a mistake", "A", "❌"),
           tok("do homework", "B", "📚"), tok("do the dishes", "B", "🍽️"), tok("do your best", "B", "💪")]),
      [qa("What are you doing?", "I am doing my homework."),
       qa("Can you take a photo?", "Yes, I can."),
       qa("Did you make a cake?", "Yes, I made a cake."),
       qa("What do you have for breakfast?", "I have eggs.")]),

    L("Linking Words",
      [("and", "➕"), ("but", "↔️"), ("because", "🤔"), ("so", "➡️"), ("or", "🔀"), ("tired", "😴")],
      "Linking words: and, but, so, because, or",
      ["I was tired, so I slept.", "I like tea but not coffee.", "I like cats and dogs.",
       "I stayed home because it rained.", "Do you want tea or milk?"],
      [g("I was tired, ___ I slept.", ["so", "but"], "so", "😴"),
       g("I like tea ___ not coffee.", ["but", "and"], "but", "🍵"),
       g("I like cats ___ dogs.", ["and", "but"], "and", "🐱"),
       g("I stayed home ___ it rained.", ["because", "so"], "because", "🌧️")],
      [t("sleep -> past", "sleep", ["slept", "sleeped", "sleep"], "slept"),
       t("rain -> past", "rain", ["rained", "raind", "rain"], "rained"),
       t("like -> he form", "like", ["likes", "likees", "like"], "likes")],
      [f("I like cats and dogs.", "I like cats but dogs.", "🐱"),
       f("I stayed home because it rained.", "I stayed home because it rain.", "🌧️"),
       f("I like tea but not coffee.", "I like tea because not coffee.", "🍵"),
       f("I was tired, so I slept.", "I was tired, so I sleeped.", "😴")],
      srt("use AND", "use BUT",
          [tok("cats and dogs", "A", "🐱"), tok("you and me", "A", "🤝"), tok("bread and butter", "A", "🍞"),
           tok("small but strong", "B", "💪"), tok("cheap but good", "B", "💰"), tok("slow but sure", "B", "🐢")]),
      [qa("Why did you sleep?", "Because I was tired."),
       qa("Do you like tea or coffee?", "I like tea."),
       qa("Do you like cats and dogs?", "Yes, I like both."),
       qa("Were you tired?", "Yes, so I slept.")]),

    L("Time Expressions",
      [("today", "📅"), ("now", "⏰"), ("soon", "⏳"), ("later", "🕐"), ("ago", "⏪"), ("yesterday", "📆")],
      "Time words: now, soon, later, ago",
      ["I will come soon.", "She left an hour ago.", "I am busy now.",
       "We will play later.", "I saw him yesterday.", "We have a test today."],
      [g("She left an hour ___.", ["ago", "later"], "ago", "⏪"),
       g("I will come ___.", ["soon", "ago"], "soon", "⏳"),
       g("I saw him ___.", ["yesterday", "tomorrow"], "yesterday", "📆"),
       g("I am busy ___.", ["now", "ago"], "now", "⏰")],
      [t("come -> past", "come", ["came", "comed", "come"], "came"),
       t("leave -> past", "leave", ["left", "leaved", "leave"], "left"),
       t("see -> past", "see", ["saw", "seed", "see"], "saw")],
      [f("I will come soon.", "I will come ago.", "⏳"),
       f("She left an hour ago.", "She left an hour soon.", "⏪"),
       f("I saw him yesterday.", "I see him yesterday.", "📆")],
      srt("PAST", "FUTURE",
          [tok("yesterday", "A", "📆"), tok("an hour ago", "A", "⏪"), tok("last week", "A", "🗓️"),
           tok("tomorrow", "B", "📅"), tok("soon", "B", "⏳"), tok("later", "B", "🕐")]),
      [qa("When will you come?", "I will come soon."),
       qa("When did she leave?", "An hour ago."),
       qa("What did you do yesterday?", "I played outside."),
       qa("Are you busy now?", "Yes, I am busy.")]),

    L("Prepositions of Time",
      [("night", "🌙"), ("noon", "🕛"), ("summer", "☀️"), ("winter", "❄️"), ("Monday", "📅"), ("July", "🗓️")],
      "Prepositions of time: at, on, in",
      ["I sleep at night.", "We meet on Monday.", "It is hot in summer.",
       "School starts at nine.", "My birthday is in July.", "We rest on Sunday."],
      [g("I sleep ___ night.", ["at", "on"], "at", "🌙"),
       g("We meet ___ Monday.", ["on", "in"], "on", "📅"),
       g("It is hot ___ summer.", ["in", "at"], "in", "☀️"),
       g("My birthday is ___ July.", ["in", "on"], "in", "🗓️")],
      [t("meet -> past", "meet", ["met", "meeted", "meet"], "met"),
       t("sleep -> past", "sleep", ["slept", "sleeped", "sleep"], "slept"),
       t("start -> he form", "start", ["starts", "startes", "start"], "starts")],
      [f("I sleep at night.", "I sleep on night.", "🌙"),
       f("We meet on Monday.", "We meet in Monday.", "📅"),
       f("It is hot in summer.", "It is hot at summer.", "☀️"),
       f("My birthday is in July.", "My birthday is on July.", "🗓️")],
      srt("ON (days)", "IN (months)",
          [tok("on Monday", "A", "📅"), tok("on Sunday", "A", "🗓️"), tok("on Friday", "A", "📆"),
           tok("in July", "B", "🏖️"), tok("in May", "B", "🌸"), tok("in June", "B", "☀️")]),
      [qa("When do you sleep?", "I sleep at night."),
       qa("When do we meet?", "On Monday."),
       qa("When is your birthday?", "In July."),
       qa("When does school start?", "At nine.")]),
])
