# -*- coding: utf-8 -*-
"""
WORLD 17 — Quantifier Quay  (advanced, functional English)

Grammar arc: prepositions of place & movement, giving directions,
likes/dislikes, comparisons, habits & routines, daily schedules, health
patterns, polite food talk, and recipe imperatives. Functional English —
but every level still teaches a PATTERN, not a bare vocabulary list.
"""

from grammar_helpers import g, t, f, tok, srt, qa, L, W


WORLD = W("Quantifier Quay", "Prepositions, comparisons & routines", [

    # ----------------------------------------------------------------------
    # 1. Prepositions of Place — in / on / under / next to / between / behind
    # ----------------------------------------------------------------------
    L("Prepositions of Place",
      [("cat", "🐱"), ("box", "📦"), ("cup", "☕"), ("ball", "⚽"), ("table", "🪑"), ("chair", "💺")],
      "Prepositions of place",
      ["The cat is under the table.", "The ball is in the box.",
       "The cup is on the table.", "The cat is behind the chair.",
       "The ball is next to the box.", "The cup is between the books."],
      [g("The ball is ___ the box.", ["in", "on"], "in", "⚽"),
       g("The cup is ___ the table.", ["on", "under"], "on", "☕"),
       g("The cat is ___ the table.", ["under", "on"], "under", "🐱"),
       g("The cat is ___ the chair.", ["behind", "between"], "behind", "💺")],
      [t("one cat -> many...?", "cat", ["cats", "cates", "cat"], "cats"),
       t("one box -> many...?", "box", ["boxs", "boxes", "box"], "boxes"),
       t("one cup -> many...?", "cup", ["cups", "cupes", "cup"], "cups")],
      [f("The cat is under the table.", "The cat are under the table.", "🐱"),
       f("The ball is in the box.", "The ball are in the box.", "⚽"),
       f("The cup is on the table.", "The cup are on the table.", "☕"),
       f("The books are on the desk.", "The books is on the desk.", "📚")],
      srt("in / on", "under / behind",
          [tok("in the box", "A", "📦"), tok("on the table", "A", "🪑"), tok("in the cup", "A", "☕"),
           tok("under the bed", "B", "🛏️"), tok("behind the door", "B", "🚪"), tok("under the chair", "B", "💺")]),
      [qa("Where is the cat?", "It is under the table."),
       qa("Where is the ball?", "It is in the box."),
       qa("Is the cup on the table?", "Yes, it is."),
       qa("Is the cat behind the chair?", "No, it is not.")]),

    # ----------------------------------------------------------------------
    # 2. Prepositions of Movement — to / from / into / across / through / along
    # ----------------------------------------------------------------------
    L("Prepositions of Movement",
      [("walk", "🚶"), ("road", "🛣️"), ("door", "🚪"), ("bridge", "🌉"), ("park", "🌳"), ("river", "🏞️")],
      "Prepositions of movement",
      ["Walk to the door.", "Go across the road.", "We walk into the park.",
       "The dog runs through the door.", "She walks along the river.",
       "We walk across the bridge."],
      [g("Walk ___ the room. (go inside)", ["into", "across"], "into", "🚪"),
       g("Go ___ the road. (cross it)", ["across", "along"], "across", "🛣️"),
       g("Walk ___ the tunnel. (in and out)", ["through", "from"], "through", "🚇"),
       g("Come ___ the shop. (leave it)", ["from", "into"], "from", "🏪")],
      [t("one road -> many...?", "road", ["roads", "roades", "road"], "roads"),
       t("one door -> many...?", "door", ["doors", "dores", "door"], "doors"),
       t("one park -> many...?", "park", ["parks", "parkes", "park"], "parks")],
      [f("She walks to the door.", "She walk to the door.", "🚪"),
       f("He runs across the road.", "He run across the road.", "🛣️"),
       f("They walk into the park.", "They walks into the park.", "🌳"),
       f("The dog runs through the door.", "The dog run through the door.", "🐕")],
      srt("to / into", "across / through",
          [tok("to the door", "A", "🚪"), tok("into the park", "A", "🌳"), tok("into the room", "A", "🚪"),
           tok("across the road", "B", "🛣️"), tok("through the door", "B", "🚪"), tok("across the river", "B", "🏞️")]),
      [qa("Where do you walk?", "I walk to the park."),
       qa("How do you cross the road?", "I go across it."),
       qa("Where does the dog run?", "It runs through the door."),
       qa("Do you walk to school?", "Yes, I do.")]),

    # ----------------------------------------------------------------------
    # 3. Directions & Instructions — turn left/right, go straight, stop
    # ----------------------------------------------------------------------
    L("Directions & Instructions",
      [("left", "⬅️"), ("right", "➡️"), ("stop", "🛑"), ("straight", "⬆️"), ("turn", "🔄"), ("road", "🛣️")],
      "Directions (imperatives)",
      ["Turn left at the shop.", "Go straight ahead.", "Turn right here.",
       "Stop at the light.", "Go straight and turn left.", "Please turn right."],
      [g("Turn ___ at the shop.", ["left", "right"], "left", "⬅️"),
       g("Turn ___ here.", ["right", "left"], "right", "➡️"),
       g("___ at the light.", ["Stop", "Turn"], "Stop", "🛑"),
       g("Go ___ ahead.", ["straight", "turn"], "straight", "⬆️")],
      [t("one shop -> many...?", "shop", ["shops", "shopes", "shop"], "shops"),
       t("one light -> many...?", "light", ["lights", "lightes", "light"], "lights"),
       t("one road -> many...?", "road", ["roads", "roades", "road"], "roads")],
      [f("Turn left at the shop.", "Turns left at the shop.", "⬅️"),
       f("Go straight ahead.", "Goes straight ahead.", "⬆️"),
       f("Please turn right.", "Please turns right.", "➡️"),
       f("Stop at the light.", "Stops at the light.", "🛑")],
      srt("turn", "go straight",
          [tok("turn left", "A", "⬅️"), tok("turn right", "A", "➡️"), tok("turn here", "A", "🔄"),
           tok("go straight", "B", "⬆️"), tok("go ahead", "B", "⬆️"), tok("keep going", "B", "🚶")]),
      [qa("Where is the shop?", "Turn left at the light."),
       qa("How do I get there?", "Go straight ahead."),
       qa("Is it on the right?", "Yes, turn right."),
       qa("Where is the park?", "Turn right at the shop.")]),

    # ----------------------------------------------------------------------
    # 4. Expressing Likes & Dislikes — like/love/enjoy/hate + noun or -ing
    # ----------------------------------------------------------------------
    L("Expressing Likes & Dislikes",
      [("reading", "📖"), ("rain", "🌧️"), ("music", "🎵"), ("swimming", "🏊"), ("cake", "🍰"), ("dogs", "🐕")],
      "like / love / hate + -ing",
      ["I love reading.", "I don't like rain.", "She likes music.",
       "We enjoy swimming.", "I hate cold days.", "He loves dogs."],
      [g("I love ___.", ["reading", "read"], "reading", "📖"),
       g("We enjoy ___.", ["swimming", "swim"], "swimming", "🏊"),
       g("She ___ music.", ["likes", "like"], "likes", "🎵"),
       g("I don't ___ rain.", ["like", "likes"], "like", "🌧️")],
      [t("read + ing ->", "read", ["reading", "readding", "reads"], "reading"),
       t("swim + ing ->", "swim", ["swiming", "swimming", "swimms"], "swimming"),
       t("play + ing ->", "play", ["playing", "plaing", "playes"], "playing")],
      [f("I love reading.", "I loves reading.", "📖"),
       f("She likes music.", "She like music.", "🎵"),
       f("We enjoy swimming.", "We enjoy swim.", "🏊"),
       f("He loves dogs.", "He love dogs.", "🐕")],
      srt("love it", "hate it",
          [tok("I love it", "A", "❤️"), tok("I like it", "A", "🙂"), tok("I enjoy it", "A", "😄"),
           tok("I hate it", "B", "😖"), tok("I don't like it", "B", "🙁"), tok("I dislike it", "B", "😒")]),
      [qa("Do you like rain?", "No, I don't."),
       qa("What do you love?", "I love reading."),
       qa("Does she like music?", "Yes, she does."),
       qa("Do you enjoy swimming?", "Yes, I do.")]),

    # ----------------------------------------------------------------------
    # 5. Making Comparisons — -er than / as ... as
    # ----------------------------------------------------------------------
    L("Making Comparisons",
      [("fast", "🏎️"), ("tall", "📏"), ("big", "🐘"), ("small", "🐭"), ("car", "🚗"), ("bike", "🚲")],
      "Comparatives (-er than)",
      ["A car is faster than a bike.", "She is as tall as me.",
       "An elephant is bigger than a mouse.", "A mouse is smaller than a cat.",
       "This box is heavier than that one.", "He is as fast as you."],
      [g("A car is ___ than a bike.", ["faster", "fast"], "faster", "🚗"),
       g("An elephant is ___ than a mouse.", ["bigger", "big"], "bigger", "🐘"),
       g("A mouse is smaller ___ a cat.", ["than", "as"], "than", "🐭"),
       g("She is ___ tall as me.", ["as", "than"], "as", "📏")],
      [t("fast + er ->", "fast", ["faster", "fastter", "fasterr"], "faster"),
       t("big + er ->", "big", ["biger", "bigger", "bigest"], "bigger"),
       t("small + er ->", "small", ["smaller", "smallerr", "smallor"], "smaller")],
      [f("A car is faster than a bike.", "A car is faster then a bike.", "🚗"),
       f("She is as tall as me.", "She is so tall as me.", "📏"),
       f("An elephant is bigger than a mouse.", "An elephant is big than a mouse.", "🐘"),
       f("A mouse is smaller than a cat.", "A mouse is smaller than an cat.", "🐭")],
      srt("-er than", "as ... as",
          [tok("faster than", "A", "🏎️"), tok("bigger than", "A", "🐘"), tok("taller than", "A", "📏"),
           tok("as tall as", "B", "📏"), tok("as big as", "B", "🐘"), tok("as fast as", "B", "🏎️")]),
      [qa("Which is faster, a car or a bike?", "A car is faster."),
       qa("Is an elephant big?", "Yes, it is very big."),
       qa("Are you as tall as me?", "Yes, I am."),
       qa("Which is smaller, a mouse or a cat?", "A mouse is smaller.")]),

    # ----------------------------------------------------------------------
    # 6. Habits & Routines — present simple + frequency adverbs
    # ----------------------------------------------------------------------
    L("Habits & Routines",
      [("breakfast", "🍳"), ("school", "🏫"), ("milk", "🥛"), ("bus", "🚌"), ("book", "📖"), ("teeth", "🦷")],
      "Frequency adverbs",
      ["I always eat breakfast.", "She usually walks to school.",
       "We often play outside.", "He never drinks milk.",
       "I sometimes read a book.", "They always brush their teeth."],
      [g("She usually ___ to school.", ["walks", "walk"], "walks", "🏫"),
       g("He never ___ milk.", ["drinks", "drink"], "drinks", "🥛"),
       g("We often ___ outside.", ["play", "plays"], "play", "⚽"),
       g("I always ___ breakfast.", ["eat", "eats"], "eat", "🍳")],
      [t("I walk, she ->", "walk", ["walks", "walkes", "walk"], "walks"),
       t("I go, she ->", "go", ["goes", "gos", "go"], "goes"),
       t("I brush, she ->", "brush", ["brushes", "brushs", "brush"], "brushes")],
      [f("She usually walks to school.", "She usually walk to school.", "🏫"),
       f("He never drinks milk.", "He never drink milk.", "🥛"),
       f("I always eat breakfast.", "I always eats breakfast.", "🍳"),
       f("They often play outside.", "They often plays outside.", "⚽")],
      srt("a lot", "not often",
          [tok("always", "A", "✅"), tok("usually", "A", "👍"), tok("often", "A", "🔁"),
           tok("never", "B", "🚫"), tok("rarely", "B", "🔻"), tok("hardly ever", "B", "➖")]),
      [qa("Do you eat breakfast?", "Yes, I always do."),
       qa("How does she go to school?", "She usually walks."),
       qa("Does he drink milk?", "No, he never does."),
       qa("What do you do after school?", "I often play outside.")]),

    # ----------------------------------------------------------------------
    # 7. Describing Daily Schedules — time + present simple (at / in)
    # ----------------------------------------------------------------------
    L("Describing Daily Schedules",
      [("clock", "🕐"), ("morning", "🌅"), ("noon", "☀️"), ("lunch", "🍱"), ("night", "🌙"), ("seven", "7️⃣")],
      "Times: at / in",
      ["I get up at seven.", "At noon I have lunch.", "I go to bed at night.",
       "In the morning I eat.", "She starts school at eight.",
       "We watch TV in the evening."],
      [g("I get up ___ seven.", ["at", "in"], "at", "🕖"),
       g("___ the morning I eat.", ["In", "At"], "In", "🌅"),
       g("I go to bed ___ night.", ["at", "in"], "at", "🌙"),
       g("She starts school ___ eight.", ["at", "on"], "at", "🏫")],
      [t("I get, she ->", "get", ["gets", "getes", "get"], "gets"),
       t("I have, she ->", "have", ["has", "haves", "have"], "has"),
       t("I start, she ->", "start", ["starts", "startes", "start"], "starts")],
      [f("I get up at seven.", "I get up in seven.", "🕖"),
       f("At noon I have lunch.", "At noon I has lunch.", "🍱"),
       f("I go to bed at night.", "I go to bed in night.", "🌙"),
       f("In the morning I eat.", "At the morning I eat.", "🌅")],
      srt("at (a time)", "in (part of day)",
          [tok("at seven", "A", "🕖"), tok("at noon", "A", "☀️"), tok("at night", "A", "🌙"),
           tok("in the morning", "B", "🌅"), tok("in the evening", "B", "🌆"), tok("in the afternoon", "B", "🌤️")]),
      [qa("What time do you get up?", "I get up at seven."),
       qa("When do you have lunch?", "At noon."),
       qa("When do you go to bed?", "At night."),
       qa("What do you do in the morning?", "I eat breakfast.")]),

    # ----------------------------------------------------------------------
    # 8. Health & Illnesses — I have a... / You should...
    # ----------------------------------------------------------------------
    L("Health & Illnesses",
      [("cold", "🤧"), ("head", "🤕"), ("rest", "🛌"), ("doctor", "👨‍⚕️"), ("water", "💧"), ("sleep", "😴")],
      "I have a... / You should...",
      ["I have a cold.", "You should rest.", "My head hurts.",
       "You should see a doctor.", "I have a headache.", "You should drink water."],
      [g("I have ___ cold.", ["a", "an"], "a", "🤧"),
       g("You should ___.", ["rest", "rests"], "rest", "🛌"),
       g("My head ___.", ["hurts", "hurt"], "hurts", "🤕"),
       g("You should ___ water.", ["drink", "drinks"], "drink", "💧")],
      [t("one doctor -> many...?", "doctor", ["doctors", "doctores", "doctor"], "doctors"),
       t("I rest, she ->", "rest", ["rests", "restes", "rest"], "rests"),
       t("one cold -> many...?", "cold", ["colds", "coldes", "cold"], "colds")],
      [f("I have a cold.", "I have an cold.", "🤧"),
       f("You should rest.", "You should rests.", "🛌"),
       f("My head hurts.", "My head hurt.", "🤕"),
       f("You should drink water.", "You should drinks water.", "💧")],
      srt("the problem", "the advice",
          [tok("I have a cold", "A", "🤧"), tok("My head hurts", "A", "🤕"), tok("I feel sick", "A", "🤢"),
           tok("You should rest", "B", "🛌"), tok("You should sleep", "B", "😴"), tok("See a doctor", "B", "👨‍⚕️")]),
      [qa("What is wrong?", "I have a cold."),
       qa("How do you feel?", "My head hurts."),
       qa("What should I do?", "You should rest."),
       qa("Should I see a doctor?", "Yes, you should.")]),

    # ----------------------------------------------------------------------
    # 9. Food & Drink (patterns) — Would you like...? / I'd like...
    # ----------------------------------------------------------------------
    L("Food & Drink",
      [("cake", "🍰"), ("juice", "🧃"), ("tea", "🍵"), ("water", "💧"), ("apple", "🍎"), ("milk", "🥛")],
      "Would you like...?",
      ["Would you like some cake?", "I'd like some juice, please.",
       "Would you like a drink?", "I would like some water.",
       "No, thank you.", "I'd like an apple, please."],
      [g("Would you ___ some cake?", ["like", "likes"], "like", "🍰"),
       g("I'd like ___ apple.", ["an", "a"], "an", "🍎"),
       g("Would you like ___ water?", ["some", "an"], "some", "💧"),
       g("I ___ like some tea.", ["would", "am"], "would", "🍵")],
      [t("one cake -> many...?", "cake", ["cakes", "cakees", "cake"], "cakes"),
       t("one apple -> many...?", "apple", ["apples", "appls", "apple"], "apples"),
       t("one drink -> many...?", "drink", ["drinks", "drinkes", "drink"], "drinks")],
      [f("Would you like some cake?", "Would you likes some cake?", "🍰"),
       f("I'd like some juice.", "I'd like an juice.", "🧃"),
       f("Would you like a drink?", "Would you like an drink?", "🥤"),
       f("I would like some water.", "I would likes some water.", "💧")],
      srt("Would you like?", "I'd like",
          [tok("Would you like tea?", "A", "🍵"), tok("Would you like cake?", "A", "🍰"), tok("Would you like juice?", "A", "🧃"),
           tok("I'd like some water.", "B", "💧"), tok("I'd like an apple.", "B", "🍎"), tok("I'd like some milk.", "B", "🥛")]),
      [qa("Would you like some cake?", "Yes, please."),
       qa("Would you like some tea?", "No, thank you."),
       qa("What would you like?", "I'd like some juice."),
       qa("Would you like an apple?", "Yes, I'd love one.")]),

    # ----------------------------------------------------------------------
    # 10. Cooking & Recipes (imperatives) — mix / add / bake / stir
    # ----------------------------------------------------------------------
    L("Cooking & Recipes",
      [("eggs", "🥚"), ("sugar", "🍬"), ("flour", "🌾"), ("milk", "🥛"), ("cake", "🍰"), ("mix", "🥣")],
      "Recipe imperatives",
      ["Mix the eggs.", "Add some sugar.", "Bake for ten minutes.",
       "Stir the milk slowly.", "Pour the milk in.", "Cut the cake."],
      [g("___ the eggs.", ["Mix", "Mixes"], "Mix", "🥚"),
       g("Add ___ sugar.", ["some", "a"], "some", "🍬"),
       g("___ for ten minutes.", ["Bake", "Bakes"], "Bake", "⏲️"),
       g("Stir the ___ slowly.", ["milk", "milks"], "milk", "🥛")],
      [t("one egg -> many...?", "egg", ["eggs", "egges", "egg"], "eggs"),
       t("one cake -> many...?", "cake", ["cakes", "cakees", "cake"], "cakes"),
       t("one minute -> many...?", "minute", ["minutes", "minuts", "minute"], "minutes")],
      [f("Mix the eggs.", "Mixes the eggs.", "🥚"),
       f("Add some sugar.", "Adds some sugar.", "🍬"),
       f("Bake for ten minutes.", "Bakes for ten minutes.", "⏲️"),
       f("Stir the milk slowly.", "Stirs the milk slowly.", "🥛")],
      srt("mix it", "bake it",
          [tok("mix the eggs", "A", "🥚"), tok("stir the milk", "A", "🥛"), tok("add sugar", "A", "🍬"),
           tok("bake the cake", "B", "🍰"), tok("heat the oven", "B", "🔥"), tok("cook the eggs", "B", "🍳")]),
      [qa("What do I do first?", "Mix the eggs."),
       qa("What comes next?", "Add some sugar."),
       qa("How long do I bake it?", "Bake for ten minutes."),
       qa("Is the cake ready?", "Yes, it is done.")]),
])
