# -*- coding: utf-8 -*-
from grammar_helpers import g, t, f, tok, srt, qa, L, W

# ===========================================================================
# WORLD 18 — Polite Plaza  (Advanced · functional & social English)
# Arc: shopping/prices, jobs (a/an), work & school present simple,
# modals of deduction, preferences, permission, offers/suggestions, advice.
# Every level teaches ONE polite pattern; sentences are short and natural.
# ===========================================================================
WORLD = W("Polite Plaza", "Polite & social language", [

    L("Shopping Phrases",
      [("shop", "🏪"), ("bag", "🎒"), ("price", "🏷️"), ("money", "💵"), ("buy", "🛒"), ("pay", "💳")],
      "How much...? / Can I have...?",
      ["How much is this?", "How much are these?", "Can I have a bag?",
       "Can I have this, please?", "How much is that hat?", "Can I pay by card?"],
      [g("How much ___ this?", ["is", "are"], "is", "🏷️"),
       g("How much ___ these?", ["is", "are"], "are", "🏷️"),
       g("Can I ___ a bag, please?", ["have", "has"], "have", "🎒"),
       g("How ___ is this?", ["much", "many"], "much", "💵")],
      [t("one shop -> many...?", "shop", ["shops", "shopes", "shop"], "shops"),
       t("one price -> many...?", "price", ["prices", "pricees", "price"], "prices"),
       t("one bag -> many...?", "bag", ["bags", "baggs", "bag"], "bags")],
      [f("How much is this?", "How much are this?", "🏷️"),
       f("How much are these?", "How much is these?", "🏷️"),
       f("Can I have a bag?", "Can I have an bag?", "🎒")],
      srt("much", "many",
          [tok("water", "A", "💧"), tok("money", "A", "💵"), tok("milk", "A", "🥛"),
           tok("apples", "B", "🍎"), tok("bags", "B", "🎒"), tok("books", "B", "📚")]),
      [qa("How much is this?", "It is five dollars."),
       qa("Can I have a bag, please?", "Yes, here you are."),
       qa("How much are these?", "They are ten dollars."),
       qa("Can I pay by card?", "Yes, of course.")]),

    L("Money & Prices",
      [("cost", "💰"), ("price", "🏷️"), ("coin", "🪙"), ("dollar", "💵"), ("cheap", "🤑"), ("change", "💴")],
      "It costs / It's ... dollars",
      ["It costs five dollars.", "How much does it cost?", "It's ten dollars.",
       "The book costs three dollars.", "How much do they cost?", "It costs a lot."],
      [g("It ___ five dollars.", ["costs", "cost"], "costs", "💵"),
       g("How much does it ___?", ["cost", "costs"], "cost", "💰"),
       g("They ___ ten dollars.", ["cost", "costs"], "cost", "🪙"),
       g("How much ___ it cost?", ["does", "do"], "does", "🏷️")],
      [t("one price -> many...?", "price", ["prices", "pricees", "price"], "prices"),
       t("one coin -> many...?", "coin", ["coins", "coines", "coin"], "coins"),
       t("one dollar -> many...?", "dollar", ["dollars", "dollares", "dollar"], "dollars")],
      [f("It costs five dollars.", "It cost five dollars.", "💵"),
       f("How much does it cost?", "How much does it costs?", "💰"),
       f("They cost ten dollars.", "They costs ten dollars.", "🪙")],
      srt("costs", "cost",
          [tok("It", "A", "🧢"), tok("The bag", "A", "🎒"), tok("This hat", "A", "👒"),
           tok("They", "B", "👟"), tok("The shoes", "B", "👞"), tok("These books", "B", "📚")]),
      [qa("How much does it cost?", "It costs five dollars."),
       qa("How much is the hat?", "It's ten dollars."),
       qa("How much do the shoes cost?", "They cost twenty dollars."),
       qa("Is it cheap?", "Yes, it is.")]),

    L("Jobs & Occupations",
      [("doctor", "🩺"), ("nurse", "💉"), ("pilot", "✈️"), ("chef", "🍳"), ("actor", "🎭"), ("artist", "🎨")],
      "a / an + job",
      ["She is a doctor.", "He is an artist.", "I am a nurse.",
       "She is a pilot.", "He is an actor.", "My mom is a chef."],
      [g("She is ___ doctor.", ["a", "an"], "a", "🩺"),
       g("He is ___ artist.", ["a", "an"], "an", "🎨"),
       g("He is ___ actor.", ["a", "an"], "an", "🎭"),
       g("He is ___ pilot.", ["a", "an"], "a", "✈️")],
      [t("one doctor -> many...?", "doctor", ["doctors", "doctores", "doctor"], "doctors"),
       t("one nurse -> many...?", "nurse", ["nurses", "nurss", "nurse"], "nurses"),
       t("one chef -> many...?", "chef", ["chefs", "chefes", "chef"], "chefs")],
      [f("She is a doctor.", "She is an doctor.", "🩺"),
       f("He is an artist.", "He is a artist.", "🎨"),
       f("He is an actor.", "He is a actor.", "🎭")],
      srt("a", "an",
          [tok("doctor", "A", "🩺"), tok("nurse", "A", "💉"), tok("pilot", "A", "✈️"),
           tok("artist", "B", "🎨"), tok("actor", "B", "🎭"), tok("engineer", "B", "🛠️")]),
      [qa("What does she do?", "She is a doctor."),
       qa("What does he do?", "He is an artist."),
       qa("What do you do?", "I am a nurse."),
       qa("Is he a pilot?", "Yes, he is.")]),

    L("Work & Workplace",
      [("office", "🏢"), ("work", "💼"), ("boss", "👔"), ("team", "👥"), ("email", "📧"), ("desk", "🪑")],
      "work / works (present simple)",
      ["I work in an office.", "She has a meeting.", "He works with a team.",
       "We send emails.", "She works at a desk.", "My dad works in a shop."],
      [g("She ___ in an office.", ["works", "work"], "works", "🏢"),
       g("I ___ with a team.", ["work", "works"], "work", "👥"),
       g("She ___ a meeting.", ["has", "have"], "has", "📅"),
       g("They ___ at a desk.", ["work", "works"], "work", "🪑")],
      [t("one office -> many...?", "office", ["offices", "officees", "office"], "offices"),
       t("one boss -> many...?", "boss", ["bosses", "bosss", "boss"], "bosses"),
       t("one email -> many...?", "email", ["emails", "emailes", "email"], "emails")],
      [f("She works in an office.", "She work in an office.", "🏢"),
       f("He has a meeting.", "He have a meeting.", "📅"),
       f("I work with a team.", "I works with a team.", "👥")],
      srt("work", "works",
          [tok("I", "A", "🙋"), tok("We", "A", "👥"), tok("They", "A", "👨‍👩‍👧"),
           tok("He", "B", "👨"), tok("She", "B", "👩"), tok("My dad", "B", "🧔")]),
      [qa("Where do you work?", "I work in an office."),
       qa("What does she do at work?", "She has a meeting."),
       qa("Do you work in a team?", "Yes, we do."),
       qa("Does he work here?", "No, he doesn't.")]),

    L("School & Education",
      [("school", "🏫"), ("class", "🧑‍🏫"), ("lesson", "📖"), ("teacher", "👩‍🏫"), ("book", "📚"), ("test", "📝")],
      "have / do at school",
      ["We have English on Monday.", "I do my homework.", "She has a test today.",
       "We study in class.", "He does his homework.", "I read my book."],
      [g("We ___ English on Monday.", ["have", "has"], "have", "📖"),
       g("I ___ my homework.", ["do", "does"], "do", "📝"),
       g("She ___ a test today.", ["has", "have"], "has", "🏫"),
       g("He ___ his homework.", ["does", "do"], "does", "📚")],
      [t("one school -> many...?", "school", ["schools", "schooles", "school"], "schools"),
       t("one lesson -> many...?", "lesson", ["lessons", "lessones", "lesson"], "lessons"),
       t("one class -> many...?", "class", ["classes", "classs", "class"], "classes")],
      [f("We have English on Monday.", "We has English on Monday.", "📖"),
       f("I do my homework.", "I does my homework.", "📝"),
       f("She has a test today.", "She have a test today.", "🏫")],
      srt("have", "has",
          [tok("I", "A", "🙋"), tok("We", "A", "👥"), tok("They", "A", "👨‍👩‍👧"),
           tok("She", "B", "👩"), tok("He", "B", "👨"), tok("My friend", "B", "🧑")]),
      [qa("What do you have on Monday?", "We have English."),
       qa("Do you do your homework?", "Yes, I do."),
       qa("Does she have a test?", "Yes, she does."),
       qa("What do you study?", "We study English.")]),

    L("Certainty & Possibility",
      [("sure", "✅"), ("maybe", "🤔"), ("true", "✔️"), ("tired", "😴"), ("right", "👍"), ("wrong", "❌")],
      "must / might / can't + be",
      ["He must be tired.", "It might be true.", "That can't be right.",
       "She must be happy.", "It might be cold.", "He can't be here."],
      [g("He must ___ tired.", ["be", "is"], "be", "😴"),
       g("It might ___ true.", ["be", "are"], "be", "✔️"),
       g("She ___ be happy.", ["must", "musts"], "must", "😊"),
       g("That can't ___ right.", ["be", "is"], "be", "❌")],
      [t("he must ->", "must", ["must be", "must is", "must are"], "must be"),
       t("it might ->", "might", ["might be", "might is", "might are"], "might be"),
       t("that can't ->", "can't", ["can't be", "can't is", "can't are"], "can't be")],
      [f("He must be tired.", "He must is tired.", "😴"),
       f("It might be true.", "It might is true.", "✔️"),
       f("That can't be right.", "That can't is right.", "❌"),
       f("She must be happy.", "She musts be happy.", "😊")],
      srt("sure", "maybe",
          [tok("must be", "A", "✅"), tok("can't be", "A", "🚫"), tok("has to be", "A", "💯"),
           tok("might be", "B", "🤔"), tok("may be", "B", "🤷"), tok("could be", "B", "❓")]),
      [qa("Why is he sleeping?", "He must be tired."),
       qa("Is that answer right?", "No, it can't be right."),
       qa("Is it true?", "It might be true."),
       qa("Where is she?", "She might be at home.")]),

    L("Expressing Preferences",
      [("tea", "🍵"), ("coffee", "☕"), ("juice", "🧃"), ("walk", "🚶"), ("swim", "🏊"), ("read", "📖")],
      "prefer ... to / would rather",
      ["I prefer tea to coffee.", "I would rather walk.", "She prefers juice.",
       "I like tea better.", "We would rather stay.", "He prefers cats to dogs."],
      [g("I prefer tea ___ coffee.", ["to", "than"], "to", "🍵"),
       g("I would rather ___.", ["walk", "to walk"], "walk", "🚶"),
       g("She ___ juice.", ["prefers", "prefer"], "prefers", "🧃"),
       g("I would rather ___ tea.", ["have", "to have"], "have", "🍵")],
      [t("she + prefer ->", "prefer", ["prefers", "prefer", "preferz"], "prefers"),
       t("he + like ->", "like", ["likes", "like", "likez"], "likes"),
       t("one drink -> many...?", "drink", ["drinks", "drinkes", "drink"], "drinks")],
      [f("I prefer tea to coffee.", "I prefer tea than coffee.", "🍵"),
       f("She prefers juice.", "She prefer juice.", "🧃"),
       f("I would rather walk.", "I would rather walks.", "🚶")],
      srt("prefer", "would rather",
          [tok("tea", "A", "🍵"), tok("juice", "A", "🧃"), tok("coffee", "A", "☕"),
           tok("walk", "B", "🚶"), tok("swim", "B", "🏊"), tok("read", "B", "📖")]),
      [qa("Do you want tea or coffee?", "I prefer tea."),
       qa("Shall we walk or drive?", "I would rather walk."),
       qa("Which do you like better?", "I like tea better."),
       qa("Does she like coffee?", "No, she prefers juice.")]),

    L("Asking & Giving Permission",
      [("may", "🙏"), ("please", "🥺"), ("sure", "👍"), ("open", "🚪"), ("help", "🤝"), ("sit", "🪑")],
      "Can / May I ...?",
      ["Can I go, please?", "May I help you?", "Yes, you can.",
       "No, you can't.", "May I open it?", "Can I sit here?"],
      [g("Can I ___, please?", ["go", "to go"], "go", "🚶"),
       g("May I ___ you?", ["help", "to help"], "help", "🤝"),
       g("___ I open the door?", ["May", "Mays"], "May", "🚪"),
       g("Yes, you ___.", ["can", "cans"], "can", "👍")],
      [t("can + go ->", "can", ["can go", "can goes", "can to go"], "can go"),
       t("may + help ->", "may", ["may help", "may helps", "may to help"], "may help"),
       t("can + open ->", "can", ["can open", "can opens", "can to open"], "can open")],
      [f("Can I go, please?", "Can I goes, please?", "🚶"),
       f("May I help you?", "May I helps you?", "🤝"),
       f("May I open it?", "May I opens it?", "🚪")],
      srt("Yes, you can", "No, you can't",
          [tok("Sure", "A", "👍"), tok("Of course", "A", "😊"), tok("Go ahead", "A", "✅"),
           tok("Sorry, no", "B", "🙅"), tok("Not now", "B", "⏳"), tok("Please don't", "B", "🚫")]),
      [qa("Can I go, please?", "Yes, you can."),
       qa("May I open the window?", "No, you can't."),
       qa("May I help you?", "Yes, please."),
       qa("Can I sit here?", "Sure, go ahead.")]),

    L("Offers & Suggestions",
      [("play", "🎮"), ("help", "🤝"), ("start", "🏁"), ("share", "🤲"), ("rest", "😌"), ("dance", "💃")],
      "Shall I / Let's / Why don't we",
      ["Let's play.", "Shall I help you?", "Why don't we go?",
       "Let's start now.", "Shall I open it?", "Why don't we rest?"],
      [g("Let's ___ now.", ["start", "starts"], "start", "🏁"),
       g("Shall I ___ you?", ["help", "helps"], "help", "🤝"),
       g("Why don't we ___?", ["play", "plays"], "play", "🎮"),
       g("Let's ___ the toys.", ["share", "shares"], "share", "🤲")],
      [t("let's + play ->", "play", ["let's play", "let's plays", "let's to play"], "let's play"),
       t("shall I + help ->", "help", ["shall I help", "shall I helps", "shall I to help"], "shall I help"),
       t("why don't we + go ->", "go", ["why don't we go", "why don't we goes", "why don't we to go"], "why don't we go")],
      [f("Let's play now.", "Let's plays now.", "🎮"),
       f("Shall I help you?", "Shall I helps you?", "🤝"),
       f("Why don't we go?", "Why don't we goes?", "🚶"),
       f("Let's start now.", "Let's starts now.", "🏁")],
      srt("Shall I", "Let's",
          [tok("Shall I help?", "A", "🤝"), tok("Shall I go?", "A", "🚶"), tok("Shall I start?", "A", "🏁"),
           tok("Let's play.", "B", "🎮"), tok("Let's rest.", "B", "😌"), tok("Let's dance.", "B", "💃")]),
      [qa("Shall I help you?", "Yes, please."),
       qa("What shall we do?", "Let's play a game."),
       qa("Why don't we go out?", "Good idea!"),
       qa("Shall I open the door?", "No, thank you.")]),

    L("Giving & Following Advice",
      [("sleep", "😴"), ("rest", "😌"), ("study", "📚"), ("drink", "🥤"), ("relax", "🧘"), ("ask", "🙋")],
      "You should + verb",
      ["You should sleep early.", "If I were you, I would ask.", "You should rest.",
       "You should drink water.", "You shouldn't worry.", "If I were you, I would study."],
      [g("You should ___ early.", ["sleep", "sleeps"], "sleep", "😴"),
       g("You should ___ water.", ["drink", "drinks"], "drink", "🥤"),
       g("If I ___ you, I would ask.", ["were", "was"], "were", "🙋"),
       g("You should ___ more.", ["study", "studies"], "study", "📚")],
      [t("should + sleep ->", "sleep", ["should sleep", "should sleeps", "should to sleep"], "should sleep"),
       t("should + rest ->", "rest", ["should rest", "should rests", "should to rest"], "should rest"),
       t("should + study ->", "study", ["should study", "should studys", "should to study"], "should study")],
      [f("You should sleep early.", "You should sleeps early.", "😴"),
       f("You should drink water.", "You should drinks water.", "🥤"),
       f("If I were you, I would ask.", "If I was you, I would ask.", "🙋"),
       f("You should rest now.", "You should rests now.", "😌")],
      srt("should", "shouldn't",
          [tok("sleep well", "A", "😴"), tok("eat fruit", "A", "🍎"), tok("drink water", "A", "🥤"),
           tok("eat junk food", "B", "🍔"), tok("stay up late", "B", "🌙"), tok("worry too much", "B", "😟")]),
      [qa("I feel tired.", "You should sleep early."),
       qa("What should I do?", "If I were you, I would ask."),
       qa("I have a test tomorrow.", "You should study tonight."),
       qa("I'm thirsty.", "You should drink water.")]),
])
