# -*- coding: utf-8 -*-
from grammar_helpers import g, t, f, tok, srt, qa, L, W

# ===========================================================================
# WORLD 19 — Everyday Express  (functional / conversation English)
# Arc: apologizing, asking for help, phone, email, small talk, describing
# people, family, airport, hotel, transport & directions. Teach useful
# PATTERNS (question -> answer), not vocabulary lists. All phrases natural.
# ===========================================================================
WORLD = W("Everyday Express", "Everyday phrases & situations", [

    L("Apologizing",
      [("sorry", "😔"), ("late", "⏰"), ("okay", "👍"), ("fine", "🙂"), ("oops", "😬"), ("excuse", "🙏")],
      "I'm sorry / That's okay",
      ["I'm sorry I'm late.",
       "That's okay.",
       "I am so sorry.",
       "It's not your fault.",
       "Please forgive me.",
       "Don't worry about it."],
      [g("___ okay.", ["That's", "Thats"], "That's", "👍"),
       g("I ___ sorry.", ["am", "is"], "am", "😔"),
       g("Please ___ me.", ["forgive", "forgives"], "forgive", "🙏"),
       g("It's not your ___.", ["fault", "faults"], "fault", "😬")],
      [t("I am -> short", "I am", ["I'm", "Im", "Iam"], "I'm"),
       t("that is -> short", "that is", ["that's", "thats", "thas"], "that's"),
       t("do not -> short", "do not", ["don't", "dont", "donot"], "don't")],
      [f("I'm sorry I'm late.", "I'm sorry I'm lately.", "⏰"),
       f("That's okay.", "That okay.", "👍"),
       f("I am so sorry.", "I is so sorry.", "😔"),
       f("Please forgive me.", "Please forgives me.", "🙏")],
      srt("Apology", "Response",
          [tok("I'm sorry.", "A", "😔"), tok("It's my fault.", "A", "😬"), tok("Please forgive me.", "A", "🙏"),
           tok("That's okay.", "B", "👍"), tok("No problem.", "B", "🙂"), tok("Don't worry.", "B", "😌")]),
      [qa("I'm sorry I'm late.", "That's okay."),
       qa("I'm sorry.", "No problem."),
       qa("It was my fault.", "Don't worry about it."),
       qa("Please forgive me.", "It's all right.")]),

    L("Asking for Help",
      [("help", "🆘"), ("open", "🔓"), ("door", "🚪"), ("please", "🙏"), ("carry", "📦"), ("close", "🔒")],
      "Can you...? / Could you...?",
      ["Can you help me, please?",
       "Could you open the door?",
       "Can you carry this bag?",
       "Could you close the window?",
       "Please help me now."],
      [g("___ you help me?", ["Can", "Cans"], "Can", "🆘"),
       g("Could you ___ the door?", ["open", "opens"], "open", "🚪"),
       g("Can you ___ me, please?", ["help", "helps"], "help", "🙋"),
       g("Could you ___ the window?", ["close", "closes"], "close", "🔒")],
      [t("can not -> short", "cannot", ["can't", "cant", "cann't"], "can't"),
       t("could not -> short", "could not", ["couldn't", "couldnt", "could'nt"], "couldn't"),
       t("would not -> short", "would not", ["wouldn't", "wouldnt", "would'nt"], "wouldn't")],
      [f("Can you help me?", "Can you helps me?", "🙋"),
       f("Could you open the door?", "Could you opens the door?", "🚪"),
       f("Can you carry this bag?", "Can you carrying this bag?", "📦"),
       f("Please close the window.", "Please closes the window.", "🔒")],
      srt("Ask for help", "Say yes",
          [tok("Can you help me?", "A", "🆘"), tok("Could you open it?", "A", "🚪"), tok("Please help me.", "A", "🙏"),
           tok("Sure, I can.", "B", "👍"), tok("Yes, of course.", "B", "🙂"), tok("No problem.", "B", "😌")]),
      [qa("Can you help me, please?", "Sure, I can."),
       qa("Could you open the door?", "Yes, of course."),
       qa("Can you carry this bag?", "No problem."),
       qa("Could you close the window?", "Okay, I will.")]),

    L("Telephone English",
      [("hello", "👋"), ("phone", "📱"), ("call", "📞"), ("speak", "🗣️"), ("hold", "✋"), ("back", "🔙")],
      "Hello, this is... / Can I speak to...?",
      ["Hello, this is Dan.",
       "Can I speak to Mom?",
       "Please hold the line.",
       "I will call you back.",
       "Who is calling, please?"],
      [g("Hello, this ___ Dan.", ["is", "are"], "is", "📱"),
       g("Can I ___ to Mom?", ["speak", "speaks"], "speak", "🗣️"),
       g("Please ___ the line.", ["hold", "holds"], "hold", "✋"),
       g("Who ___ calling?", ["is", "are"], "is", "📞")],
      [t("I will -> short", "I will", ["I'll", "Ill", "I'l"], "I'll"),
       t("who is -> short", "who is", ["who's", "whos", "whose"], "who's"),
       t("I am -> short", "I am", ["I'm", "Im", "Iam"], "I'm")],
      [f("Hello, this is Dan.", "Hello, this are Dan.", "📱"),
       f("Can I speak to Mom?", "Can I speaks to Mom?", "🗣️"),
       f("I will call you back.", "I will calls you back.", "🔙"),
       f("Please hold the line.", "Please holds the line.", "✋")],
      srt("Start a call", "Answer",
          [tok("Hello, this is Dan.", "A", "👋"), tok("Can I speak to Mom?", "A", "📞"), tok("Is Mom there?", "A", "📱"),
           tok("Speaking.", "B", "🗣️"), tok("Who is calling?", "B", "❓"), tok("Please hold on.", "B", "✋")]),
      [qa("Hello, this is Dan.", "Hi Dan, how are you?"),
       qa("Can I speak to Mom?", "Yes, please hold on."),
       qa("Who is calling, please?", "This is Ben."),
       qa("Is Mom there?", "No, she is out.")]),

    L("Email & Letter Basics",
      [("dear", "💌"), ("thank", "🙏"), ("wishes", "✨"), ("gift", "🎁"), ("letter", "✉️"), ("write", "✍️")],
      "Dear... / Thank you / Best wishes",
      ["Dear Grandma, thank you.",
       "Thank you for the gift.",
       "Best wishes, Dan.",
       "I miss you a lot.",
       "Please write back soon.",
       "I hope you are well."],
      [g("Thank you ___ the gift.", ["for", "to"], "for", "🎁"),
       g("___ Grandma, thank you.", ["Dear", "Deer"], "Dear", "💌"),
       g("Best ___, Dan.", ["wishes", "wish"], "wishes", "✨"),
       g("Please write ___ soon.", ["back", "backs"], "back", "✍️")],
      [t("one wish -> many...?", "wish", ["wishes", "wishs", "wish"], "wishes"),
       t("one gift -> many...?", "gift", ["gifts", "giftes", "gift"], "gifts"),
       t("one letter -> many...?", "letter", ["letters", "lettres", "letter"], "letters")],
      [f("Thank you for the gift.", "Thank you at the gift.", "🎁"),
       f("Best wishes, Dan.", "Best wish, Dan.", "✨"),
       f("I hope you are well.", "I hope you is well.", "🙏"),
       f("Please write back soon.", "Please writes back soon.", "✍️")],
      srt("Start a letter", "End a letter",
          [tok("Dear Grandma,", "A", "💌"), tok("Dear Sir,", "A", "✉️"), tok("Hello Dan,", "A", "👋"),
           tok("Best wishes,", "B", "✨"), tok("Thank you,", "B", "🙏"), tok("See you soon,", "B", "🌟")]),
      [qa("How do you start a letter?", "Dear Grandma,"),
       qa("How do you end a letter?", "Best wishes, Dan."),
       qa("What do you say for a gift?", "Thank you very much."),
       qa("Where do you write your name?", "At the end.")]),

    L("Small Talk",
      [("fine", "🙂"), ("thanks", "🙏"), ("meet", "🤝"), ("good", "👍"), ("great", "😄"), ("well", "😊")],
      "How are you? / Nice to meet you.",
      ["How are you?",
       "I'm fine, thanks.",
       "Nice to meet you.",
       "It's good to see you.",
       "How is your day?",
       "I am very well, thanks."],
      [g("How ___ you?", ["are", "is"], "are", "🙂"),
       g("Nice ___ meet you.", ["to", "too"], "to", "🤝"),
       g("I'm fine, ___.", ["thanks", "thank"], "thanks", "🙏"),
       g("How ___ your day?", ["is", "are"], "is", "😄")],
      [t("how is -> short", "how is", ["how's", "hows", "howse"], "how's"),
       t("it is -> short", "it is", ["it's", "its", "its'"], "it's"),
       t("I am -> short", "I am", ["I'm", "Im", "Iam"], "I'm")],
      [f("How are you?", "How is you?", "🙂"),
       f("Nice to meet you.", "Nice too meet you.", "🤝"),
       f("It's good to see you.", "It's good too see you.", "👍"),
       f("I am very well.", "I is very well.", "😊")],
      srt("Greeting", "Reply",
          [tok("How are you?", "A", "🙂"), tok("How is your day?", "A", "😄"), tok("Nice to meet you.", "A", "🤝"),
           tok("I'm fine, thanks.", "B", "😊"), tok("Not bad, thanks.", "B", "👍"), tok("Very well, thanks.", "B", "😄")]),
      [qa("How are you?", "I'm fine, thanks."),
       qa("Nice to meet you.", "Nice to meet you, too."),
       qa("How is your day?", "It's really good."),
       qa("How is your family?", "They are all well.")]),

    L("Describing People",
      [("tall", "📏"), ("hair", "💇"), ("kind", "🤗"), ("eyes", "👀"), ("short", "📐"), ("funny", "😄")],
      "has got / is (describing)",
      ["She has long hair.",
       "He is tall and kind.",
       "She has got blue eyes.",
       "He has got short hair.",
       "They are very funny.",
       "I have big brown eyes."],
      [g("She ___ got blue eyes.", ["has", "have"], "has", "👀"),
       g("He ___ tall and kind.", ["is", "are"], "is", "📏"),
       g("They ___ very funny.", ["are", "is"], "are", "😄"),
       g("I ___ got brown eyes.", ["have", "has"], "have", "👀")],
      [t("I have -> she ___", "have", ["has", "haves", "have"], "has"),
       t("one eye -> many...?", "eye", ["eyes", "eyies", "eye"], "eyes"),
       t("she is -> short", "she is", ["she's", "shes", "shese"], "she's")],
      [f("She has got blue eyes.", "She have got blue eyes.", "👀"),
       f("He is tall and kind.", "He are tall and kind.", "📏"),
       f("They are very funny.", "They is very funny.", "😄"),
       f("She has long hair.", "She have long hair.", "💇")],
      srt("has got (features)", "is (like)",
          [tok("has blue eyes", "A", "👀"), tok("has long hair", "A", "💇"), tok("has short hair", "A", "💇"),
           tok("is tall", "B", "📏"), tok("is kind", "B", "🤗"), tok("is funny", "B", "😄")]),
      [qa("What does she look like?", "She has long hair."),
       qa("Is he tall?", "Yes, he is very tall."),
       qa("What color are her eyes?", "They are blue."),
       qa("What is he like?", "He is kind and funny.")]),

    L("Family Relationships",
      [("aunt", "👩"), ("uncle", "👨"), ("niece", "👧"), ("cousin", "🧒"), ("sister", "👭"), ("mother", "🤱")],
      "possessive 's (family)",
      ["My father's brother is my uncle.",
       "My mother's sister is my aunt.",
       "My aunt's daughter is my cousin.",
       "This is my sister's book.",
       "My uncle's son is my cousin."],
      [g("My father's brother is my ___.", ["uncle", "aunt"], "uncle", "👨"),
       g("My mother's sister is my ___.", ["aunt", "uncle"], "aunt", "👩"),
       g("This is my ___ book.", ["sister's", "sisters"], "sister's", "📕"),
       g("My ___ daughter is my cousin.", ["aunt's", "aunts"], "aunt's", "🧒")],
      [t("mother + 's ->", "mother", ["mother's", "mothers", "mothes"], "mother's"),
       t("father + 's ->", "father", ["father's", "fathers", "fathes"], "father's"),
       t("one cousin -> many...?", "cousin", ["cousins", "cousines", "cousin"], "cousins")],
      [f("My father's brother is my uncle.", "My fathers brother is my uncle.", "👨"),
       f("My mother's sister is my aunt.", "My mothers sister is my aunt.", "👩"),
       f("This is my sister's book.", "This is my sisters book.", "📕"),
       f("My aunt's daughter is my cousin.", "My aunts daughter is my cousin.", "🧒")],
      srt("'s = belongs to", "s = more than one",
          [tok("mother's bag", "A", "👜"), tok("father's car", "A", "🚗"), tok("sister's book", "A", "📕"),
           tok("two sisters", "B", "👭"), tok("three cousins", "B", "🧒"), tok("many aunts", "B", "👩")]),
      [qa("Who is your mother's sister?", "She is my aunt."),
       qa("Who is your father's brother?", "He is my uncle."),
       qa("Who is your aunt's daughter?", "She is my cousin."),
       qa("Who is your uncle's son?", "He is my cousin, too.")]),

    L("Travel & Airport",
      [("gate", "🚪"), ("ticket", "🎫"), ("bag", "🧳"), ("plane", "✈️"), ("seat", "💺"), ("pass", "🛂")],
      "Where is...? / I would like...",
      ["Where is the gate?",
       "I would like a ticket, please.",
       "Here is my passport.",
       "My plane leaves at noon.",
       "Where can I find my seat?"],
      [g("I would like ___ ticket.", ["a", "an"], "a", "🎫"),
       g("Where ___ the gate?", ["is", "are"], "is", "🚪"),
       g("Where ___ the restrooms?", ["are", "is"], "are", "🚻"),
       g("Can I ___ my bag here?", ["leave", "leaves"], "leave", "🧳")],
      [t("one ticket -> many...?", "ticket", ["tickets", "ticketes", "ticket"], "tickets"),
       t("one bag -> many...?", "bag", ["bags", "bages", "bag"], "bags"),
       t("I would -> short", "I would", ["I'd", "Id", "I'ld"], "I'd")],
      [f("Where is the gate?", "Where are the gate?", "🚪"),
       f("I would like a ticket.", "I would like an ticket.", "🎫"),
       f("Here is my passport.", "Here are my passport.", "🛂"),
       f("Where are the restrooms?", "Where is the restrooms?", "🚻")],
      srt("is (one thing)", "are (many things)",
          [tok("the gate is here", "A", "🚪"), tok("my seat is free", "A", "💺"), tok("the plane is late", "A", "✈️"),
           tok("the bags are here", "B", "🧳"), tok("the seats are free", "B", "💺"), tok("the gates are open", "B", "🚪")]),
      [qa("Where is the gate?", "It is over there."),
       qa("Can I see your ticket?", "Yes, here it is."),
       qa("What time is the plane?", "It leaves at noon."),
       qa("Is this my seat?", "No, yours is there.")]),

    L("Hotel & Accommodation",
      [("room", "🚪"), ("key", "🔑"), ("bed", "🛏️"), ("hotel", "🏨"), ("towel", "🧻"), ("night", "🌙")],
      "I would like a room / Do you have...?",
      ["I would like a room, please.",
       "Do you have a key?",
       "The room has a big bed.",
       "Do you have a towel?",
       "I will stay for one night."],
      [g("I would like ___ room.", ["a", "an"], "a", "🚪"),
       g("Do you ___ a key?", ["have", "has"], "have", "🔑"),
       g("The room ___ a big bed.", ["has", "have"], "has", "🛏️"),
       g("I will stay for one ___.", ["night", "nights"], "night", "🌙")],
      [t("one room -> many...?", "room", ["rooms", "roomes", "room"], "rooms"),
       t("one key -> many...?", "key", ["keys", "keies", "key"], "keys"),
       t("do not -> short", "do not", ["don't", "dont", "donot"], "don't")],
      [f("Do you have a key?", "Do you has a key?", "🔑"),
       f("The room has a bed.", "The room have a bed.", "🛏️"),
       f("I would like a room.", "I would like an room.", "🚪"),
       f("I will stay one night.", "I will stay one nights.", "🌙")],
      srt("have (I / you)", "has (he / she / it)",
          [tok("I have a key", "A", "🔑"), tok("you have a room", "A", "🚪"), tok("we have towels", "A", "🧻"),
           tok("she has a key", "B", "🔑"), tok("the room has a bed", "B", "🛏️"), tok("he has a towel", "B", "🧻")]),
      [qa("Do you have a room?", "Yes, we do."),
       qa("Can I have my key?", "Here you are."),
       qa("How many nights?", "Just one night."),
       qa("Do you have a towel?", "Yes, here it is.")]),

    L("Transport & Directions",
      [("bus", "🚌"), ("left", "⬅️"), ("right", "➡️"), ("park", "🏞️"), ("stop", "🛑"), ("train", "🚆")],
      "How do I get to...? / Take the...",
      ["How do I get to the park?",
       "Take the bus and turn left.",
       "Turn right at the stop.",
       "The park is on the left.",
       "Take the train to town."],
      [g("How do I ___ to the park?", ["get", "gets"], "get", "🏞️"),
       g("___ the bus to town.", ["Take", "Takes"], "Take", "🚌"),
       g("Turn right ___ the stop.", ["at", "on"], "at", "🛑"),
       g("The park is ___ the left.", ["on", "in"], "on", "⬅️")],
      [t("one bus -> many...?", "bus", ["buses", "buss", "bus"], "buses"),
       t("one train -> many...?", "train", ["trains", "traines", "train"], "trains"),
       t("one stop -> many...?", "stop", ["stops", "stopes", "stop"], "stops")],
      [f("Take the bus to town.", "Takes the bus to town.", "🚌"),
       f("Turn right at the stop.", "Turn right on the stop.", "🛑"),
       f("The park is on the left.", "The park is in the left.", "⬅️"),
       f("How do I get there?", "How do I gets there?", "🏞️")],
      srt("Ask the way", "Give the way",
          [tok("How do I get there?", "A", "❓"), tok("Where is the park?", "A", "🏞️"), tok("Is it far?", "A", "📏"),
           tok("Take the bus.", "B", "🚌"), tok("Turn left.", "B", "⬅️"), tok("Go straight on.", "B", "⬆️")]),
      [qa("How do I get to the park?", "Take the bus and turn left."),
       qa("Where is the bus stop?", "It is on the right."),
       qa("Is the park far?", "No, it is very near."),
       qa("How do I get to town?", "Take the train.")]),
])
