# -*- coding: utf-8 -*-
# ===========================================================================
# WORLD 20 — Big Idea Boulevard  (Levels 291-300)
# The FINAL world: big real-life topics that REVIEW earlier grammar patterns.
# Every sentence is short and correct. Patterns revisited: it is + adjective /
# present continuous, prepositions of time, play/do/go collocations,
# like/enjoy + -ing, can + base, comparatives with "than", should/must + base,
# present simple -s, passive/past facts, to be + feeling + because.
# ===========================================================================
from grammar_helpers import g, t, f, tok, srt, qa, L, W

WORLD = W("Big Idea Boulevard", "Big topics, real grammar", [

    L("Weather & Small Talk",
      [("sunny", "☀️"), ("rainy", "🌧️"), ("cloudy", "☁️"), ("windy", "🌬️"), ("cold", "🥶"), ("warm", "🌡️")],
      "It is + weather",
      ["It is sunny today.", "It is raining now.", "The sky is cloudy.",
       "It is very cold.", "It is windy outside.", "How is the weather?"],
      [g("It ___ sunny today.", ["is", "are"], "is", "☀️"),
       g("It is ___ now.", ["raining", "rain"], "raining", "🌧️"),
       g("The sky ___ cloudy.", ["is", "are"], "is", "☁️"),
       g("It ___ windy outside.", ["is", "be"], "is", "🌬️")],
      [t("rain -> it is ___", "rain", ["raining", "rainning", "rains"], "raining"),
       t("snow -> it is ___", "snow", ["snowing", "snowwing", "snows"], "snowing"),
       t("blow -> it is ___", "blow", ["blowing", "bloing", "blows"], "blowing")],
      [f("It is sunny today.", "It are sunny today.", "☀️"),
       f("It is raining now.", "It is rain now.", "🌧️"),
       f("The sky is cloudy.", "The sky are cloudy.", "☁️")],
      srt("It is + adjective", "It is + -ing",
          [tok("sunny", "A", "☀️"), tok("cold", "A", "🥶"), tok("windy", "A", "🌬️"),
           tok("raining", "B", "🌧️"), tok("snowing", "B", "❄️"), tok("blowing", "B", "💨")]),
      [qa("How is the weather?", "It is sunny."),
       qa("Is it raining?", "Yes, it is."),
       qa("Is it cold today?", "No, it is warm."),
       qa("What is the weather like?", "It is cloudy.")]),

    L("Seasons & Holidays",
      [("winter", "❄️"), ("summer", "☀️"), ("spring", "🌸"), ("autumn", "🍂"), ("party", "🎉"), ("holiday", "🎊")],
      "in + season / time",
      ["In winter it is cold.", "In summer it is hot.", "Flowers grow in spring.",
       "We have a party in December.", "My birthday is in May.", "We ski in winter."],
      [g("___ winter it is cold.", ["In", "On"], "In", "❄️"),
       g("We swim ___ summer.", ["in", "at"], "in", "☀️"),
       g("My birthday is ___ May.", ["in", "on"], "in", "🎂"),
       g("We have a party ___ December.", ["in", "on"], "in", "🎉")],
      [t("one party -> two ___", "party", ["parties", "partys", "party"], "parties"),
       t("one holiday -> two ___", "holiday", ["holidays", "holidayes", "holiday"], "holidays"),
       t("one gift -> two ___", "gift", ["gifts", "giftes", "gift"], "gifts")],
      [f("In winter it is cold.", "On winter it is cold.", "❄️"),
       f("We have a party in December.", "We have a party on December.", "🎉"),
       f("My birthday is in May.", "My birthday is at May.", "🎂"),
       f("Flowers grow in spring.", "Flowers grows in spring.", "🌸")],
      srt("in (month/season)", "on (day)",
          [tok("in winter", "A", "❄️"), tok("in summer", "A", "☀️"), tok("in May", "A", "🎂"),
           tok("on Monday", "B", "📅"), tok("on Sunday", "B", "📆"), tok("on my birthday", "B", "🎈")]),
      [qa("When is your birthday?", "It is in May."),
       qa("Do you like winter?", "Yes, I do."),
       qa("What do we do in summer?", "We swim in the sea."),
       qa("When is the party?", "It is in December.")]),

    L("Sports & Exercise",
      [("soccer", "⚽"), ("tennis", "🎾"), ("swimming", "🏊"), ("running", "🏃"), ("yoga", "🧘"), ("karate", "🥋")],
      "play / go / do + sport",
      ["I play soccer.", "I go swimming.", "I do yoga.",
       "She plays tennis.", "We go running.", "He does karate."],
      [g("I ___ soccer.", ["play", "go"], "play", "⚽"),
       g("I ___ swimming.", ["go", "play"], "go", "🏊"),
       g("I ___ yoga.", ["do", "play"], "do", "🧘"),
       g("She ___ tennis.", ["plays", "goes"], "plays", "🎾")],
      [t("I play -> she ___", "play", ["plays", "playes", "play"], "plays"),
       t("I go -> she ___", "go", ["goes", "gos", "go"], "goes"),
       t("I do -> she ___", "do", ["does", "dos", "do"], "does")],
      [f("I play soccer.", "I go soccer.", "⚽"),
       f("I go swimming.", "I play swimming.", "🏊"),
       f("She plays tennis.", "She play tennis.", "🎾"),
       f("He does karate.", "He do karate.", "🥋")],
      srt("play", "go",
          [tok("soccer", "A", "⚽"), tok("tennis", "A", "🎾"), tok("basketball", "A", "🏀"),
           tok("swimming", "B", "🏊"), tok("running", "B", "🏃"), tok("skiing", "B", "⛷️")]),
      [qa("What sport do you play?", "I play soccer."),
       qa("Do you go swimming?", "Yes, I do."),
       qa("Does she play tennis?", "Yes, she does."),
       qa("What do you do to relax?", "I do yoga.")]),

    L("Hobbies & Free Time",
      [("reading", "📖"), ("cooking", "🍳"), ("dancing", "💃"), ("singing", "🎤"), ("drawing", "✏️"), ("painting", "🎨")],
      "like / enjoy + -ing",
      ["I like reading.", "She enjoys painting.", "We like dancing.",
       "He enjoys cooking.", "I enjoy singing.", "They like drawing."],
      [g("I like ___.", ["reading", "read"], "reading", "📖"),
       g("She enjoys ___.", ["painting", "paint"], "painting", "🎨"),
       g("We like ___.", ["dancing", "dance"], "dancing", "💃"),
       g("He ___ cooking.", ["enjoys", "enjoy"], "enjoys", "🍳")],
      [t("read -> I like ___", "read", ["reading", "readding", "reads"], "reading"),
       t("dance -> I like ___", "dance", ["danceing", "dancing", "dances"], "dancing"),
       t("cook -> I like ___", "cook", ["cooking", "cookking", "cooks"], "cooking")],
      [f("I like reading.", "I like read.", "📖"),
       f("She enjoys painting.", "She enjoy painting.", "🎨"),
       f("We like dancing.", "We likes dancing.", "💃"),
       f("He enjoys cooking.", "He enjoys cook.", "🍳")],
      srt("just add -ing", "drop e, add -ing",
          [tok("read -> reading", "A", "📖"), tok("cook -> cooking", "A", "🍳"), tok("sing -> singing", "A", "🎤"),
           tok("dance -> dancing", "B", "💃"), tok("bake -> baking", "B", "🧁"), tok("write -> writing", "B", "✍️")]),
      [qa("What do you like doing?", "I like reading."),
       qa("Does she enjoy painting?", "Yes, she does."),
       qa("Do you enjoy cooking?", "No, I don't."),
       qa("What is your hobby?", "I enjoy singing.")]),

    L("Music & Entertainment",
      [("guitar", "🎸"), ("piano", "🎹"), ("drums", "🥁"), ("violin", "🎻"), ("song", "🎵"), ("music", "🎶")],
      "can + play",
      ["I can play the guitar.", "She sings very well.", "He can play the piano.",
       "We sing a song.", "They play music.", "I can play the drums."],
      [g("I can ___ the guitar.", ["play", "plays"], "play", "🎸"),
       g("She ___ very well.", ["sings", "sing"], "sings", "🎵"),
       g("He can ___ the piano.", ["play", "playing"], "play", "🎹"),
       g("They ___ music.", ["play", "plays"], "play", "🎶")],
      [t("I sing -> she ___", "sing", ["sings", "singes", "sing"], "sings"),
       t("I play -> he ___", "play", ["plaies", "plays", "play"], "plays"),
       t("I dance -> she ___", "dance", ["dances", "dancs", "dance"], "dances")],
      [f("I can play the guitar.", "I can plays the guitar.", "🎸"),
       f("She sings very well.", "She sing very well.", "🎵"),
       f("He can play the piano.", "He can plays the piano.", "🎹"),
       f("They play music.", "They plays music.", "🎶")],
      srt("can + base", "she / he + verb-s",
          [tok("can sing", "A", "🎤"), tok("can play", "A", "🎸"), tok("can dance", "A", "💃"),
           tok("she sings", "B", "🎵"), tok("he plays", "B", "🎹"), tok("she dances", "B", "💃")]),
      [qa("Can you play the guitar?", "Yes, I can."),
       qa("Can she play the piano?", "No, she can't."),
       qa("What can you play?", "I can play the drums."),
       qa("Does he sing well?", "Yes, he does.")]),

    L("Animals & Nature",
      [("whale", "🐋"), ("shark", "🦈"), ("tiger", "🐅"), ("eagle", "🦅"), ("snake", "🐍"), ("mouse", "🐭")],
      "bigger than / can",
      ["A whale is bigger than a shark.", "Birds can fly.", "A tiger is faster than a snake.",
       "Fish can swim.", "An eagle is smaller than a whale.", "Snakes can move fast."],
      [g("A whale is bigger ___ a shark.", ["than", "then"], "than", "🐋"),
       g("A tiger is ___ than a snake.", ["faster", "fast"], "faster", "🐅"),
       g("Birds ___ fly.", ["can", "cans"], "can", "🐦"),
       g("A mouse is ___ than a tiger.", ["smaller", "small"], "smaller", "🐭")],
      [t("big -> ___ than", "big", ["bigger", "more big", "biger"], "bigger"),
       t("fast -> ___ than", "fast", ["more fast", "faster", "fastest"], "faster"),
       t("small -> ___ than", "small", ["smaller", "smallest", "smaler"], "smaller")],
      [f("A whale is bigger than a shark.", "A whale is bigger then a shark.", "🐋"),
       f("A tiger is faster than a snake.", "A tiger is faster as a snake.", "🐅"),
       f("Birds can fly.", "Birds can flies.", "🐦"),
       f("Fish can swim.", "Fish cans swim.", "🐟")],
      srt("comparison (than)", "can (ability)",
          [tok("bigger than", "A", "🐋"), tok("faster than", "A", "🐅"), tok("smaller than", "A", "🐭"),
           tok("can fly", "B", "🐦"), tok("can swim", "B", "🐟"), tok("can run", "B", "🐆")]),
      [qa("Is a whale bigger than a shark?", "Yes, it is."),
       qa("Can birds fly?", "Yes, they can."),
       qa("Can a snake fly?", "No, it can't."),
       qa("Which is faster, a tiger or a snake?", "A tiger is faster.")]),

    L("Environment & Recycling",
      [("recycle", "♻️"), ("water", "💧"), ("plastic", "🧴"), ("bottle", "🍶"), ("planet", "🌍"), ("trash", "🗑️")],
      "should / must + base",
      ["We should recycle.", "We must not waste water.", "You should save energy.",
       "We must protect the planet.", "We should use less plastic.", "You must not drop trash."],
      [g("We ___ recycle.", ["should", "shoulds"], "should", "♻️"),
       g("We must not ___ water.", ["waste", "wastes"], "waste", "💧"),
       g("We must ___ the planet.", ["protect", "protects"], "protect", "🌍"),
       g("You should ___ energy.", ["save", "saves"], "save", "💡")],
      [t("recycles -> we should ___", "recycle", ["recycle", "recycles", "recycling"], "recycle"),
       t("saves -> we should ___", "save", ["saves", "save", "saving"], "save"),
       t("protects -> we must ___", "protect", ["protects", "protecting", "protect"], "protect")],
      [f("We should recycle.", "We should recycles.", "♻️"),
       f("We must protect the planet.", "We must protects the planet.", "🌍"),
       f("You should save energy.", "You should saves energy.", "💡"),
       f("We must not waste water.", "We must not wastes water.", "💧")],
      srt("we should (good)", "we should not (bad)",
          [tok("recycle bottles", "A", "♻️"), tok("save water", "A", "💧"), tok("plant trees", "A", "🌳"),
           tok("waste water", "B", "🚱"), tok("drop trash", "B", "🗑️"), tok("burn plastic", "B", "🔥")]),
      [qa("What should we do?", "We should recycle."),
       qa("Should we waste water?", "No, we should not."),
       qa("Must we protect the planet?", "Yes, we must."),
       qa("How can we help the earth?", "We should use less plastic.")]),

    L("Technology & Digital Life",
      [("computer", "💻"), ("email", "📧"), ("phone", "📱"), ("mouse", "🖱️"), ("screen", "🖥️"), ("website", "🌐")],
      "use / can + verb",
      ["I use a computer.", "You can send an email.", "She uses a phone.",
       "We can watch videos.", "He clicks the mouse.", "I can type fast."],
      [g("I ___ a computer.", ["use", "uses"], "use", "💻"),
       g("You can ___ an email.", ["send", "sends"], "send", "📧"),
       g("She ___ a phone.", ["uses", "use"], "uses", "📱"),
       g("We can ___ videos.", ["watch", "watches"], "watch", "🎬")],
      [t("I use -> she ___", "use", ["uses", "uzes", "use"], "uses"),
       t("I click -> he ___", "click", ["clickes", "clicks", "click"], "clicks"),
       t("I watch -> she ___", "watch", ["watches", "watchs", "watch"], "watches")],
      [f("I use a computer.", "I uses a computer.", "💻"),
       f("You can send an email.", "You can sends an email.", "📧"),
       f("She uses a phone.", "She use a phone.", "📱"),
       f("He clicks the mouse.", "He click the mouse.", "🖱️")],
      srt("she / he (adds -s)", "I / we / they (base)",
          [tok("she uses", "A", "📱"), tok("he clicks", "A", "🖱️"), tok("it works", "A", "💻"),
           tok("I use", "B", "💻"), tok("we type", "B", "⌨️"), tok("they watch", "B", "🎬")]),
      [qa("Can you send an email?", "Yes, I can."),
       qa("What do you use?", "I use a computer."),
       qa("Does she use a phone?", "Yes, she does."),
       qa("Can we watch videos?", "Yes, we can.")]),

    L("Science & Invention",
      [("bulb", "💡"), ("water", "💧"), ("phone", "📱"), ("engine", "🚂"), ("steam", "♨️"), ("wheel", "☸️")],
      "was invented / boils",
      ["The bulb was invented long ago.", "Water boils at 100 degrees.", "The phone was invented by Bell.",
       "Ice melts in the sun.", "The wheel was made long ago.", "The sun gives us light."],
      [g("The bulb ___ invented long ago.", ["was", "were"], "was", "💡"),
       g("Water ___ at 100 degrees.", ["boils", "boil"], "boils", "💧"),
       g("The phone was ___ by Bell.", ["invented", "invent"], "invented", "📱"),
       g("Ice ___ in the sun.", ["melts", "melt"], "melts", "🧊")],
      [t("invent -> it was ___", "invent", ["invented", "invent", "inventing"], "invented"),
       t("make -> it was ___", "make", ["maked", "made", "making"], "made"),
       t("boil -> water ___", "boil", ["boils", "boiles", "boil"], "boils")],
      [f("The bulb was invented long ago.", "The bulb were invented long ago.", "💡"),
       f("Water boils at 100 degrees.", "Water boil at 100 degrees.", "💧"),
       f("The wheel was made long ago.", "The wheel was maked long ago.", "☸️"),
       f("Ice melts in the sun.", "Ice melt in the sun.", "🧊")],
      srt("passive (was + -ed)", "present fact",
          [tok("was invented", "A", "💡"), tok("was made", "A", "☸️"), tok("was built", "A", "🏛️"),
           tok("water boils", "B", "💧"), tok("ice melts", "B", "🧊"), tok("the sun shines", "B", "☀️")]),
      [qa("Who invented the phone?", "Bell invented the phone."),
       qa("When was the bulb invented?", "It was invented long ago."),
       qa("At what temperature does water boil?", "At 100 degrees."),
       qa("What melts in the sun?", "Ice melts in the sun.")]),

    L("Emotions & Feelings",
      [("happy", "😊"), ("sad", "😢"), ("tired", "😴"), ("angry", "😠"), ("scared", "😨"), ("proud", "😌")],
      "am/is/are + feeling + because",
      ["I am happy because it is sunny.", "She feels tired.", "He is sad because it is raining.",
       "We are proud of you.", "I am scared of the dark.", "They are angry today."],
      [g("I ___ happy today.", ["am", "is"], "am", "😊"),
       g("She ___ tired.", ["feels", "feel"], "feels", "😴"),
       g("He is sad ___ it is raining.", ["because", "so"], "because", "😢"),
       g("We ___ proud of you.", ["are", "is"], "are", "😌")],
      [t("I ___ happy", "be", ["am", "is", "are"], "am"),
       t("she ___ tired", "be", ["am", "is", "are"], "is"),
       t("they ___ angry", "be", ["am", "is", "are"], "are")],
      [f("I am happy because it is sunny.", "I is happy because it is sunny.", "😊"),
       f("She feels tired.", "She feel tired.", "😴"),
       f("We are proud of you.", "We is proud of you.", "😌"),
       f("They are angry today.", "They is angry today.", "😠")],
      srt("is (he/she/it)", "are (we/you/they)",
          [tok("he is sad", "A", "😢"), tok("she is happy", "A", "😊"), tok("it is scary", "A", "😨"),
           tok("we are proud", "B", "😌"), tok("they are angry", "B", "😠"), tok("you are tired", "B", "😴")]),
      [qa("Why are you happy?", "Because it is sunny."),
       qa("How do you feel?", "I feel tired."),
       qa("Why is he sad?", "Because it is raining."),
       qa("Are you scared?", "No, I am not.")]),
])
